### ISSUE TITLE
Test failures with vagrant 2.2.5

### ISSUE THREAD

**Issue by dcermak** [vagrant-libvirt/vagrant-libvirt#1018]
Note: the plugin appears to be working fine, although a lot of the unit tests fail. Maybe this is only problematic during installation?

### Steps to reproduce
1. Install vagrant 2.2.5 (optional, bundler will clone the vagrant git repo)
2. clone the vagrant-libvirt repository
3. `bundle install`
4. `bundle exec rspec spec`

### Expected behavior

The tests should pass as they did with Vagrant < 2.2.5

### Actual behavior

Most of the tests fail with errors like this one:
```
  1) VagrantPlugins::ProviderLibvirt::Action::DestroyDomain#call when no snapshots when only has root disk calls fog to destroy volumes
     Failure/Error: let(:iso_env)          { test_env.create_vagrant_env ui_class: Vagrant::UI::Basic }

     Vagrant::Errors::PluginInitError:
       The plugins failed to initialize correctly. This may be due to manual
       modifications made within the Vagrant home directory. Vagrant can
       attempt to automatically correct this issue by running:

         vagrant plugin repair

       If Vagrant was recently updated, this error may be due to incompatible
       versions of dependencies. To fix this problem please remove and re-install
       all plugins. Vagrant can attempt to do this automatically by running:

         vagrant plugin expunge --reinstall

       Or you may want to try updating the installed plugins to their latest
       versions:

         vagrant plugin update

       Error message given during initialization: undefined method `runtime_dependencies' for nil:NilClass
     # ./vendor/bundle/ruby/2.6.0/bundler/gems/vagrant-4ce8d84f7e67/lib/vagrant/plugin/manager.rb:108:in `rescue in bundler_init'
     # ./vendor/bundle/ruby/2.6.0/bundler/gems/vagrant-4ce8d84f7e67/lib/vagrant/plugin/manager.rb:101:in `bundler_init'
     # ./vendor/bundle/ruby/2.6.0/bundler/gems/vagrant-4ce8d84f7e67/lib/vagrant/plugin/manager.rb:69:in `localize!'
     # ./vendor/bundle/ruby/2.6.0/bundler/gems/vagrant-4ce8d84f7e67/lib/vagrant/environment.rb:169:in `initialize'
     # ./vendor/bundle/ruby/2.6.0/bundler/gems/vagrant-spec-abfc34474d12/lib/vagrant-spec/unit/isolated_environment.rb:22:in `new'
     # ./vendor/bundle/ruby/2.6.0/bundler/gems/vagrant-spec-abfc34474d12/lib/vagrant-spec/unit/isolated_environment.rb:22:in `create_vagrant_env'
     # ./spec/support/sharedcontext.rb:21:in `block (2 levels) in <top (required)>'
     # ./spec/support/sharedcontext.rb:22:in `block (2 levels) in <top (required)>'
     # ./spec/support/sharedcontext.rb:31:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `runtime_dependencies' for nil:NilClass
     #   ./vendor/bundle/ruby/2.6.0/bundler/gems/vagrant-4ce8d84f7e67/lib/vagrant/bundler.rb:425:in `vagrant_internal_specs'
```

### System configuration
**OS/Distro version:**: openSUSE Tumbleweed

**Libvirt version:** 5.4.0

**Output of `vagrant version; vagrant plugin list`:**
```
$ vagrant version
Installed Version: 2.2.5
Latest Version: 2.2.5
$ vagrant plugin list
vagrant-libvirt (0.0.45, system)
```

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
N/A

**A Vagrantfile to reproduce the issue:**
N/A

**Are you using upstream vagrant package or your distros package?**

I have tried both: the tests fail in the open build service which is using the vagrant RPM and also locally when the dependencies are installed via bundler.

**Comment by dcermak** [comment]
This issue is solved by https://github.com/hashicorp/vagrant/pull/10945.

**Comment by electrofelix** [comment]
Closing this issue, I do need to improve the development notes to help running tests if you already have the plugin installed.
