### ISSUE TITLE
aarch64 vagrant box with NVRAM enabled cannot be deleted by vagrant destroy

### ISSUE THREAD

**Issue by dcermak** [vagrant-libvirt/vagrant-libvirt#1027]
### Steps to reproduce
1. Grab a aarch64 vagrant box and apply the following settings:
``` ruby
    config.vm.provider :libvirt do |libvirt|
      libvirt.driver = 'kvm'
      libvirt.host = 'localhost'
      libvirt.uri = 'qemu:///system'
      libvirt.host = "master"
      libvirt.nvram = ""
      libvirt.loader = "/usr/share/qemu/aavmf-aarch64-code.bin"
      libvirt.video_type = "vga"
      libvirt.cpu_mode = "host-passthrough"
      libvirt.machine_type = "virt-3.1"
      libvirt.emulator_path = "/usr/bin/qemu-system-aarch64"
    end
```
2. vagrant up
3. vagrant destroy

### Expected behavior
The VM should get cleaned up.

### Actual behavior
I get a backtrace:
```
Removing domain...

/usr/lib64/ruby/gems/2.5.0/gems/fog-libvirt-0.6.0/lib/fog/libvirt/requests/compute/vm_action.rb:7:in `undefine': Call to virDomainUndefineFlags failed: Requested operation is not valid: cannot undefine domain with nvram (Libvirt::Error)

	from /usr/lib64/ruby/gems/2.5.0/gems/fog-libvirt-0.6.0/lib/fog/libvirt/requests/compute/vm_action.rb:7:in `vm_action'
	from /usr/lib64/ruby/gems/2.5.0/gems/fog-libvirt-0.6.0/lib/fog/libvirt/models/compute/server.rb:88:in `destroy'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/destroy_domain.rb:47:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/forward_ports.rb:197:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:121:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:121:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/machine.rb:238:in `action_raw'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/machine.rb:209:in `block in action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/environment.rb:615:in `lock'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/machine.rb:195:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/machine.rb:195:in `action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

```

### System configuration
**OS/Distro version:**: SUSE Linux Enterprise Server 15 SP1 on aarch64

**Libvirt version:** libvirt-5.1.0-8.6.1.aarch64

**Output of `vagrant version; vagrant plugin list`:** vagrant 2.2.4, vagrant-libvirt (0.0.45, system)

**A Vagrantfile to reproduce the issue:**
``` ruby
Vagrant.configure("2") do |config|

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 2048
  end

  if RbConfig::CONFIG["arch"].include? "aarch64"
    config.vm.provider :libvirt do |libvirt|
      libvirt.driver = 'kvm'
      libvirt.host = 'localhost'
      libvirt.uri = 'qemu:///system'
      libvirt.host = "master"
      libvirt.nvram = ""
      libvirt.storage_pool_name = 'default'
      libvirt.loader = "/usr/share/qemu/aavmf-aarch64-code.bin"
      libvirt.video_type = "vga"
      libvirt.cpu_mode = "host-passthrough"
      libvirt.machine_type = "virt-3.1"
      libvirt.emulator_path = "/usr/bin/qemu-system-aarch64"
    end
  end

  config.vm.hostname = "vm-test"

  config.vm.define "testing-Tumbleweed-arm" do |tw|
    tw.vm.box = "openSUSE-Tumbleweed-Vagrant.aarch64"
    tw.vm.box_url = "https://download.opensuse.org/repositories/Virtualization:/Appliances:/Images:/openSUSE-Tumbleweed/openSUSE_Tumbleweed_ARM/boxes/openSUSE-Tumbleweed-Vagrant.aarch64.json"
  end

end
```

**Are you using upstream vagrant package or your distros package?**
Distro

# Workaround

Manually remove the VM via:
``` shell
virsh undefine $domain_name --nvram --remove-all-storage
```

# Potential solution

If NVRAM is used by the domain, then the equivalent of `--nvram` must be passed to the libvirt call to undefine. Unfortunately I am not at all familiar with Ruby & fog to be able to submit a PR.

**Comment by trinitronx** [comment]
This seems like a duplicate of #1371 

There are 2 upstream fixes and 1 open pull request required before this will work:

- libvirt/libvirt-ruby@b0862ef - ([Merged!][1] We probably need to wait for the next gem release (`>= 0.8.0`)
- byonoy-dne/fog-libvirt@71e05e3 - PR: fog/fog-libvirt#102
- byonoy-dne/vagrant-libvirt@36b61e8 - PR: #1329 

If you cannot wait get this working, feel free to test out the [pre-release gems that I've built and posted here][2]

[1]: https://gitlab.com/libvirt/libvirt-ruby/-/merge_requests/1
[2]: https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1371#issuecomment-1014980135

**Comment by dcermak** [comment]
Thanks for the update @trinitronx! I have not run into this issue anymore, as I have simply removed the line with `libvirt.nvram = ""`. We can close this issue in favor of #1371, as I no longer have the environment where I encountered this issue available to me and wouldn't be able to test it.
