### ISSUE TITLE
Machine in pmsuspended state causes exception

### ISSUE THREAD

**Issue by p0xd1** [vagrant-libvirt/vagrant-libvirt#1048]
### Steps to reproduce
1. Create a VM on a KVM host, in my case this is a VM running Windows 10
2. Let it go into `pmsuspended` mode. 
```
$ virsh -c 'qemu+ssh://kvm06/system' list
 Id    Name                                State
--------------------------------------------------------
 164   pedro_desktop_windows01   pmsuspended
```
3. Run any vagrant command related to this VM, for example `vagrant status`

### Expected behaviour
This should work.

### Actual behaviour
```
$ vagrant status
/home/pedro/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/driver.rb:141:in `state': undefined method `to_sym' for nil:NilClass (NoMethodError)
        from /home/pedro/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/provider.rb:103:in `state'
        from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:529:in `state'
        from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:146:in `initialize'
        from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/vagrantfile.rb:81:in `new'
        from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/vagrantfile.rb:81:in `machine'
        from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:717:in `machine'
        from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/v2/command.rb:213:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/v2/command.rb:212:in `map'
        from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/v2/command.rb:212:in `with_target_vms'
        from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/commands/status/command.rb:20:in `execute'
        from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/cli.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:292:in `cli'
        from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:182:in `<main>'
```

### Possible workaround
Use `virsh dompmwakeup` to move the VM into running state. Vagrant commands now execute sucessfully.

### System configuration
**OS/Distro version:**:
Debian

**Libvirt version:**
5.0.0-4 

**Output of `vagrant version; vagrant plugin list`:**
```
$ vagrant plugin list                                                                                                                1 ↵
colorize (0.8.1, global)
net-ping (2.0.6, global)
netaddr (2.0.3, global)
vagrant-libvirt (0.0.45, global)

$ vagrant version
Installed Version: 2.2.4
```

**Are you using upstream vagrant package or your distros package?**
Upstream

I suspect this will also need a fix in the Fog library. Help identify where the bug is.

**Comment by electrofelix** [comment]
Partially debugged in #1200 so going to close this issue in favour of following up via that issue.
