### ISSUE TITLE
Installation error with vagrant 2.2.7

### ISSUE THREAD

**Issue by azmeuk** [vagrant-libvirt/vagrant-libvirt#1074]
### Steps to reproduce
1. Use a up-to-date archlinux with vagrant 2.2.7
2. `vagrant plugin install vagrant-libvirt`

### Expected behaviour
The plugin should install.

### Actual behaviour
The installation fails and display a stack trace.

### System configuration
**OS/Distro version:**: Archlinux

**Libvirt version:** 5.10.0

**Output of `vagrant version; vagrant plugin list`:** 
```
Installed Version: 2.2.7
Latest Version: 2.2.7
 
You're running an up-to-date version of Vagrant!
No plugins installed.
```

```
$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Traceback (most recent call last):
	16: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/bin/vagrant:182:in `<main>'
	15: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/environment.rb:290:in `cli'
	14: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/cli.rb:66:in `execute'
	13: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/plugins/commands/plugin/command/root.rb:66:in `execute'
	12: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/plugins/commands/plugin/command/install.rb:69:in `execute'
	11: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/plugins/commands/plugin/command/install.rb:69:in `each'
	10: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/plugins/commands/plugin/command/install.rb:70:in `block in execute'
	9: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/plugins/commands/plugin/command/base.rb:14:in `action'
	8: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `run'
	7: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/util/busy.rb:19:in `busy'
	6: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `block in run'
	5: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/action/builder.rb:116:in `call'
	4: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
	3: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	2: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
	1: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.7/plugins/commands/plugin/action/install_gem.rb:30:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.2.7/lib/vagrant/plugin/manager.rb:156:in `install_plugin': undefined method `name' for nil:NilClass (NoMethodError)
```

**A Vagrantfile to reproduce the issue:**
```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by electrofelix** [comment]
This looks more like an issue with Vagrant, can you confirm that you can install other plugins, as the error is coming from Vagrant itself without anything from vagrant-libvirt related

**Comment by electrofelix** [comment]
Seems this is a bug with distro vagrant when there is a vagrant-libvirt plugin installed with the distro, the simple solution is to remove the distro vagrant-libvirt and then install, sorry it took a while to work out.

Ideally this should be fixed by the distro.


After running the following:
```
sudo apt-get update
sudo apt install -y qemu libvirt-daemon-system libvirt-clients ebtables dnsmasq-base libguestfs-tools vagrant ruby-libvirt
```
Then running `vagrant plugin install vagrant-libvirt`, I see the following:
``` 
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
"https://rubygems.org/"]}}
Done installing documentation for  after 0 seconds
Traceback (most recent call last):
	18: from /usr/bin/vagrant:23:in `<main>'
	17: from /usr/bin/vagrant:23:in `load'
	16: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/bin/vagrant:177:in `<top (required)>'
	15: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/environment.rb:290:in `cli'
	14: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/cli.rb:66:in `execute'
	13: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/plugins/commands/plugin/command/root.rb:66:in `execute'
	12: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/plugins/commands/plugin/command/install.rb:69:in `execute'
	11: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/plugins/commands/plugin/command/install.rb:69:in `each'
	10: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/plugins/commands/plugin/command/install.rb:70:in `block in execute'
	 9: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/plugins/commands/plugin/command/base.rb:14:in `action'
	 8: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
	 7: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
	 6: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
	 5: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
	 4: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	 3: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
	 2: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
	 1: from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/plugins/commands/plugin/action/install_gem.rb:30:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/plugin/manager.rb:159:in `install_plugin': undefined method `name' for nil:NilClass (NoMethodError)
```

However if I then run:
```
sudo apt-get purge vagrant-libvirt
```
Followed by `vagrant plugin install vagrant-libvirt`, I see the following:
```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching vagrant-libvirt-0.9.0.gem
Parsing documentation for vagrant-libvirt-0.9.0
Installing ri documentation for vagrant-libvirt-0.9.0
Done installing documentation for vagrant-libvirt after 1 seconds
Installed the plugin 'vagrant-libvirt (0.9.0)'!
```

My guess is a suggested dependency pulled in vagrant-libvirt by accident and then that prevents you installing the latest version due to a bug with how it handles there being a default gem for vagrant-libvirt.

Based on this, going to close this now as being a distro issue with a workaround available.
