### ISSUE TITLE
vagrant up fails due to Libvirt::ConnectionError on Mac OS 

### ISSUE THREAD

**Issue by imperialguy** [vagrant-libvirt/vagrant-libvirt#1193]
### Steps to reproduce
1. Install `libvirt`, `qemu` using `homebrew` and `vagrant-libvirt` plugin using `vagrant plugin install` on mac.
2. Create a vagrant box or download one. Doesn't matter which OS. For e.g. try archlinux 
3. Run `vagrant up`

### Expected behaviour
It should bring up the box

### Actual behaviour
```
/Users/testuser/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.3.0/lib/vagrant-libvirt/driver.rb:59:in `open_read_only': Call to virConnectOpenReadOnly failed: Failed to connect socket to '/usr/local/var/run/libvirt/libvirt-sock-ro': No such file or directory (Libvirt::ConnectionError)
```

### System configuration
**OS/Distro version:**: Mac OS Big Sur v11.1

**Libvirt version:** libvirt 6.10.0

**Output of `vagrant version; vagrant plugin list`:** 
```
~ % vagrant version
Installed Version: 2.2.14
Latest Version: 2.2.14

You're running an up-to-date version of Vagrant!

~ % vagrant plugin list
vagrant-libvirt (0.3.0, global)
```

**Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`**
```
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/5755148/vagrant.log)
```

**A Vagrantfile to reproduce the issue:**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.vm.define "sample-01" do |config|
    config.vm.hostname = "sample-01"
    config.vm.box = "sample"
    config.vm.box_check_update = false
    config.vm.synced_folder ".", "/vagrant", disabled: true
    
    config.vm.provider :libvirt do |v|
      v.memory = 1024
      v.driver = "kvm"
      v.socket = "/Users/testuser/.cache/libvirt/libvirt-sock"
    end
  end
end
```

**Are you using upstream vagrant package or your distros package?**
installed via `homebrew`

**Comment by lukechilds** [comment]
I'm hitting the same issue, did you resolve this @imperialguy?

**Comment by alisson276** [comment]
I have set `libvirt.system_uri` and `libvirt.uri` and this error stopped. However, a new error starts to happen:
```
/Users/user/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/util/network_util.rb:144:in `list_networks': Call to virConnectNumOfNetworks failed: this function is not supported by the connection driver: virConnectNumOfNetworks (Libvirt::RetrieveError)
```

**Comment by alisson276** [comment]
I believe this issue is related to https://gitlab.com/libvirt/libvirt/-/issues/75
