### ISSUE TITLE
Error during install on Debian 10

### ISSUE THREAD

**Issue by kripskroll** [vagrant-libvirt/vagrant-libvirt#1216]
### Steps to reproduce

Installation can´t finisihed with error during compilation

### System configuration
**OS/Distro version:**: Debian 10

**Libvirt version:**
root@debian10:~# virsh version
Compiled against library: libvirt 5.0.0
Using library: libvirt 5.0.0
Using API: QEMU 5.0.0
Running hypervisor: QEMU 3.1.0

**Output of vagrant version; vagrant plugin list:** 
root@debian10:~ # vagrant version
Installed Version: 2.2.14
Latest Version: 2.2.14
root@debian10:~ # vagrant plugin list
vagrant-lxc (1.4.3, global)

**Output of `VAGRANT_LOG=debug vagrant plugin install vagrant-libvirt >vagrant.log 2>&1`**
```
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /root/.vagrant.d/gems/2.6.2/gems/racc-1.5.2/ext/racc/cparse
/tmp/.mount_vagranHLqh5I/usr/bin/ruby2.6 -I /tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0 -r ./siteconf20210308-13118-1oe3s6b.rb extconf.rb
checking for rb_ary_subseq()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/tmp/.mount_vagranHLqh5I/usr/bin/$(RUBY_BASE_NAME)2.6
/tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0/mkmf.rb:552:in `try_link0'
        from /tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0/mkmf.rb:570:in `try_link'
        from /tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0/mkmf.rb:782:in `try_func'
        from /tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0/mkmf.rb:1069:in `block in have_func'
        from /tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
        from /tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
        from /tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
        from /tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
        from /tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
        from /tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
        from /tmp/.mount_vagranHLqh5I/usr/lib/ruby/2.6.0/mkmf.rb:1068:in `have_func'
        from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /root/.vagrant.d/gems/2.6.2/extensions/x86_64-linux/2.6.0/racc-1.5.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /root/.vagrant.d/gems/2.6.2/gems/racc-1.5.2 for inspection.
Results logged to /root/.vagrant.d/gems/2.6.2/extensions/x86_64-linux/2.6.0/racc-1.5.2/gem_make.out
```

Here is output of  /root/.vagrant.d/gems/2.6.2/extensions/x86_64-linux/2.6.0/racc-1.5.2/mkmf.log
```
"gcc -o conftest -I/tmp/.mount_vagranHLqh5I/usr/include/x86_64-linux-gnu/ruby-2.6.0 -I/tmp/.mount_vagranHLqh5I/usr/include/ruby-2.6.0/ruby/backward -I/tmp/.mount_vagranHLqh5I/usr/include/ruby-2.6.0 -I. -D_FORTIFY_SOURCE=2   -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -fPIC conftest.c  -L. -L/tmp/.mount_vagranHLqh5I/usr/lib/x86_64-linux-gnu -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic     -lruby-2.6  -lm   -lc"
In file included from /tmp/.mount_vagranHLqh5I/usr/include/ruby-2.6.0/ruby/ruby.h:29,
                 from /tmp/.mount_vagranHLqh5I/usr/include/ruby-2.6.0/ruby.h:33,
                 from conftest.c:1:
/tmp/.mount_vagranHLqh5I/usr/include/ruby-2.6.0/ruby/defines.h:123:10: fatal error: stdio.h: Aucun fichier ou dossier de ce type
 #include <stdio.h>
          ^~~~~~~~~
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Are you using upstream vagrant package or your distros package?**
Upstream for Vagrant
Distro for libvirt

**Output of gcc to include stdio.h :**
root@debian10:~# gcc -x c -c -o/dev/null - <<<'#include <stdio.h>'
No error message

**Comment by electrofelix** [comment]
I'd expect GCC to be installed via the instructions for Debian 9 and higher in the main readme. Can you confirm that the following had been executed:
```
apt-get build-dep vagrant ruby-libvirt
apt-get install qemu libvirt-daemon-system libvirt-clients ebtables dnsmasq-base
apt-get install libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev
```

**Comment by Jeansen** [comment]
Works fine for me, on Debian Buster and even unstable (SID). I bet simply some packages are missing...

**Comment by electrofelix** [comment]
I've re-read the error message, and I believe the translation is saying that the file or folder cannot be found. However the last couple of lines show that a test program can be compiled that includes the stdio.h so it should be found on the system.

I suspect it might be a missing package just not an obvious one as GCC must be present and the standard includes must also be present.

I've tagged it with needinfo so that if the author can provide a bit more detail I can try and reproduce the issue, and if not, it'll automatically get closer 30 days after the last update.

**Comment by smutel** [comment]
I have the same issue. Any help or suggestion will be helpful.
