### ISSUE TITLE
[Question] Failed to connect socket to '/var/run/libvirt/libvirt-sock-ro': No such file or directory

### ISSUE THREAD

**Issue by pvalena** [vagrant-libvirt/vagrant-libvirt#1255]
```
Failed to connect socket to '/var/run/libvirt/libvirt-sock-ro': No such file or directory
```
Is libvirt intentionaly needed for tests to run? Is there some way to disable those tests? Can this be mocked instead?

_ _ _ _

### Steps to reproduce
1. Running the test suite during Fedora package build.

### Expected behaviour
Tests pass.

### Actual behaviour
```
DEBUG:   1) VagrantPlugins::ProviderLibvirt::Action::WaitTillUp#call when machine is booting multiple timeouts waiting for IP should abort after hitting limit
DEBUG:      Failure/Error: expect {subject.call(env) }.to raise_error(::Fog::Errors::TimeoutError)
DEBUG:        expected Fog::Errors::TimeoutError, got #<Libvirt::ConnectionError: Call to virConnectOpenReadOnly failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock-ro': No such file or directory> with backtrace:
DEBUG:          # ./lib/vagrant-libvirt/driver.rb:59:in `open_read_only'
DEBUG:          # ./lib/vagrant-libvirt/driver.rb:59:in `system_connection'
DEBUG:          # ./lib/vagrant-libvirt/driver.rb:137:in `get_ipaddress_from_system'
DEBUG:          # ./lib/vagrant-libvirt/driver.rb:97:in `get_domain_ipaddress'
DEBUG:          # ./lib/vagrant-libvirt/action/wait_till_up.rb:43:in `block (2 levels) in call'
DEBUG:          # /usr/share/vagrant/gems/gems/vagrant-2.2.14/lib/vagrant/util/retryable.rb:17:in `retryable'
DEBUG:          # ./lib/vagrant-libvirt/action/wait_till_up.rb:38:in `block in call'
DEBUG:          # ./lib/vagrant-libvirt/util/timer.rb:9:in `time'
DEBUG:          # ./lib/vagrant-libvirt/action/wait_till_up.rb:37:in `call'
DEBUG:          # ./spec/unit/action/wait_till_up_spec.rb:64:in `block (6 levels) in <top (required)>'
DEBUG:          # ./spec/unit/action/wait_till_up_spec.rb:64:in `block (5 levels) in <top (required)>'
DEBUG:          # /usr/share/gems/gems/bundler-2.2.15/libexec/bundle:49:in `block in <top (required)>'
DEBUG:          # /usr/share/gems/gems/bundler-2.2.15/libexec/bundle:37:in `<top (required)>'
DEBUG:      # ./spec/unit/action/wait_till_up_spec.rb:64:in `block (5 levels) in <top (required)>'
DEBUG:      # /usr/share/gems/gems/bundler-2.2.15/libexec/bundle:49:in `block in <top (required)>'
DEBUG:      # /usr/share/gems/gems/bundler-2.2.15/libexec/bundle:37:in `<top (required)>'

```

### System configuration
**OS/Distro version:**: Fedora

**Libvirt version:** -

**Output of `vagrant version; vagrant plugin list`:**
Vagrant 2.2.14
vagrant-libvirt 0.4.1

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by electrofelix** [comment]
Uncovered the problem, it appears the tests are picking up a local environment change that sets the connection to `qemu:///session` while the tests are expecting to the default to be `qemu:///system` and only some tests set it to `qemu:///session`.

I'll look to try and isolate the tests from picking this up accidentally.

**Comment by electrofelix** [comment]
@pvalena just happened to have a look at the SRPM for fedora, I suspect that vagrant-libvirt-0.0.45-enable-qemu-session-by-default.patch may also cause this problem because changing the behaviour of the code by default to `qemu:///session` but not necessarily adding the required mocks. Might want to rework that patch.
