### ISSUE TITLE
Updating vagrant-libvirt from 0.3 to 0.4.1 fails because new vrsion cannot be "activated"

### ISSUE THREAD

**Issue by zimmski** [vagrant-libvirt/vagrant-libvirt#1263]
### Steps to reproduce
1. Install a VM on openSUSE 15.2 with Vagrant 2.2.14 and vagrant-libvirt 0.3.0
2. Update the versions Vagrant to 2.2.16
3. Run `vagrant plugin expunge --local-only --force`
3. Update vagrant-libvirt to 0.4.1 using `vagrant plugin install --local`
3. See the following error

```
Installing the 'vagrant-libvirt --version '0.4.1'' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/specification.rb:2292:in `check_version_conflict': can't activate vagrant-libvirt-0.4.1, already activated vagrant-libvirt-0.3.0 (Gem::LoadError)
        from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/specification.rb:1414:in `activate'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:751:in `block in activate_solution'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:748:in `each'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:748:in `activate_solution'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:588:in `internal_install'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/bundler.rb:350:in `install'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/action/install_gem.rb:30:in `call'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/builder.rb:149:in `call'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `block in run'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/action/runner.rb:89:in `run'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/command/base.rb:14:in `action'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/command/install.rb:59:in `block in execute'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/command/install.rb:58:in `each'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/command/install.rb:58:in `execute'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/plugin/command/root.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/cli.rb:67:in `execute'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/environment.rb:290:in `cli'
        from /opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/bin/vagrant:231:in `<main>'
```

### Expected behaviour
Installation works like it did with 0.3.0

### Actual behaviour
Installation fails with `/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/specification.rb:2292:in `check_version_conflict': can't activate vagrant-libvirt-0.4.1, already activated vagrant-libvirt-0.3.0 (Gem::LoadError)`

### System configuration
OS: openSUSE 15.2

Compiled against library: libvirt 6.0.0
Using library: libvirt 6.0.0
Using API: QEMU 6.0.0
Running hypervisor: QEMU 4.2.1

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by electrofelix** [comment]
Essentially vagrant is saying that it won't install the newer plugin because it already is detecting 0.3.0 as being present and activated.

As far as I know there isn't anything any plugin can do here, as this is something to do with the plugin manager, unless vagrant has some expectation with the local install mechanism that I'm not a aware of.

I'm afraid you'll have to submit this issue to vagrant itself at https://github.com/hashicorp/vagrant

**Comment by zimmski** [comment]
@electrofelix thanks. Created an issue https://github.com/hashicorp/vagrant/issues/12345 with probably the MOST awesome issue IDs in a long time :-)

Will keep you posted.
