### ISSUE TITLE
Race in get_ip_address_from_domain if old network cleaned up

### ISSUE THREAD

**Issue by jamie01** [vagrant-libvirt/vagrant-libvirt#1438]
**Describe the bug**
There seems to be a race window in `driver.rb:205:in 'block in get_ipaddress_from_domain'` which I believe is actually most likely a race in the `fog-libvirt` code, so I am more than happy to raise the issue over there instead, but thought it warranted a set of eyes on it here first.

In the logs I've attached, we have a job scheduled by jenkins that is creating a new set of VMs. This is `jenkins_test_job-3690`
There is a failure in the creation phase on one of the nodes, with the below message

`Call to virNetworkLookupByName failed: Network not found: no network with matching name 'test_job-3689_node5net'`

This is referring to a network that was part of the previous job, jenkins build 3689
So what seems to be happening is during `get_ipaddress_from_domain` there is code that first gets a list of all networks, and then iteratively calls `lookup_network_by_name` on each one. Any time inside this loop, one of those networks could be destroyed by some other process, and this leads to the error seen.

That seems to be the race to me, I guess my next question is why do we need to lookup _all_ networks, rather than just the ones attached to the current domain? This would remove the need to iterate over potentially hundreds of unrelated networks, assuming a heavily loaded system.

**To Reproduce**
Somewhat difficult to reproduce reliably, but having a long list of libvirt networks and removing them while a new VM is created.

**Expected behavior**
Either don't look for unrelated networks.
Or allow the `lookup_network_by_name` call to fail on the assumption it was deleted. Again I realise this particular behaviour would need addressing in `fog-libvirt`

**Screenshots**

**Versions (please complete the following information):**:
- Libvirt version: 7.0.0-3
- Vagrant version [output of `vagrant version`]: 2.2.14
- Vagrant flavour [Upstream or Distro]:  debian11
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: vagrant-libvirt (0.7.0, global)

**Debug Log**
Non-debug log attached, which shows the issue clearly enough with the traceback. If there is a need for a debug log I will try and get one, it means enabling debug logging on all of our jobs given the race nature of the issue.
[libvirt_net_race.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/7899154/libvirt_net_race.txt)

The key part of the log is below
```
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error occurred when executing the action on the
'node2' machine. Please report this as a bug:

Call to virNetworkLookupByName failed: Network not found: no network with matching name 'test_job-3689_node5net'

/home/jenkins/.vagrant.d/gems/2.7.4/gems/fog-libvirt-0.9.0/lib/fog/libvirt/requests/compute/list_networks.rb:9:in `lookup_network_by_name'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/fog-libvirt-0.9.0/lib/fog/libvirt/requests/compute/list_networks.rb:9:in `block in list_networks'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/fog-libvirt-0.9.0/lib/fog/libvirt/requests/compute/list_networks.rb:8:in `each'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/fog-libvirt-0.9.0/lib/fog/libvirt/requests/compute/list_networks.rb:8:in `list_networks'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/fog-libvirt-0.9.0/lib/fog/libvirt/models/compute/networks.rb:11:in `all'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/fog-libvirt-0.9.0/lib/fog/libvirt/models/compute/server.rb:410:in `addresses_dhcp'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/driver.rb:205:in `block in get_ipaddress_from_domain'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/fog-core-2.2.4/lib/fog/core/model.rb:75:in `instance_eval'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/fog-core-2.2.4/lib/fog/core/model.rb:75:in `block in wait_for'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/fog-core-2.2.4/lib/fog/core/wait_for.rb:7:in `block in wait_for'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/fog-core-2.2.4/lib/fog/core/wait_for.rb:6:in `loop'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/fog-core-2.2.4/lib/fog/core/wait_for.rb:6:in `wait_for'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/fog-core-2.2.4/lib/fog/core/model.rb:72:in `wait_for'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/driver.rb:204:in `get_ipaddress_from_domain'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/driver.rb:113:in `get_domain_ipaddress'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/wait_till_up.rb:45:in `block (2 levels) in call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/util/retryable.rb:17:in `retryable'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/wait_till_up.rb:40:in `block in call'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/util/timer.rb:11:in `time'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/wait_till_up.rb:39:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/start_domain.rb:404:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/set_boot_order.rb:80:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_network_interfaces.rb:190:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_networks.rb:93:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/share_folders.rb:22:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:21:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/builtin/delayed.rb:19:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:14:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/builtin/provision.rb:80:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_domain.rb:443:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_domain_volume.rb:94:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/handle_box_image.rb:123:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/handle_storage_pool.rb:63:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/home/jenkins/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/builtin/box_check_outdated.rb:31:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/machine.rb:246:in `action_raw'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/machine.rb:215:in `block in action'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/environment.rb:613:in `lock'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `call'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `action'
/usr/share/rubygems-integration/all/gems/vagrant-2.2.14/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```

**A Vagrantfile to reproduce the issue:**
```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Comment by electrofelix** [comment]
It does look like the code at https://github.com/fog/fog-libvirt/blob/35d2cb441fdddabbbfe9209543ff74ce1f948128/lib/fog/libvirt/models/compute/server.rb#L410-L417 could be improved to replace the all call with a series of calls that use filters to limit the networks searched to those only attached to the domain as you suggest.

I think that the block:
```
            service.networks.all.each do |net|
              if net.name == nic.network
                leases = net.dhcp_leases(mac, 0)
                # Assume the lease expiring last is the current IP address
                ip_address = leases.sort_by { |lse| lse["expirytime"] }.last["ipaddr"] if !leases.empty?
                break
              end
            end
```

Could be rewritten as:
```
            service.networks.all({:name => nic.network}}.each do |net|
              leases = net.dhcp_leases(mac, 0)
              # Assume the lease expiring last is the current IP address
              ip_address = leases.sort_by { |lse| lse["expirytime"] }.last["ipaddr"] if !leases.empty?
              break
            end
```
Since the nested if statement is filtering out by name anyway. Which would help reduce the number of network lookups as well.

**Comment by jamie01** [comment]
I never thanked you for getting that fix into fog-libvirt, better late than never! I was reminded of this ticket as I opened https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1815

I believe your changes addressed the case I had in this ticket, and my PR will cover what then became the most common point of failure in our synchronous deploy/destroy events. So I think this ticket can be closed.

By the way in case you're interested, log files suggest one of our execution hosts had launched over 218k VMs since last power on, all through this plugin. Thanks for keeping it active and investing so much time into it
