### ISSUE TITLE
using qemu/edk2-x86_64-code.fd uefi firmware

### ISSUE THREAD

**Issue by eoli3n** [vagrant-libvirt/vagrant-libvirt#1443]
**Describe the bug**
I want to be able to use qemu edk2 efi firmware.

**To Reproduce**
```ruby
Vagrant.configure("2") do |config|
  config.vm.define :voidlinux do |voidlinux|
    voidlinux.vm.hostname = "voidlinux"
    voidlinux.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'
      libvirt.memory = '2048'
      libvirt.cpus = '1'
      # Create a disk
      libvirt.storage :file,
        size: '50G',
        type: 'qcow2',
        bus: 'sata',
        device: 'sda'
      # Set fr keyboard for vnc connection
      libvirt.keymap = 'fr'
      libvirt.boot 'cdrom'
      libvirt.boot 'hd'
      libvirt.storage :file, :device => :cdrom, :path => '/tmp/hrmpf.iso'
      libvirt.loader '/usr/share/qemu/edk2-x86_64-code.fd'
    end
  end
end
~
```
**Expected behavior**
Booting well

**Versions (please complete the following information):**:
- Libvirt version: 8.0.0
- Vagrant version [output of `vagrant version`]: 2.2.19
- Vagrant flavour [Upstream or Distro]: latest Void Linux
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: vagrant-libvirt (0.7.0, global)

**A Vagrantfile to reproduce the issue:**
See https://github.com/eoli3n/void-config/blob/master/scripts/virt/Vagrantfile

```bash
Bringing machine 'voidlinux' up with 'libvirt' provider...
==> voidlinux: Running action triggers before up ...
==> voidlinux: Running trigger...
    voidlinux: Running local: Inline script
    voidlinux: ./download_iso.sh start
==> voidlinux: Creating domain with the following settings...
==> voidlinux:  -- Name:              virt_voidlinux
==> voidlinux:  -- Description:       Source: /home/user/dev/void-config/scripts/virt/Vagrantfile
==> voidlinux:  -- Domain type:       kvm
==> voidlinux:  -- Cpus:              1
==> voidlinux:  -- Feature:           acpi
==> voidlinux:  -- Feature:           apic
==> voidlinux:  -- Feature:           pae
==> voidlinux:  -- Clock offset:      utc
==> voidlinux:  -- Memory:            2048M
==> voidlinux:  -- Management MAC:    
==> voidlinux:  -- Loader:            /usr/share/qemu/edk2-x86_64-code.fd
==> voidlinux:  -- Nvram:             
==> voidlinux:  -- Storage pool:      default
==> voidlinux:  -- Disk driver opts:  cache='default'
==> voidlinux:  -- Kernel:            
==> voidlinux:  -- Initrd:            
==> voidlinux:  -- Graphics Type:     vnc
==> voidlinux:  -- Graphics Port:     -1
==> voidlinux:  -- Graphics IP:       127.0.0.1
==> voidlinux:  -- Graphics Password: Not defined
==> voidlinux:  -- Video Type:        cirrus
==> voidlinux:  -- Video VRAM:        9216
==> voidlinux:  -- Video 3D accel:    false
==> voidlinux:  -- Sound Type:	
==> voidlinux:  -- Keymap:            fr
==> voidlinux:  -- TPM Backend:       passthrough
==> voidlinux:  -- TPM Path:          
==> voidlinux:  -- Boot device:        cdrom
==> voidlinux:  -- Boot device:        hd
==> voidlinux:  -- Disks:         sda(qcow2,50G)
==> voidlinux:  -- Disk(sda):     /var/lib/libvirt/images/virt_voidlinux-sda.qcow2
==> voidlinux:  -- CDROMS:            hda
==> voidlinux:  -- CDROM(hda):        /tmp/hrmpf.iso
==> voidlinux:  -- INPUT:             type=mouse, bus=ps2
==> voidlinux: Starting domain.
/home/user/.vagrant.d/gems/3.0.3/gems/fog-libvirt-0.9.0/lib/fog/libvirt/requests/compute/vm_action.rb:7:in `create': Call to virDomainCreateWithFlags failed: internal error: qemu unexpectedly closed the monitor: qemu: could not load PC BIOS '/usr/share/qemu/edk2-x86_64-code.fd' (Libvirt::Error)
```

It seems that with ``edk2-x86_64-code.fd``, ``-bios`` is not working : 
- https://www.reddit.com/r/qemu_kvm/comments/k6ndha/bios_not_working/
- https://www.reddit.com/r/virtualization/comments/ifmmnh/qemu_options_for_booting_efi/

I tried with
```ruby
libvirt.storage :file, :device => :pflash, :type => 'raw', :path => '/usr/share/qemu/edk2-x86_64-code.fd'
```
But it doesn't work too.

Any idea ?

**Comment by eoli3n** [comment]
Following https://github.com/vagrant-libvirt/vagrant-libvirt/pull/869 , tried to set ``loader`` and ``nvram`` without more success.
```ruby
      libvirt.loader = '/usr/share/qemu/edk2-x86_64-code.fd'
      libvirt.nvram = '/var/lib/libvirt/qemu/nvram/vagrant.fd'
```

```
==> voidlinux: Starting domain.
/home/user/.vagrant.d/gems/3.0.3/gems/fog-libvirt-0.9.0/lib/fog/libvirt/requests/compute/vm_action.rb:7:in `create': Call to virDomainCreateWithFlags failed: internal error: qemu unexpectedly closed the monitor: qemu: could not load PC BIOS '/usr/share/qemu/edk2-x86_64-code.fd' (Libvirt::Error)
```

**Comment by eoli3n** [comment]
When I use the ``--uefi`` switch to qemu it points to ``/usr/share/qemu/edk2-x86_64-secure-code.fd``.

```ruby
      libvirt.loader = '/usr/share/qemu/edk2-x86_64-secure-code.fd'
      libvirt.nvram = '/var/lib/libvirt/qemu/nvram/voidlinux-vagrant.fd'
```

It seems better, but then I get a problem with nvram which is not created automatically.

```
 Call to virDomainCreateWithFlags failed: operation failed: unable to find any master var store for loader: /usr/share/qemu/edk2-x86_64-secure-code.fd (Libvirt::Error)
```

**Comment by eoli3n** [comment]
When I run a plain qemu command to create a host with ``--uefi``, a new nvram file is created in ``/var/lib/libvirt/qemu/nvram``.

See https://github.com/eoli3n/void-config/blob/master/scripts/virt/00-create.sh#L73-L91
It procudes
```bash
$ root@osz ~# ps aux | grep qemu
libvirt  19403  100  0.8 2896956 144824 ?      Sl   09:02  47:27 /usr/bin/qemu-system-x86_64 -name guest=void-linux-hrmpf,debug-threads=on -S -object {"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/lib/libvirt/qemu/domain-34-void-linux-hrmpf/master-key.aes"} -blockdev {"driver":"file","filename":"/usr/share/qemu/edk2-x86_64-secure-code.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash0-format","read-only":true,"driver":"raw","file":"libvirt-pflash0-storage"} -blockdev {"driver":"file","filename":"/var/lib/libvirt/qemu/nvram/void-linux-hrmpf_VARS.fd","node-name":"libvirt-pflash1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash1-format","read-only":false,"driver":"raw","file":"libvirt-pflash1-storage"} -machine pc-q35-6.1,usb=off,vmport=off,smm=on,dump-guest-core=off,pflash0=libvirt-pflash0-format,pflash1=libvirt-pflash1-format,memory-backend=pc.ram -accel kvm -cpu Cooperlake,ss=on,vmx=on,pdcm=on,hypervisor=on,tsc-adjust=on,avx512ifma=on,sha-ni=on,avx512vbmi=on,umip=on,avx512vbmi2=on,gfni=on,vaes=on,vpclmulqdq=on,avx512bitalg=on,avx512-vpopcntdq=on,rdpid=on,movdiri=on,movdir64b=on,fsrm=on,md-clear=on,xsaves=on,ibpb=on,ibrs=on,amd-stibp=on,amd-ssbd=on,hle=off,rtm=off,avx-vnni=off,avx512-bf16=off,taa-no=off -m 2048 -object {"qom-type":"memory-backend-ram","id":"pc.ram","size":2147483648} -overcommit mem-lock=off -smp 2,sockets=2,cores=1,threads=1 -uuid 1488b471-65dd-480e-b8a8-6b349c7e2ca5 -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=30,server=on,wait=off -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -global ICH9-LPC.disable_s3=1 -global ICH9-LPC.disable_s4=1 -boot strict=on -device pcie-root-port,port=16,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2 -device pcie-root-port,port=17,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1 -device pcie-root-port,port=18,chassis=3,id=pci.3,bus=pcie.0,addr=0x2.0x2 -device pcie-root-port,port=19,chassis=4,id=pci.4,bus=pcie.0,addr=0x2.0x3 -device pcie-root-port,port=20,chassis=5,id=pci.5,bus=pcie.0,addr=0x2.0x4 -device pcie-root-port,port=21,chassis=6,id=pci.6,bus=pcie.0,addr=0x2.0x5 -device qemu-xhci,p2=15,p3=15,id=usb,bus=pci.2,addr=0x0 -device virtio-serial-pci,id=virtio-serial0,bus=pci.3,addr=0x0 -blockdev {"driver":"file","filename":"/var/lib/libvirt/images/void-linux-hrmpf.img","node-name":"libvirt-2-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":false,"driver":"qcow2","file":"libvirt-2-storage","backing":null} -device ide-hd,bus=ide.0,drive=libvirt-2-format,id=sata0-0-0,bootindex=2 -blockdev {"driver":"file","filename":"/var/lib/libvirt/isos/hrmpf-x86_64-5.15.11_1-20211227.iso","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":true,"driver":"raw","file":"libvirt-1-storage"} -device ide-cd,bus=ide.1,drive=libvirt-1-format,id=sata0-0-1,bootindex=1 -netdev tap,fd=31,id=hostnet0,vhost=on,vhostfd=33 -device virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:43:f4:1c,bus=pci.1,addr=0x0 -chardev pty,id=charserial0 -device isa-serial,chardev=charserial0,id=serial0 -chardev spicevmc,id=charchannel0,name=vdagent -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=com.redhat.spice.0 -device usb-tablet,id=input0,bus=usb.0,port=1 -audiodev {"id":"audio1","driver":"spice"} -spice port=5900,addr=127.0.0.1,disable-ticketing=on,image-compression=off,seamless-migration=on -device qxl-vga,id=video0,ram_size=67108864,vram_size=67108864,vram64_size_mb=0,vgamem_mb=16,max_outputs=1,bus=pcie.0,addr=0x1 -device ich9-intel-hda,id=sound0,bus=pcie.0,addr=0x1b -device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0,audiodev=audio1 -chardev spicevmc,id=charredir0,name=usbredir -device usb-redir,chardev=charredir0,id=redir0,bus=usb.0,port=2 -chardev spicevmc,id=charredir1,name=usbredir -device usb-redir,chardev=charredir1,id=redir1,bus=usb.0,port=3 -device virtio-balloon-pci,id=balloon0,bus=pci.4,addr=0x0 -object {"qom-type":"rng-random","id":"objrng0","filename":"/dev/urandom"} -device virtio-rng-pci,rng=objrng0,id=rng0,bus=pci.5,addr=0x0 -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
```

**Comment by eoli3n** [comment]
Virt-install uses the template file ``/usr/share/qemu/firmware/50-edk2-x86_64-secure.json`` to template the nvram.

```
{
    "description": "UEFI firmware for x86_64, with Secure Boot and SMM",
    "interface-types": [
        "uefi"
    ],
    "mapping": {
        "device": "flash",
        "executable": {
            "filename": "/usr/share/qemu/edk2-x86_64-secure-code.fd",
            "format": "raw"
        },
        "nvram-template": {
            "filename": "/usr/share/qemu/edk2-i386-vars.fd",
            "format": "raw"
        }
    },
    "targets": [
        {
            "architecture": "x86_64",
            "machines": [
                "pc-q35-*"
            ]
        }
    ],
    "features": [
        "acpi-s3",
        "amd-sev",
        "requires-smm",
        "secure-boot",
        "verbose-dynamic"
    ],
    "tags": [

    ]
}
```

If I get it well, using ``libvirt.nvram = '/var/lib/libvirt/qemu/nvram/voidlinux-vagrant.fd'`` should template ``/usr/share/qemu/edk2-i386-vars.fd`` to create ``/var/lib/libvirt/qemu/nvram/voidlinux-vagrant.fd``.

**Comment by eoli3n** [comment]
Tried to template it manually
```bash
$ sudo cp /usr/share/qemu/edk2-i386-vars.fd /var/lib/libvirt/qemu/nvram/voidlinux-vagrant.fd
$ vagrant up
Bringing machine 'voidlinux' up with 'libvirt' provider...
==> voidlinux: Running action triggers before up ...
==> voidlinux: Running trigger...
    voidlinux: Running local: Inline script
    voidlinux: ./download_iso.sh start
==> voidlinux: Starting domain.
/home/user/.vagrant.d/gems/3.0.3/gems/fog-libvirt-0.9.0/lib/fog/libvirt/requests/compute/vm_action.rb:7:in `create': Call to virDomainCreateWithFlags failed: operation failed: unable to find any master var store for loader: /usr/share/qemu/edk2-x86_64-secure-code.fd (Libvirt::Error)
```
I'm missing something

**Comment by electrofelix** [comment]
@eoli3n if you use `VAGRANT_LOG=debug vagrant up 2>&1 | tee vagrant.log` the last release of vagrant-libvirt should display the XML sent to libvirt to create as well as the XML it is started with, and can then use those to compare against the virt-install output. Might help narrow down what it should look like.

I don't see any nvram referenced in the virt-install generated XML, just the loader.

**Comment by eoli3n** [comment]
It seems that virt-install uses its own firmware detection which could be used by vagrant-libvirt.
See https://libvirt.org/formatdomain.html#bios-bootloader ``<!-- QEMU with automatic UEFI firmware and secure boot -->``

Let's dump vagrant xml

**Comment by eoli3n** [comment]
First of all ``/usr/share/qemu/edk2-x86_64-secure-code.fd`` is for secure boot.
Defaultly vagrant-libvirt creates a host with ``i440FX`` chipset which does not support secure boot.
The ``50-edk2-x86_64-secure.json`` file doesn't match that chipset.

```json
[...]
    "targets": [
        {
            "architecture": "x86_64",
            "machines": [
                "pc-q35-*"
            ]
        }
[...]
```

The file ``60-edk2-x86_64.json`` does match ``i440FX``. Let's first use debug that one. Then try to find vagrant-libvirt way to set chipset.

**Comment by eoli3n** [comment]
Ok that was my issue.
```
      libvirt.loader = '/usr/share/qemu/edk2-x86_64-code.fd'
      libvirt.nvram = '/var/lib/libvirt/qemu/nvram/voidlinux-vagrant.fd'
```
This is working, except that ``vagrant destroy`` fails to remove the nvram file.

**Comment by eoli3n** [comment]
Now let's search for the way to force ``Q35`` chipset.

**Comment by eoli3n** [comment]
```
```

**Comment by eoli3n** [comment]
Ok, so I switch the disk to scsi bus and the cdrom to sata (both on sata gave a conflict).
Here the final working Vagrantfile : https://github.com/eoli3n/void-config/blob/master/vagrant/Vagrantfile

**Comment by electrofelix** [comment]
Do you need to switch the storage device? Looks like it defaulted to sata, was only the cdrom that looked to be ide.

**Comment by eoli3n** [comment]
I don't get what you meant ?

**Comment by electrofelix** [comment]
In the debug output the XML for the storage device was as follows:

```
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/var/lib/libvirt/images/virt_voidlinux-sda.qcow2'/>
      <target dev='sda' bus='sata'/>
      <boot order='2'/>
      <alias name='ua-disk-volume-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
```

Which is using SATA rather than IDE, so I was wondering do you really need to set the storage bus to SCSI? As it looks like the default should work.

It's only the cdrom block that is using IDE
```
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='/tmp/hrmpf.iso'/>
      <target dev='hda' bus='ide'/>
      <readonly/>
      <boot order='1'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
```

**Comment by electrofelix** [comment]
> I firstly set cdrom to sata, but it gave a conflict error that I didn't want to debug more. So I changed the disk to scsi to avoid the conflict.

Ah, thanks I missed the both on SATA gave a conflict. Bug in device auto assignment. The code tried to have both use sda instead of allocating the next available based on bus usage.

I'll have to have another look as that should be a relatively straightforward fix. Not sure how straight forward it would be to have the uefi loader and nvram work with a simpler option, but the former should definitely be fixed.

**Comment by eoli3n** [comment]
Lets create a dedicated issue

**Comment by eoli3n** [comment]
https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1444
