### ISSUE TITLE
[OS X] `Vagrant failed to properly resolve required dependencies. ` for vagrant plugin install vagrant-libvirt

### ISSUE THREAD

**Issue by iapicca** [vagrant-libvirt/vagrant-libvirt#1461]
following the steps described [here](https://lunar.computer/posts/vagrant-libvirt-macos/)
I'm encountering the error below when running `vagrant plugin install vagrant-libvirt`

<details>
  <summary>steps</summary>
  
 1. install homebrew

    ```bash
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    ```

2. install qemu

    ```bash
    brew install qemu
    ```
3. install vagrant

    ```bash
    brew install --cask vagrant && \
    brew install libiconv gcc libvirt
    ```

4. update path 

    ```bash
    echo 'export PATH="/usr/local/opt/libiconv/bin:$PATH"' >> ~/.zshrc  && \
    echo 'export LDFLAGS="-L/usr/local/opt/libiconv/lib"' >> ~/.zshrc && \
    echo 'export CPPFLAGS="-I/usr/local/opt/libiconv/include"' >> ~/.zshrc && \
    echo 'export VAGRANT_DEFAULT_PROVIDER=kvm' >> ~/.zshrc
    ```

5. install vagrant-libvirt

    - find out `ruby version` 

    ```bash
    ➜  ~ /opt/vagrant/embedded/bin/ruby --version
    
    ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin19]
    ```

    - vagrant plugin install vagrant-libvirt 

    ```bash
    CONFIGURE_ARGS='with-ldflags=-L/opt/vagrant/embedded/lib with-libvirt-include=/usr/local/include/libvirt with-libvirt-lib=/usr/local/lib' \
    GEM_HOME=~/.vagrant.d/gems/2.7.4p191 \
    GEM_PATH=$GEM_HOME:/opt/vagrant/embedded/gems \
    PATH=/opt/vagrant/embedded/bin:$PATH \
    vagrant plugin install vagrant-libvirt
    ```
    
    note: replacing `GEM_HOME=~/.vagrant.d/gems/2.7.4p191 \` with `GEM_HOME=~/.vagrant.d/gems/2.7.4 \`
    outputs the same result 

</details>

<details>
  <summary>error</summary>

```console
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /Users/francesco/.vagrant.d/gems/2.7.4/gems/ruby-libvirt-0.8.0/ext/libvirt
/opt/vagrant/embedded/bin/ruby -I /opt/vagrant/embedded/lib/ruby/2.7.0 -r ./siteconf20220306-10299-t8kkrg.rb extconf.rb
Looking for libvirt in /usr/local/include/libvirt and /usr/local/lib
checking for virConnectOpen() in -lvirt... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
	--with-libvirt-include
	--with-libvirt-lib
	--with-virt-dir
	--without-virt-dir
	--with-virt-include
	--without-virt-include=${virt-dir}/include
	--with-virt-lib
	--without-virt-lib=${virt-dir}/lib
	--with-virtlib
	--without-virtlib
extconf.rb:44:in `<main>': No working libvirt installation found (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/francesco/.vagrant.d/gems/2.7.4/extensions/x86_64-darwin-19/2.7.0/ruby-libvirt-0.8.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/francesco/.vagrant.d/gems/2.7.4/gems/ruby-libvirt-0.8.0 for inspection.
Results logged to /Users/francesco/.vagrant.d/gems/2.7.4/extensions/x86_64-darwin-19/2.7.0/ruby-libvirt-0.8.0/gem_make.out
```

</details>

<details>
  <summary>info</summary>

```console
➜  ~ neofetch
                    'c.          francesco@Francescos-MacBook-Pro.local
                 ,xNMM.          --------------------------------------
               .OMMMMo           OS: macOS 12.2.1 21D62 x86_64
               OMMM0,            Host: MacBookPro15,1
     .;loddo:' loolloddol;.      Kernel: 21.3.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 5 hours, 32 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 70 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1680x1050
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Amethyst
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    Terminal: iTerm2
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal Font: Monaco 12
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Intel i7-9750H (12) @ 2.60GHz
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Intel UHD Graphics 630, Radeon Pro 555X
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 9933MiB / 16384MiB
       .cooc,.    .,coo:.

```
```console
➜  ~ vagrant --version
Vagrant 2.2.19
```

</details>

## alterenatively: is there an easier way to use vagrant & qemu on OSX?

related issues:

https://github.com/vagrant-libvirt/vagrant-libvirt/issues/497
https://github.com/vagrant-libvirt/vagrant-libvirt/issues/818
https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1017

mirror:
https://github.com/iapicca/dart_server_container/issues/1
[stackoverflow](https://stackoverflow.com/questions/71371218/error-installing-vagrant-libvirt-plugin-on-osx)

**Comment by electrofelix** [comment]
I would skip setting `GEM_HOME` and `GEM_PATH` as these would likely interfere with vagrant trying to set them up itself.

Can you attach the file  /Users/francesco/.vagrant.d/gems/2.7.4/extensions/x86_64-darwin-19/2.7.0/ruby-libvirt-0.8.0/mkmf.log as that should contain more details on the build error. I suspect that there is some issue with picking up the libvirt libraries.

Checking through the various issues linked 
https://github.com/vagrant-libvirt/vagrant-libvirt/issues/497#issuecomment-597564837 seems the best way of passing through the paths for the configure env var.

**Comment by iapicca** [comment]
@electrofelix 
first of all, thanks for your answer

removing 

```
GEM_HOME=~/.vagrant.d/gems/2.7.4p191 \
GEM_PATH=$GEM_HOME:/opt/vagrant/embedded/gems \
```
outputs this:
[libvirt.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/8238147/libvirt.log)

```console
➜  ~ CONFIGURE_ARGS='with-ldflags=-L/opt/vagrant/embedded/lib with-libvirt-include=/usr/local/include/libvirt with-libvirt-lib=/usr/local/lib' \
PATH=/opt/vagrant/embedded/bin:$PATH \
vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching formatador-1.1.0.gem
Fetching fog-core-2.3.0.gem
Building native extensions. This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /Users/francesco/.vagrant.d/gems/2.7.4/gems/ruby-libvirt-0.8.0/ext/libvirt
/opt/vagrant/embedded/bin/ruby -I /opt/vagrant/embedded/lib/ruby/2.7.0 -r ./siteconf20220312-10570-1hq8z35.rb extconf.rb
Looking for libvirt in /usr/local/include/libvirt and /usr/local/lib
checking for virConnectOpen() in -lvirt... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
	--with-libvirt-include
	--with-libvirt-lib
	--with-virt-dir
	--without-virt-dir
	--with-virt-include
	--without-virt-include=${virt-dir}/include
	--with-virt-lib
	--without-virt-lib=${virt-dir}/lib
	--with-virtlib
	--without-virtlib
extconf.rb:44:in `<main>': No working libvirt installation found (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/francesco/.vagrant.d/gems/2.7.4/extensions/x86_64-darwin-19/2.7.0/ruby-libvirt-0.8.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/francesco/.vagrant.d/gems/2.7.4/gems/ruby-libvirt-0.8.0 for inspection.
Results logged to /Users/francesco/.vagrant.d/gems/2.7.4/extensions/x86_64-darwin-19/2.7.0/ruby-libvirt-0.8.0/gem_make.out
```

I'm attaching the logs

**Comment by electrofelix** [comment]
The build output indicates that `with-libvirt-include=/usr/local/include/libvirt` is the problem.

I'd guess that using
```
export CONFIGURE_ARGS="with-ldflags=-L/opt/vagrant/embedded/lib with-libvirt-lib=$(brew --prefix libvirt)/lib with-libvirt-include=$(brew --prefix libvirt)/include"
```
Should do the right thing, and result in `with-libvirt-include=/use/local/include` instead of

**Comment by iapicca** [comment]
@electrofelix 
it worked like a charm! thank you very much...
please if you feel to do so, you may collect your bounty on stackoverflow :)
https://stackoverflow.com/questions/71371218/error-installing-vagrant-libvirt-plugin-on-osx
