### ISSUE TITLE
Destroy fails: cannot load such file -- rexml

### ISSUE THREAD

**Issue by abbbi** [vagrant-libvirt/vagrant-libvirt#1483]
Destroying a multi machine environment fails after update to the latest release:
```
vagrant destroy  -f

Traceback (most recent call last):
        28: from /opt/vagrant/embedded/gems/2.2.15/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
        27: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
        26: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:201:in `action'
        25: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:201:in `call'
        24: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/environment.rb:614:in `lock'
        23: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:215:in `block in action'
        22: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/machine.rb:246:in `action_raw'
        21: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
        20: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
        19: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
        18: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
        17: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
        16: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        15: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
        14: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:53:in `call'
        13: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `run'
        12: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/util/busy.rb:19:in `busy'
        11: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/runner.rb:89:in `block in run'
        10: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builder.rb:149:in `call'
         9: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
         8: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
         7: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/warden.rb:48:in `call'
         6: from /opt/vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/lib/vagrant/action/builtin/call.rb:47:in `call'
         5: from /home/buildtest/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.8.1/lib/vagrant-libvirt/action.rb:262:in `block (3 levels) in action_destroy'
         4: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         3: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         2: from /home/buildtest/.vagrant.d/gems/2.6.6/gems/vagrant-libvirt-0.8.1/lib/vagrant-libvirt/action/destroy_domain.rb:4:in `<top (required)>'
         1: from /opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/vagrant/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rexml (LoadError)

```

one of the vms in the multi machine config is not yet up (which doesnt seem to matter, it also fails after i bring up this
machine)

```
Current machine states:

cli-linux                 running (libvirt)
cli-windows               running (libvirt)
cli-windows2              running (libvirt)
cli-rds-linux             running (libvirt)
srv                       not created (libvirt)
```

i tink this is a regression in the latest release, as it worked before.

**Comment by abbbi** [comment]
works after downgrading to the last version.

**Comment by electrofelix** [comment]
rexml should be part of the stdlib for ruby 2.6 https://ruby-doc.org/stdlib-2.6/libdoc/rexml/rdoc/index.html

I have to wonder if the latest release is exposing a bug in vagrant 2.2.15 that would be solved by updating vagrant itself?

**Comment by electrofelix** [comment]
I was pretty sure vagrant itself uses rexml, so even if they stripped down the embedded ruby, not sure how it's missing and vagrant itself is working.

**Comment by abbbi** [comment]
Appears to work after updating vagrant to 2.2.15, strange.

**Comment by electrofelix** [comment]
Looks like for older rexml the correct loading procedure is to require 'rexml/rexml'

So use of the following fixes it.
```
begin
  require 'rexml'
rescue LoadError
  require 'rexml/rexml'
end
```
