### ISSUE TITLE
No box and PXE boot example from documentation fails

### ISSUE THREAD

**Issue by mikfire** [vagrant-libvirt/vagrant-libvirt#1508]
**Describe the bug**
I am attempting to PXE boot a VM with no defined box, as described [in the docs](https://www.rubydoc.info/gems/vagrant-libvirt#no-box-and-pxe-boot).

`vagrant up pxeboot` fails with
```
resolve_disk_settings.rb:101:in `lookup_domain_by_uuid': no implicit conversion of nil into String (TypeError)
```
I believe this is a side effect of PR #1502. It looks like there is an assumption that if the config.vm.box isn't set, then the ID will be. In the PXE case, both the box and the ID are nil which is causing line 101 to throw the error. If I comment out lines 101 - 106, the machine comes up as expected. I am uncertain if that is a good idea or not.

**To Reproduce**
1. Install vagrant 2.2.19
2. say `vagrant plugin install vagrant-libvirt`
3. Verify vagrant-libvirt v 0.9.0 is installed
4. Say vagrant up pxeclient

**Expected behavior**
The expected behavior is that the client machine will start, recognize its network and PXE boot, as it did in v0.7.0.

**Versions (please complete the following information):**:
- Libvirt version: 0.9.0
- Vagrant version: `Installed Version: 2.2.19`
- Vagrant flavour: gentoo
- Vagrant plugins versions (including vagrant-libvirt):
```
pkg-config (1.4.7, global)
  - Version Constraint: > 0
vagrant-libvirt (0.9.0, global)
```

**Debug Log**
I would, but github keeps throwing errors when I try. The full error message is:

```
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00007f8c904e9db8>
/home/****/.vagrant.d/gems/2.7.6/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/resolve_disk_settings.rb:101:in `lookup_domain_by_uuid': no implicit conversion of nil into String (TypeError)
	from /home/****/.vagrant.d/gems/2.7.6/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/resolve_disk_settings.rb:101:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /home/****/.vagrant.d/gems/2.7.6/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /home/****/.vagrant.d/gems/2.7.6/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/cleanup_on_failure.rb:21:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_check_outdated.rb:31:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'
	from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.19/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```

**A Vagrantfile to reproduce the issue:**

This does assume you have a PXE server available. This is also mostly a copy/paste from the documentation.
```
Vagrant.configure("2") do |config|

  config.vm.define :pxeboot, autostart: false do |node|
    node.vm.provider :libvirt do |libvirt|
      libvirt.memory = 8192
      libvirt.boot 'hd'
      libvirt.boot 'network'
      libvirt.storage :file, :size => '20G', :type => 'qcow2'
      libvirt.mgmt_attach = false
    end
  end
end

```

**Comment by electrofelix** [comment]
Thanks, I knew I should have put together some kind of test for this scenario

**Comment by electrofelix** [comment]
At a quick guess I think wrapping the lines you mentioned with a check to see if `domain_name` is nil and only query if it is should be sufficient.

**Comment by mikfire** [comment]
That is about what I did. I just wanted to make sure I wasn't causing any extra headaches later.

Here's a patch, in case it helps.
```patch
--- resolve_disk_settings.orig  2022-06-08 07:35:55.125630077 -0400
+++ resolve_disk_settings.rb    2022-06-08 07:31:13.120633520 -0400
@@ -97,14 +97,14 @@
             # the default storage prefix is typically: /var/lib/libvirt/images/
             storage_prefix = "#{File.dirname(domain_volumes[0][:absolute_path])}/" # steal
           else
-            # Ensure domain name is set for subsequent steps if restarting a machine without a box
-            libvirt_domain = env[:machine].provider.driver.connection.client.lookup_domain_by_uuid(
-              env[:machine].id
-            )
-            domain_xml = libvirt_domain.xml_desc(1)
-            xml_descr = REXML::Document.new(domain_xml)
-            domain_name = xml_descr.elements['domain'].elements['name'].text
-
+            if env[:machine].id
+              libvirt_domain = env[:machine].provider.driver.connection.client.lookup_domain_by_uuid(
+                env[:machine].id
+              )
+              domain_xml = libvirt_domain.xml_desc(1)
+              xml_descr = REXML::Document.new(domain_xml)
+              domain_name = xml_descr.elements['domain'].elements['name'].text
+            end
             storage_prefix = get_disk_storage_prefix(env[:machine], storage_pool_name)
           end
```

Thanks for the help.
