### ISSUE TITLE
resolve_disk_settings.rb bug in 0.9.0 release

### ISSUE THREAD

**Issue by nathanjsweet** [vagrant-libvirt/vagrant-libvirt#1519]
I've been running a particular Vagrantfile for months without a problem as part of our regular build process. I can confirm that this is a bug introduced by your 0.9.0 release (I don't hit it if I specify the 0.8.2 release). 

When I run `vagrant up bootstrap01` I get the following error message:
```
Bringing machine 'bootstrap01' up with 'libvirt' provider...
Traceback (most recent call last):
	34: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	33: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'
	32: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'
	31: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
	30: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'
	29: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'
	28: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	27: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	26: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	25: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	24: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	23: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	22: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	21: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_check_outdated.rb:31:in `call'
	20: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	19: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
	18: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	17: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	16: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	15: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	14: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	13: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	12: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	11: from /home/nathan/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/cleanup_on_failure.rb:21:in `call'
	10: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	 9: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/provision.rb:80:in `call'
	 8: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	 7: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	 6: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	 5: from /home/nathan/.vagrant.d/gems/2.7.4/gems/vagrant-hostmanager-1.8.9/lib/vagrant-hostmanager/action/update_all.rb:24:in `call'
	 4: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	 3: from /home/nathan/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
	 2: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	 1: from /home/nathan/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/resolve_disk_settings.rb:101:in `call'
/home/nathan/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/resolve_disk_settings.rb:101:in `lookup_domain_by_uuid': no implicit conversion of nil into String (TypeError)
```
Here's the Vagrantfile:
```
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# Require a recent version of vagrant otherwise some have reported errors 
# setting host names on boxes
Vagrant.require_version ">= 1.7.2"

CONFIG = {
  "domain" =>               ENV['CLUSTER_DOMAIN'] || "ocp1.k8s.work",
  "network_name" =>         ENV['CLUSTER_NETWORK'] || "ocp1",
  "network_cidr" =>         ENV['CLUSTER_CIDR'] || "192.168.200.0/24",
  "domain_mac_seed" =>      ENV['DOMAIN_MAC_SEED'] || "52:54:00:00",
  "num_bootstrap_nodes" =>  ENV['NUM_BOOTSTRAP_NODES'] || "1",
  "bootstrap_cores" =>      ENV['BOOTSTRAP_CORES'] || "2",
  "bootstrap_memory" =>     ENV['BOOTSTRAP_MEMORY'] || "4096",
  "bootstrap_disk" =>       ENV['BOOTSTRAP_DISK'] || "40G", 
  "bootstrap_mac" =>        ENV['BOOTSTRAP_MAC'] || ":01",
  "num_cp_nodes" =>         ENV['NUM_CP'] || "3",
  "cp_cores" =>             ENV['CP_CORES'] || "8",
  "cp_memory"  =>           ENV['CP_MEMORY'] || "16384",
  "cp_disk" =>              ENV['CP_DISK'] || "100G", 
  "cp_mac" =>               ENV['CP_MAC'] || ":02",
  "num_worker_nodes" =>     ENV['NUM_WORKER'] || "3",
  "worker_cores" =>         ENV['WORKER_CORES'] || "4",
  "worker_memory"  =>       ENV['WORKER_MEMORY'] || "8192",
  "worker_disk" =>          ENV['WORKER_DISK'] || "100G", 
  "worker_mac" =>           ENV['WORKER_MAC'] || ":03",
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false

  BS = (CONFIG['num_bootstrap_nodes']).to_i
  (1..BS).each do |i|
    vm_name = "bootstrap0#{i}"
    vm_cpu = CONFIG['bootstrap_cores']
    vm_memory = CONFIG['bootstrap_memory']
    vm_disk = CONFIG['bootstrap_disk']
    vm_mac = "#{CONFIG['domain_mac_seed']}#{CONFIG['bootstrap_mac']}:0#{i}"
    config.vm.define vm_name do |node|
      node.vm.hostname = "#{vm_name}.#{CONFIG['domain']}"
      node.ssh.username = "core"
      node.vm.network :private_network,
        :type => "dhcp",
        :libvirt__network_name => "#{CONFIG['network_name']}",
        :libvirt__always_destroy => false,
        :autostart => false,
        :mac => vm_mac
      node.vm.provider :libvirt do |domain|
        domain.uri = 'qemu+unix:///system'
        domain.driver = 'kvm'
        domain.memory = "#{vm_memory}".to_i
        domain.cpus = "#{vm_cpu}".to_i
        domain.storage :file, :size => "#{vm_disk}", :type => 'qcow2'
        boot_network = {'network' => CONFIG['network_name']}
        domain.boot 'hd'
        domain.boot boot_network
        domain.mgmt_attach = false
      end
    end
  end
end
```
(I've truncated it a bit, as there are more VM definitions, but they aren't relevant to this failure)

It looks like there is a bad nil check[ on this line](https://github.com/vagrant-libvirt/vagrant-libvirt/blame/master/lib/vagrant-libvirt/action/resolve_disk_settings.rb#L100).

**Comment by electrofelix** [comment]
I think this is fixed in #1509 so it will be in the next release.

**Comment by bk201** [comment]
Hit the same issue when provisioning box-less VM:

```
$ cat Vagrantfile

Vagrant.configure("2") do |config|
  config.vm.define :pxeclient do |pxeclient|
    pxeclient.vm.provider :libvirt do |domain|
      domain.boot 'network'
    end
  end
end

$ vagrant up
Bringing machine 'pxeclient' up with 'libvirt' provider...
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/resolve_disk_settings.rb:101:in `lookup_domain_by_uuid': no implicit conversion of nil into String (TypeError)
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/resolve_disk_settings.rb:101:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/cleanup_on_failure.rb:21:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_check_outdated.rb:31:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```

Confirm https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1509 fix the problem.

**Comment by electrofelix** [comment]
Hoping to do a release shortly, so closing as it should appear fixed.
