### ISSUE TITLE
RubyZip dependency conflict

### ISSUE THREAD

**Issue by sempervictus** [vagrant-libvirt/vagrant-libvirt#1648]
**Describe the bug**
The `rubyzip` gem is conflicting after upgrading to Vagrant 2.3.2 on Arch

**To Reproduce**
1. Install current Vagrant package on Arch Linux
2. Try to install the plugin

**Expected behavior**
Plugin installs

**Screenshots**
```shell
$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies rubyzip (= 2.3.1) and rubyzip (= 2.3.2)
  Activated rubyzip-2.3.2
  which does not match conflicting dependency (= 2.3.1)

  Conflicting dependency chains:
    rubyzip (= 2.3.2), 2.3.2 activated

  versus:
    rubyzip (= 2.3.1)

  Gems matching rubyzip (= 2.3.1):
    rubyzip-2.3.1
```

**Versions (please complete the following information):**:
- Libvirt version: n/a
- Vagrant version [output of `vagrant version`]: 2.3.2
- Vagrant flavour [Upstream or Distro]: distro
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:

**Debug Log**
```ruby
ERROR vagrant: /opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/lib/vagrant/plugin/manager.rb:200:in `rescue in install_plugin'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/lib/vagrant/plugin/manager.rb:116:in `install_plugin'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/plugins/commands/plugin/action/install_gem.rb:30:in `call'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/lib/vagrant/action/warden.rb:48:in `call'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/lib/vagrant/action/builder.rb:180:in `call'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/lib/vagrant/action/runner.rb:101:in `block in run'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/lib/vagrant/action/runner.rb:101:in `run'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/plugins/commands/plugin/command/base.rb:14:in `action'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/plugins/commands/plugin/command/install.rb:70:in `block in execute'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/plugins/commands/plugin/command/install.rb:69:in `each'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/plugins/commands/plugin/command/install.rb:69:in `execute'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/plugins/commands/plugin/command/root.rb:66:in `execute'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/lib/vagrant/cli.rb:67:in `execute'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/lib/vagrant/environment.rb:301:in `cli'
/opt/vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/bin/vagrant:248:in `<main>'
 INFO interface: error: Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies rubyzip (= 2.3.1) and rubyzip (= 2.3.2)
  Activated rubyzip-2.3.2
  which does not match conflicting dependency (= 2.3.1)

  Conflicting dependency chains:
    rubyzip (= 2.3.2), 2.3.2 activated

  versus:
    rubyzip (= 2.3.1)

  Gems matching rubyzip (= 2.3.1):
    rubyzip-2.3.1
```

**Comment by electrofelix** [comment]
As this plugin doesn't depend on rubyzip it's unlikely that there is anything that can be done from this project to resolve.

**Comment by sempervictus** [comment]
Interesting, it does end up in the lockfile:
```shell
$ basename $PWD ; grep rubyzip Gemfile.lock 
vagrant-libvirt
      rubyzip (~> 2.0)
    rubyzip (2.3.2)
      rubyzip (~> 2.0)
```

**Comment by electrofelix** [comment]
That's probably because the plugin depends on vagrant which in turn depends on rubyzip https://github.com/hashicorp/vagrant/blob/d14bd022308e1e246b64ba6a81ba7c7a573107ee/vagrant.gemspec#L36

It's most likely this is another occurrence of hashicorp/vagrant#12837 with rubygems/rubygems#5843 being the underlying issue

**Comment by electrofelix** [comment]
I've just done a quick test with a pristine archlinux env and I've not been able to reproduce this.

Used the archlinux box defined in the qa test bed at: https://github.com/vagrant-libvirt/vagrant-libvirt-qa (launched with `--no-provision` to skip using the default install script for the upstream package)
And followed the steps documented at: https://vagrant-libvirt.github.io/vagrant-libvirt/installation.html#arch

```
[vagrant@archlinux ~]$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching xml-simple-1.1.9.gem
Fetching nokogiri-1.13.9-x86_64-linux.gem
Fetching ruby-libvirt-0.8.0.gem
Building native extensions. This could take a while...
Fetching formatador-1.1.0.gem
Fetching fog-core-2.3.0.gem
Fetching fog-xml-0.1.4.gem
Fetching fog-json-1.2.0.gem
Fetching fog-libvirt-0.9.0.gem
Fetching diffy-3.4.2.gem
Fetching vagrant-libvirt-0.10.8.gem
Installed the plugin 'vagrant-libvirt (0.10.8)'!
[vagrant@archlinux ~]$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
[vagrant@archlinux ~]$ vagrant version
Installed Version: 2.3.2
Latest Version: 2.3.2
 
You're running an up-to-date version of Vagrant!
[vagrant@archlinux ~]$ vagrant plugin list
vagrant-libvirt (0.10.8, global)
```

If you want to use it, may need to reboot the VM first if the kernel was updated.

Did you possibly have other plugins installed before you upgraded Vagrant? I'm wondering if there was a different plugin that was pinning the dependency and causing the conflict.
