### ISSUE TITLE
Veryisolated network mode does not work

### ISSUE THREAD

**Issue by david-sykora** [vagrant-libvirt/vagrant-libvirt#1649]
**Describe the bug**
The veryisolated mode isn't working. It looks like the variables that should be filled do not contain the necessary data:

When creating a domain with a veryisolated mode, the [action/create_networks.rb:create_private_network](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/ddb6dbd0767f55e337749d9b5fe2e2dbdb087c2d/lib/vagrant-libvirt/action/create_networks.rb#L309) function is called and the `interface_network` variable should be filled, but its value is:
```ruby
{:name=>"vagrant-libvirt", :ip_address=>nil, :netmask=>"255.255.255.0", :network_address=>nil, :bridge_name=>"virbr1", :domain_name=>nil, :ipv6_address=>nil, :ipv6_prefix=>nil, :created=>false, :active=>false, :autostart=>false, :guest_ipv6=>"yes", :libvirt_network=>nil}
```
mainly the value of `@interface_network[:network_address]` is `nil` and this raises the an exception:
```
/home/john/.vagrant.d/gems/3.0.4/gems/vagrant-libvirt-0.10.8/lib/vagrant-libvirt/action/create_networks.rb:351:in `create_private_network': undefined method `to_range' for nil:NilClass (NoMethodError)
Did you mean?  to_any
	from /home/john/.vagrant.d/gems/3.0.4/gems/vagrant-libvirt-0.10.8/lib/vagrant-libvirt/action/create_networks.rb:224:in `handle_ip_option'
	from /home/john/.vagrant.d/gems/3.0.4/gems/vagrant-libvirt-0.10.8/lib/vagrant-libvirt/action/create_networks.rb:88:in `block (2 levels) in call'
	from /home/john/.vagrant.d/gems/3.0.4/gems/vagrant-libvirt-0.10.8/lib/vagrant-libvirt/action/create_networks.rb:52:in `each'
TRUNCATED
```

[there](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/ddb6dbd0767f55e337749d9b5fe2e2dbdb087c2d/lib/vagrant-libvirt/action/create_networks.rb#L332)  is a check that checks for the presence of the address, but it doesn't seem to solve the problem with its nil value

**Expected behavior**
a private network for a vm management should be created

**Versions (please complete the following information):**:
- Libvirt version: 8.8.0
- Vagrant version [output of `vagrant version`]: 2.3.2
- Vagrant flavour [Upstream or Distro]: Arch 6.1.0-rc2-1-mainline
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: 0.10.8

**A Vagrantfile to reproduce the issue:**
```ruby
Vagrant.configure("2") do |config|
  config.vm.define "test" do |test|
    test.vm.box = "roboxes/alpine39"
    test.vm.provider "libvirt" do |kvm|
       kvm.management_network_mode = "veryisolated"
    end
  end
end
```

**Comment by david-sykora** [comment]
My bad. This is probably due to my misunderstanding of how Libvirt networking works. [Networks in "veryprivate" mode have all communication with "guest" disabled](https://libvirt.org/formatnetwork.html#network-config-with-no-gateway-addresses). I am trying to achieve the ability to set up a management network so that communication can only take place between "guest" and "host" (no NAT, no forwading outiside of host). The vagrant-libvirt documentation states that it is possible to set the management network to the "veryisolated" mode. What are the theoretical possible use cases for this mod?

**Comment by electrofelix** [comment]
@david-sykora I think for what you want, `management_network_mode = "none"` will work. https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html#private-network-options contains a `forward_mode` that is the analogous (not sure how we ended up with forward_mode => mode instead of keeping the same name).

However, the bug is still valid as the docs state that veryisolated should be a valid config, though I can't really guess as to what this would be useful for. #324 suggests that it might be useful for private networks where multiple users are sharing the same libvirt host and wish for them to use the same network config without talking to other guests started by other users.

I'd have to test to make sure it doesn't break lots of other stuff as well, but either the code needs to be fixed to support it, or it needs to be rejected early on as not valid.
