### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by mazzy89** [vagrant-libvirt/vagrant-libvirt#1678]
**Describe the bug**

A reload of a node causes the error

```
$ vagrant reload worker03.hznux.talos.home

==> worker03.hznux.talos.home: Attempting graceful shutdown of VM...
    worker03.hznux.talos.home: Guest communication could not be established! This is usually because
    worker03.hznux.talos.home: SSH is not running, the authentication information was changed,
    worker03.hznux.talos.home: or some other networking issue. Vagrant will force halt, if
    worker03.hznux.talos.home: capable.
==> worker03.hznux.talos.home: Attempting direct shutdown of domain...
/root/.vagrant.d/gems/3.1.2/gems/vagrant-libvirt-0.10.8/lib/vagrant-libvirt/action/start_domain.rb:52:in `+': no implicit conversion of nil into String (TypeError)
	from /root/.vagrant.d/gems/3.1.2/gems/vagrant-libvirt-0.10.8/lib/vagrant-libvirt/action/start_domain.rb:52:in `block in call'
	from /root/.vagrant.d/gems/3.1.2/gems/vagrant-libvirt-0.10.8/lib/vagrant-libvirt/action/start_domain.rb:49:in `each'
	from /root/.vagrant.d/gems/3.1.2/gems/vagrant-libvirt-0.10.8/lib/vagrant-libvirt/action/start_domain.rb:49:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /root/.vagrant.d/gems/3.1.2/gems/vagrant-libvirt-0.10.8/lib/vagrant-libvirt/action/set_boot_order.rb:22:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /root/.vagrant.d/gems/3.1.2/gems/vagrant-libvirt-0.10.8/lib/vagrant-libvirt/action/shutdown_domain.rb:15:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /root/.vagrant.d/gems/3.1.2/gems/vagrant-libvirt-0.10.8/lib/vagrant-libvirt/action/forward_ports.rb:202:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/plugins/commands/reload/command.rb:42:in `block in execute'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/plugin/v2/command.rb:243:in `block in with_target_vms'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/plugin/v2/command.rb:232:in `each'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/plugins/commands/reload/command.rb:40:in `execute'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/cli.rb:67:in `execute'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/environment.rb:290:in `cli'
	from /usr/share/vagrant/gems/gems/vagrant-2.2.19/bin/vagrant:231:in `<top (required)>'
	from /usr/share/vagrant/gems/bin/vagrant:25:in `load'
	from /usr/share/vagrant/gems/bin/vagrant:25:in `<main>'
```

**To Reproduce**

`vagrant reload <node>`

**Expected behavior**

The machine reloads and boot again.

**Screenshots**

**Versions (please complete the following information):**:
- Libvirt version: libvirtd (libvirt) 8.1.0
- Vagrant version [output of `vagrant version`]: 2.3.2
- Vagrant flavour [Upstream or Distro]:  Fedora 36
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: 0.10.8

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`
```
Delete this text and drag and drop the log file for github to attach and add a link here
```

**A Vagrantfile to reproduce the issue:**
```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Comment by electrofelix** [comment]
Missing a ResolveDiskSettings before the action_start at https://github.com/vagrant-libvirt/vagrant-libvirt/blob/451c6f6c5374b0ad6f181057153b2dff0d80a705/lib/vagrant-libvirt/action.rb#L228

**Comment by electrofelix** [comment]
There was an acceptance test to catch this scenario, but it appears it's not working for some reason, so I'll probably check what is happening there before merging.
