### ISSUE TITLE
Wrong domain definition with UEFI boot

### ISSUE THREAD

**Issue by jeka** [vagrant-libvirt/vagrant-libvirt#1723]
**Describe the bug**
Vagrant generates wrong domain XML when setting up domain with UEFI boot.

**To Reproduce**

with Vagrantfile: (adopted [Secure Encryption Virtualization (SEV))](https://vagrant-libvirt.github.io/vagrant-libvirt/examples.html#secure-encryption-virtualization-sev)
```
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.loader = "/usr/share/edk2/ovmf/OVMF_CODE.cc.fd"
    libvirt.nvram = "/usr/share/edk2/ovmf/OVMF_VARS.fd"
    libvirt.machine_type = "q35"
  end

  config.vm.define "uefi-node" do |vm|
    vm.vm.provider :libvirt do |domain|
      domain.cpus = 1
      domain.memory = 256
      domain.storage :file, :size => '1G', :device => 'sda', :type => 'raw', :bus => 'scsi', :discard => 'unmap', :detect_zeroes => 'on'
    end
  end

end
```
vagrant generates domain XML with **os** section as follows:
```
  <os>
    <type arch='x86_64' machine='pc-q35-rhel8.6.0'>hvm</type>
    <loader readonly='yes' type='pflash'>/usr/share/edk2/ovmf/OVMF_CODE.cc.fd</loader>
    <nvram>/usr/share/edk2/ovmf/OVMF_VARS.fd'</nvram>
    <boot dev='hd'/>
    <bootmenu enable='no'/>
  </os>
```
Which is wrong. While that will work if you are booting only 1 machine in UEFI mode, it still modifies a file that should not be touched.

The correct XML part would be:
```
  <os>
    <type arch='x86_64' machine='pc-q35-rhel8.6.0'>hvm</type>
    <loader readonly='yes' type='pflash'>/usr/share/edk2/ovmf/OVMF_CODE.cc.fd</loader>
    <nvram template='/usr/share/edk2/ovmf/OVMF_VARS.fd'>/var/lib/libvirt/qemu/nvram/bug_uefi-node-VARS.fd</nvram>
    <boot dev='hd'/>
    <bootmenu enable='no'/>
```
The result should be that every single machine booted in UEFI mode should have dedicated EFI vars storage.
I guess `/var/lib/libvirt/qemu/nvram` is specific to my host OS  (CentOS Stream 8)

**Versions (please complete the following information):**:
- Libvirt version:
```
$ virsh version
Compiled against library: libvirt 8.0.0
Using library: libvirt 8.0.0
Using API: QEMU 8.0.0
Running hypervisor: QEMU 6.2.0
```
- Vagrant version [output of `vagrant version`]:
```
Installed Version: 2.3.4
Latest Version: 2.3.4
```
- Vagrant flavour [Upstream or Distro]: Upstream
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]:
`vagrant-libvirt (0.11.2, global)` - the only plugin installed

**Comment by cwegener** [comment]
I only just ran into the same issue today when building a multi-VM vagrantfile with Windows VMs that use UEFI boot.

In my case, the default SELinux configuration in `/etc/libvirt/qemu.conf` was actually yelling at me about a relabeling conflict as soon as I tried spinning up the second UEFI VM from the same VARS file.

As a temporary workaround to get around the relabeling conflict I did change the `security_default_confined` from `1` to `0` to run the VMs unconfined instead, which lets all VMs read and write to the same NVRAM instance, which is obviously wrong as you have documented.

It would be great to have this handled correctly.

Unfortunately, I won't have any capacity to look at  making the necessary changes in `vagrant-libvirt` to correct this issue.

Here's the error that shows up when running with SELinux and the default configuration of `security_default_confined = 1`:

```
An unexpected error occurred when executing the action on the
'winclient1' machine. Please report this as a bug:

Call to virDomainCreateWithFlags failed: Requested operation is not valid: Setting different SELinux label on /usr/share/edk2/ovmf-4m/OVMF_VARS.secboot.fd which is already in use

/home/fedora/.vagrant.d/gems/3.1.3/gems/fog-libvirt-0.11.0/lib/fog/libvirt/requests/compute/vm_action.rb:7:in `create'
/home/fedora/.vagrant.d/gems/3.1.3/gems/fog-libvirt-0.11.0/lib/fog/libvirt/requests/compute/vm_action.rb:7:in `vm_action'
/home/fedora/.vagrant.d/gems/3.1.3/gems/fog-libvirt-0.11.0/lib/fog/libvirt/models/compute/server.rb:76:in `start'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/start_domain.rb:546:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/set_boot_order.rb:22:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/share_folders.rb:22:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:21:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/delayed.rb:19:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:14:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/create_network_interfaces.rb:197:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/create_networks.rb:98:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/create_domain.rb:452:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/resolve_disk_settings.rb:143:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/create_domain_volume.rb:97:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/handle_box_image.rb:127:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/handle_storage_pool.rb:63:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/provision.rb:80:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/home/fedora/.vagrant.d/gems/3.1.3/gems/vagrant-libvirt-0.11.2/lib/vagrant-libvirt/action/cleanup_on_failure.rb:21:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'
/usr/share/vagrant/gems/gems/vagrant-2.2.19/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
/home/fedora/.vagrant.d/gems/3.1.3/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

**Comment by ju2wheels** [comment]
Linking #1725 as tangentially related to UEFI XML issues.
