### ISSUE TITLE
Regression: iommu driver option is only supported for virtio devices

### ISSUE THREAD

**Issue by Wenzel** [vagrant-libvirt/vagrant-libvirt#1743]
**Describe the bug**
When setting the `libvirt.nic_model_type`to something else than `virtio`, the domain XML cannot be generated since an `iommu`option has been inserted, which is only valid for in the context of `virtio devices`.

**To Reproduce**
1. Define a Vagrantfile
2. Define a libvirt section with a non `virtio` driver
![image](https://github.com/vagrant-libvirt/vagrant-libvirt/assets/964610/906ccb2c-a29b-485e-af5c-90d7a868c348)
4. Run `vagrant up`
5. Observe that it fails:
![image](https://github.com/vagrant-libvirt/vagrant-libvirt/assets/964610/cc70c28d-ef6f-4291-98cf-f370613b75aa)

**Expected behavior**
The domain should have been defined and started.

**Screenshots**
see above

**Versions (please complete the following information):**:
- Libvirt version: `9.0.0-2ubuntu1`
- Vagrant version : `2.3.6`
- Vagrant flavour : `23.04` 
- Vagrant plugins versions:
```
vagrant-libvirt (0.12.1, global)
  - Version Constraint: 0.12.1
vagrant-reload (0.0.1, global)
  - Version Constraint: > 0
```

**Debug Log**
Attach Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt >vagrant.log 2>&1`
[vagrant.log](https://github.com/vagrant-libvirt/vagrant-libvirt/files/11555436/vagrant.log)

**A Vagrantfile to reproduce the issue:**
```ruby
Vagrant.configure("2") do |config|
  # The Packer box we just added
  config.vm.box = "kafl_windows"
  # we use winrm
  config.vm.communicator = "winrm"
  # HTTP
  config.winrm.port = 5985
  # basic
  config.winrm.transport = :plaintext
  # credentials
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  # explicitely tell Vagrant that this is a Windows guest
  # no need to guess
  config.vm.guest = :windows

  config.vm.provider :libvirt do |libvirt|
    libvirt.disk_bus = "ide"
    libvirt.nic_model_type = "e1000e"
    libvirt.memory = 4096
  end
end
```

Related:
- https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1702
- https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1688

**Comment by Wenzel** [comment]
I tested `vagrant plugin install vagrant-libvirt --plugin-version 0.11.2` and I confirm that this version is the most recent that fixes the bug.

**Comment by electrofelix** [comment]
Looks like there is a mismatch between what options are read during create and start. Create is ignoring the e1000 nic model type and then start is updating the domain xml to set the model type, and at the same time failing to delete the iommu setting.

So almost 2 bugs in one.

**Comment by electrofelix** [comment]
Did a bit of digging and it turns out I missed that part of the problem is the first interface is the management network, so that means it's model type is supposed to be controlled by the config option `management_network_model_type` https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html#management-network. When this attribute was added, it is set to default to `virtio` when not set, meaning that later when iterating over the networks and looking to use `nic_model_type` as the default if not set, `management_network_model_type` is always set.

However previously this was controlled by `nic_model_type`, and since this was only added in 0.12.0, I think it's reasonable to assume that what should be happening is that if `management_network_model_type` is not explicitly set, it should default to `nic_model_type` to match the previous behaviour while allowing for the management network model type to also be separately overridden.

**Comment by electrofelix** [comment]
@Wenzel Assuming the PR passes it's checks, if you feel comfortable following https://github.com/vagrant-libvirt/vagrant-libvirt#latest-development-version it should be possible to install the gem by downloading the artifact referenced in https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1747#issuecomment-1587979044.

I've been struggling for time to fix this so while I think the PR should work as expected, it's relying on unit tests to validate the behaviour and it might take a while before I can take it for a proper test to ensure my unit tests are actually working. (though it does look like there is a compatibility bug with earlier ruby releases for older vagrants still in use on some distros).

**Comment by Wenzel** [comment]
Hi @electrofelix ,

First i'd like to thank you for your reply, investigation and the quick solution you provided !

Second, I'm impressed by the infrastructure you have developed, it's very convenient to install the development version from the artifact built from the PR !

So I tested your PR today:
```
vagrant plugin install ./vagrant-libvirt-0.12.2.pre.3.gem
Installing the './vagrant-libvirt-0.12.2.pre.3.gem' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Successfully uninstalled vagrant-libvirt-0.11.2
Installed the plugin 'vagrant-libvirt (0.12.2.pre.3)'!
```

And ran gain my Vagrantfile against it.
I'm hitting the following (unrelated ?) error:
```ruby
==> vagrant-kafl-windows:  -- CHANNEL:             target_type=virtio, target_name=com.redhat.spice.0
==> vagrant-kafl-windows: Removing domain...
==> vagrant-kafl-windows: Deleting the machine folder
/home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.3/lib/vagrant-libvirt/action/start_domain.rb:21:in `initialize': undefined local variable or method `env' for #<VagrantPlugins::ProviderLibvirt::Action::StartDomain:0x00007fd9eee86230 @logger=#<Log4r::Logger:0x00007fd9eee860c8 @fullname="vagrant_libvirt::action::start_domain", @outputters=[], @additive=true, @name="start_domain", @path="vagrant_libvirt::action", @parent=#<Log4r::Logger:0x00007fd9f2b00800 @fullname="vagrant_libvirt::action", @outputters=[], @additive=true, @name="action", @path="vagrant_libvirt", @parent=#<Log4r::RootLogger:0x00007fd9f2ba52d8 @level=0, @outputters=[]>, @level=0, @trace=false>, @level=0, @trace=false>> (NameError)

          config = env[:machine].provider_config
                   ^^^
Did you mean?  _env
               end
               END
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:121:in `new'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:121:in `finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:34:in `block in initialize'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:34:in `map'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:34:in `initialize'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/builder.rb:220:in `new'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/builder.rb:220:in `to_app'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/builtin/call.rb:52:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/builder.rb:180:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/runner.rb:101:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/runner.rb:101:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.3/lib/vagrant-libvirt/action/create_network_interfaces.rb:170:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.3/lib/vagrant-libvirt/action/create_networks.rb:40:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.3/lib/vagrant-libvirt/action/create_domain.rb:466:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.3/lib/vagrant-libvirt/action/resolve_disk_settings.rb:143:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.3/lib/vagrant-libvirt/action/create_domain_volume.rb:98:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.3/lib/vagrant-libvirt/action/handle_box_image.rb:129:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.3/lib/vagrant-libvirt/action/handle_storage_pool.rb:63:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.3/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/builtin/provision.rb:80:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.3/lib/vagrant-libvirt/action/cleanup_on_failure.rb:21:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/builder.rb:180:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/runner.rb:101:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/runner.rb:101:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/builder.rb:180:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/runner.rb:101:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/runner.rb:101:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/machine.rb:248:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/machine.rb:217:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/environment.rb:631:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/machine.rb:203:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/machine.rb:203:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
        from /opt/vagrant/embedded/gems/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
make[1]: *** [Makefile:9: init] Error 1
make[1]: Leaving directory '/home/mtarral/kafl/kafl/examples/windows_x86_64-userspace'
```

Full log:
https://gist.github.com/Wenzel/c7f7657c7f5a835202607aea041cfa68

Thanks for the update !

**Comment by electrofelix** [comment]
@Wenzel looks like GitHub messed up and didn't re-run the workflow to comment on the PR and update the gem referenced.

The latest gem build on the PR fixes that variable issue and should be downloadable from the page 
https://github.com/vagrant-libvirt/vagrant-libvirt/actions/runs/5248927743

Sorry about that

**Comment by Wenzel** [comment]
Thanks for the quick update !

New error here 🙂 

~~~ruby
==> vagrant-kafl-windows: Creating shared folders metadata...
==> vagrant-kafl-windows: Removing domain...
==> vagrant-kafl-windows: Deleting the machine folder
/home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.4/lib/vagrant-libvirt/action/start_domain.rb:107:in `block in call': undefined method `attributes' for nil:NilClass (NoMethodError)

            iface.delete_element(iface_driver) if iface_driver.attributes.empty?
                                                              ^^^^^^^^^^^
        from /opt/vagrant/embedded/gems/gems/rexml-3.2.5/lib/rexml/xpath.rb:68:in `each'
        from /opt/vagrant/embedded/gems/gems/rexml-3.2.5/lib/rexml/xpath.rb:68:in `each'
        from /home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.4/lib/vagrant-libvirt/action/start_domain.rb:77:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.4/lib/vagrant-libvirt/action/set_boot_order.rb:22:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.4/lib/vagrant-libvirt/action/share_folders.rb:22:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/action/warden.rb:48:in `call'
        from /home/mtarral/.vagrant.d/gems/3.1.4/gems/vagrant-libvirt-0.12.2.pre.4/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:21:in `call'
~~~

**Comment by electrofelix** [comment]
@Wenzel few more unit tests added and the new bug you hit fixed, gem updated in the pr comment https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1747#issuecomment-1587979044

Didn't get to spin up an actual test machine to check the settings of the vagrantfile you provided, hopefully tomorrow for that part.

**Comment by votdev** [comment]
> @Wenzel few more unit tests added and the new bug you hit fixed, gem updated in the pr comment [#1747 (comment)](https://github.com/vagrant-libvirt/vagrant-libvirt/pull/1747#issuecomment-1587979044)
> 
> Didn't get to spin up an actual test machine to check the settings of the vagrantfile you provided, hopefully tomorrow for that part.

Version `0.12.2.pre.9` has fixed the issue for me. Thx.

**Comment by Wenzel** [comment]
@electrofelix thanks for the update !
I confirm this works too here 💯

**Comment by electrofelix** [comment]
Forgot to say I did a quick test run and it appeared to confirm it was fixed though there are a few gotchas to enabling iommu which are separate.
