### ISSUE TITLE
`vagrant halt -f` does not poweroff the domain if shutdown fails

### ISSUE THREAD

**Issue by arg0d** [vagrant-libvirt/vagrant-libvirt#1765]
**Describe the bug**
For some reason `vagrant halt -f` attempts to shutdown the domain (ACPI), and waits for the domain to shut itself down. If guest does not perform shutdown after ACPI, then vagrant-libvirt times out after 60 seconds and throws an exception.

**To Reproduce**
1. `vagrant up` a VM which does not respond to ACPI.
2. Attempt to poweroff the VM using `vagrant halt -f`.

**Expected behavior**
The domain is powered off immediately without sending ACPI.

**Screenshots**
n/a

**Versions (please complete the following information):**:
n/a

**Debug Log**
```
$ vagrant halt -f
==> default: Attempting direct shutdown of domain...
Traceback (most recent call last):
	68: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/bin/vagrant:248:in `<main>'
	67: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:301:in `cli'
	66: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/cli.rb:67:in `execute'
	65: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/plugins/commands/halt/command.rb:30:in `execute'
	64: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	63: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/plugin/v2/command.rb:232:in `each'
	62: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/plugin/v2/command.rb:243:in `block in with_target_vms'
	61: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/plugins/commands/halt/command.rb:31:in `block in execute'
	60: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/machine.rb:203:in `action'
	59: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/machine.rb:203:in `call'
	58: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/environment.rb:631:in `lock'
	57: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/machine.rb:217:in `block in action'
	56: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/machine.rb:248:in `action_raw'
	55: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `run'
	54: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/busy.rb:19:in `busy'
	53: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `block in run'
	52: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builder.rb:180:in `call'
	51: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	50: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	49: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	48: from /home/kantanavicius/.vagrant.d/gems/2.7.6/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/forward_ports.rb:202:in `call'
	47: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	46: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	45: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `run'
	44: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/busy.rb:19:in `busy'
	43: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `block in run'
	42: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builder.rb:180:in `call'
	41: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	40: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	39: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	38: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	37: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `run'
	36: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/busy.rb:19:in `busy'
	35: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `block in run'
	34: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builder.rb:180:in `call'
	33: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	32: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	31: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	30: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	29: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	28: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	27: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `run'
	26: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/busy.rb:19:in `busy'
	25: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `block in run'
	24: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builder.rb:180:in `call'
	23: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	22: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	21: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	20: from /home/kantanavicius/.vagrant.d/gems/2.7.6/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/shutdown_domain.rb:15:in `call'
	19: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	18: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	17: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `run'
	16: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/busy.rb:19:in `busy'
	15: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `block in run'
	14: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builder.rb:180:in `call'
	13: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	12: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	11: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	10: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builtin/call.rb:43:in `call'
	 9: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `run'
	 8: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/util/busy.rb:19:in `busy'
	 7: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/runner.rb:101:in `block in run'
	 6: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/builder.rb:180:in `call'
	 5: from /opt/vagrant/embedded/gems/2.3.1/gems/vagrant-2.3.1/lib/vagrant/action/warden.rb:48:in `call'
	 4: from /home/kantanavicius/.vagrant.d/gems/2.7.6/gems/vagrant-libvirt-0.12.2/lib/vagrant-libvirt/action/shutdown_domain.rb:61:in `call'
	 3: from /home/kantanavicius/.vagrant.d/gems/2.7.6/gems/fog-core-2.3.0/lib/fog/core/model.rb:72:in `wait_for'
	 2: from /home/kantanavicius/.vagrant.d/gems/2.7.6/gems/fog-core-2.3.0/lib/fog/core/wait_for.rb:6:in `wait_for'
	 1: from /home/kantanavicius/.vagrant.d/gems/2.7.6/gems/fog-core-2.3.0/lib/fog/core/wait_for.rb:6:in `loop'
/home/kantanavicius/.vagrant.d/gems/2.7.6/gems/fog-core-2.3.0/lib/fog/core/wait_for.rb:9:in `block in wait_for': The specified wait_for timeout (59.932046826 seconds) was exceeded (Fog::Errors::TimeoutError)
```

**A Vagrantfile to reproduce the issue:**
n/a

**Comment by arg0d** [comment]
The same issue from before? https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1265

**Comment by arg0d** [comment]
Relevant documentation from Vagrant: https://developer.hashicorp.com/vagrant/docs/cli/halt
> [-f](https://developer.hashicorp.com/vagrant/docs/cli/halt#f) or --force - Do not attempt to gracefully shut down the machine. This effectively pulls the power on the guest machine.

**Comment by electrofelix** [comment]
@arg0d I think I might hopefully have an acceptance test in place now to prevent a regression of the expected behaviour in the future.

**Comment by arg0d** [comment]
Nice, I was trying to write a test, but my Ruby knowledge is lacking.
