### ISSUE TITLE
Waiting for domain to get an IP address...

### ISSUE THREAD

**Issue by adamretter** [vagrant-libvirt/vagrant-libvirt#177]
Using vagrant-libvirt with Vagrant 1.5.2 and I am trying to bring up a Vagrant box based on a RHEL 6.4 base-box that I have created using libvirt. The host system is also RHEL 6.4.

The box does come up fine apart from the networking, from the output of `sudo vagrant up --provider libvirt` I see:

```
[aretter@dri-dev1 test-vagrant]$ sudo vagrant up --provider libvirt
[sudo] password for aretter: 
Bringing machine 'default' up with 'libvirt' provider...
2014-04-22 15:49:49.779+0000: 4212: info : libvirt version: 0.10.2, package: 29.el6_5.7 (Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>, 2014-03-26-06:33:24, x86-022.build.eng.bos.redhat.com)
2014-04-22 15:49:49.779+0000: 4212: warning : virNetTLSContextCheckCertificate:1142 : Certificate check failed Certificate [session] owner does not match the hostname localhost
==> default: HandleBoxUrl middleware is deprecated. Use HandleBox instead.
==> default: This is a bug with the provider. Please contact the creator
==> default: of the provider you use to fix this.
==> default: Uploading base box image as volume into libvirt storage...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:          test-vagrant_default
==> default:  -- Domain type:   kvm
==> default:  -- Cpus:          1
==> default:  -- Memory:        512M
==> default:  -- Base box:      vagrant-rhel-server-6-x86_64
==> default:  -- Storage pool:  default
==> default:  -- Image:         /var/lib/libvirt/images/test-vagrant_default.img
==> default:  -- Volume Cache:  default
==> default:  -- Kernel:        
==> default:  -- Initrd:        
==> default:  -- Command line : 
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
/root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/prune_nfs_exports.rb:18:in `call': undefined method `nfs_prune' for #<Vagrant::Host:0x0000000245b530> (NoMethodError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:34:in `call'
    from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/forward_ports.rb:137:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:34:in `call'
    from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/connect_libvirt.rb:19:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/runner.rb:69:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/runner.rb:69:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/builtin/call.rb:51:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/runner.rb:69:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/runner.rb:69:in `run'
    from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/wait_till_up.rb:90:in `terminate'
    from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.15/lib/vagrant-libvirt/action/wait_till_up.rb:81:in `recover'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:67:in `block in recover'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:64:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:64:in `recover'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/builtin/call.rb:62:in `recover'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:67:in `block in recover'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:64:in `each'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:64:in `recover'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:53:in `rescue in call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/warden.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/runner.rb:69:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/action/runner.rb:69:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/machine.rb:157:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.5.3/lib/vagrant/batch_action.rb:72:in `block (2 levels) in run'
```

If I open up virt-manager and look at the new virtual machine console, I can see that for some reason when I run `ifconfig` that the interface `eth1` now exists and there is no `eth0`. When I created the initial machine image it was happily running with `eth0` and has the script `/etc/sysconfig/network-scripts/ifcfg-eth0`:

```
DEVICE=eth0
HWADDR=52:54:00:17:67:95
TYPE=Ethernet
UUID=a450244f-f93b-494d-b952-7cc96095850d
ONBOOT=yes
NM_CONTROLLED=yes
BOOTPROTO=dhcp
```

Could this be something conflicting with what vagrant/vagrant-libvirt expects in the network configuration. e.g. that the MAC address has changed from the base-box to the new vagrant box?

**Comment by Shumakriss** [comment]
I hit this gotcha with RHEL too. I think it's a RHEL 6 thing. Do you know if that has changed in RHEL 7 or if there are any guides for provisioning with RHEL that mention that potential hang up?

**Comment by SaimonL** [comment]
Thank you adamretter. Your solution works for me however for additional network adapter this becomes a problem once again. I switched to Debian and Ubuntu server and I no longer have any issues.

**Comment by AlexBaranowski** [comment]
According to my personal experience restarting vagrant-libvirt network (In virt-manager -> Edit Connection details) may help. Refreshing the storage in same window (virt-manager -> edit -> Storage) can also magically help :smile_cat:.
