### ISSUE TITLE
Cannot install on Archlinux

### ISSUE THREAD

**Issue by arcenik** [vagrant-libvirt/vagrant-libvirt#1824]
**Describe the bug**

On Archlinux the installation of the vagrant-libvirt plugin fails.

**To Reproduce**

```
$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
/usr/lib/ruby/3.0.0/rubygems/resolver/conflict.rb:47:in `conflicting_dependencies': undefined method `request' for nil:NilClass (NoMethodError)
        from /usr/lib/ruby/3.0.0/rubygems/exceptions.rb:61:in `conflicting_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/exceptions.rb:55:in `initialize'
        from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `exception'
        from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `raise'
        from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:193:in `rescue in resolve'
        from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:191:in `resolve'
        from /usr/lib/ruby/3.0.0/rubygems/request_set.rb:411:in `resolve'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/bundler.rb:604:in `internal_install'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/bundler.rb:358:in `install'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/plugin/manager.rb:141:in `block in install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/plugin/manager.rb:151:in `install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/action/install_gem.rb:33:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builder.rb:183:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/base.rb:17:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/install.rb:73:in `block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/install.rb:72:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/install.rb:72:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/root.rb:69:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/cli.rb:67:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/environment.rb:319:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/bin/vagrant:248:in `<main>'
/usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:317:in `raise_error_unless_state': Unable to satisfy the following requirements: (Gem::Resolver::Molinillo::VersionConflict)

- `facter (= 3.14.24)` required by `user-specified dependency`
- `facter (> 2.0.1, < 5)` required by `puppet-7.31.0`
        from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
        from <internal:kernel>:90:in `tap'
        from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
        from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:682:in `attempt_to_activate'
        from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
        from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
        from /usr/lib/ruby/3.0.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
        from /usr/lib/ruby/3.0.0/rubygems/resolver.rb:190:in `resolve'
        from /usr/lib/ruby/3.0.0/rubygems/request_set.rb:411:in `resolve'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/bundler.rb:604:in `internal_install'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/bundler.rb:358:in `install'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/plugin/manager.rb:141:in `block in install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/plugin/manager.rb:151:in `install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/action/install_gem.rb:33:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/warden.rb:38:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/builder.rb:183:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/util/busy.rb:22:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/action/runner.rb:104:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/base.rb:17:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/install.rb:73:in `block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/install.rb:72:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/install.rb:72:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/commands/plugin/command/root.rb:69:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/cli.rb:67:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/lib/vagrant/environment.rb:319:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/bin/vagrant:248:in `<main>'
```

**Expected behavior**

The plugin installation should work

**Versions (please complete the following information):**:
- Libvirt version: libvirt 1:10.5.0-1 / ruby-libvirt 0.8.3-3
- Vagrant version [output of `vagrant version`]: 2.4.1
- Vagrant flavour [Upstream or Distro]: Archlinux
- Vagrant plugins versions (including vagrant-libvirt) [output of `vagrant plugin list`]: no plugin installed

**Debug Log**

[vagrant-libvirt-install.log](https://github.com/user-attachments/files/16265070/vagrant-libvirt-install.log)

**Comment by arcenik** [comment]
As I have the same error for any Vagrant plugin, I've opened an issue here https://github.com/hashicorp/vagrant/issues/13476
