### ISSUE TITLE
duplicate or stale arp table entries can confuse WaitTillUp

### ISSUE THREAD

**Issue by electrofelix** [vagrant-libvirt/vagrant-libvirt#438]
With some of the changes for #428 I could start to see another bug that I believe was mostly hidden but occurs occasionally. This is where an exception is thrown in vagrant's communicate.ready? due to a [] access on a nilClass:

```
Any errors that occurred are shown below.

An unexpected error occurred when executing the action on the
'm3' machine. Please report this as a bug:

undefined method `[]' for nil:NilClass

/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/communicators/ssh/communicator.rb:148:in `ready?'
/home/<user>/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30.42/lib/vagrant-libvirt/action/wait_till_up.rb:62:in `block (2 levels) in call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/retryable.rb:17:in `retryable'
/home/<user>/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30.42/lib/vagrant-libvirt/action/wait_till_up.rb:54:in `block in call'
.....
```

And with the fixes to the logging I would finally see the error occur with the following captured:

```
 INFO wait_till_up: Got IP address 192.168.121.63
 INFO wait_till_up: Got IP address 192.168.121.183
 INFO wait_till_up: Got IP address 192.168.121.140
 INFO wait_till_up: Got IP address 192.168.121.140
 INFO wait_till_up: Got IP address 192.168.121.42
 INFO wait_till_up: Got IP address 192.168.121.55
 INFO wait_till_up: Got IP address 192.168.121.112
```

Since subsequently I only had 6 machines running out of 7, it appears one of them gets an address that doesn't belong to the machine. This looks like libvirt can recycle mac addresses which may have stale entries in the arp table and this results in getting 

I believe this allows the initial block in WaitTillUp at https://github.com/pradels/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/wait_till_up.rb#L30-L45 to find an address, but then the subsequent block https://github.com/pradels/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/wait_till_up.rb#L52-L66 fails because the following block of code in vagrant:

```
        # If we're already attempting to switch out the SSH key, then
        # just return that we're ready (for Machine#guest).
        @lock.synchronize do
          return true if @inserted_key || !@machine.config.ssh.insert_key
          @inserted_key = true
        end

        # If we used a password, then insert the insecure key
        ssh_info = @machine.ssh_info
        insert   = ssh_info[:password] && ssh_info[:private_key_path].empty?
```

blows up because after a while the entry in the arp cache disappears and subsequent calls to ssh_info return nil instead. It seems it's just a timing issue, and that it's only if it gets past a preceding call to `connect` which does some checking on whether it is nil or not can it manage to hit this. I see it about 1 in 30 runs.

I'm wondering if there is anything that we can do to ensure that the address returned is valid and actually for the target machine and not a stale entry? Guess we could add additional commands to check that we only have one ip address returned?

Using fping might work, but seems likely it would be prone to issues around firewalls in boxes dropping icmp requests?

I'm not sure what else can be done here. I'll look to get more debug on when this occurs and add some additional statements to see what comes out.

One possibility might to switch the ip_command to the following:

```
ip neighbor show | awk "/$mac/ {print \$1}"
```

which seems to exclude mac addresses for entries that are not reachable or failed.

If we could before bringing up any domains, look to execute just once `fping` to update the entire arp cache for the default network that would work, but it does seem a little difficult to ensure that fog-libvirt will execute that just once.

Possibly also look at executing as part of the ip_command sent to fog-libvirt

```
arping -q -c 1 -I <network_device> <address_from_search>
```

and only echoing the address if the exit code is 0.

**Comment by electrofelix** [comment]
This is resolved with the switch to using net_dhcp_leases API in libvirt, though to support retrieving public IP address, may need to revisit to implement this locally in some cases.
