### ISSUE TITLE
"vagrant up" destroys VM

### ISSUE THREAD

**Issue by varac** [vagrant-libvirt/vagrant-libvirt#456]
i experience this annoying behaviour from time to time since a while, and am not sure if i should open the issue here or in the vagrant issue tracker itself.

```
--- git/leap_platform ‹develop› » vagrant status
Current machine states:

node1                     shutoff (libvirt)

The Libvirt domain is not running. Run `vagrant up` to start it.

--- git/leap_platform ‹develop› » vagrant up
Bringing machine 'node1' up with 'libvirt' provider...
==> node1: Starting domain.
==> node1: Waiting for domain to get an IP address...
==> node1: Waiting for SSH to become available...
==> node1: Creating shared folders metadata...
==> node1: Removing domain...
/home/varac/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:44:in `connect': no implicit conversion of Array into String (TypeError)
    from /home/varac/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:44:in `block in read_host_ip'
    from /home/varac/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:43:in `open'
    from /home/varac/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:43:in `read_host_ip'
    from /home/varac/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:23:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/varac/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/forward_ports.rb:30:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/varac/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/wait_till_up.rb:73:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/varac/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/start_domain.rb:26:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/varac/.vagrant.d/gems/gems/vagrant-proxyconf-1.5.1/lib/vagrant-proxyconf/action/only_once.rb:21:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folders.rb:84:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/varac/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/varac/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/create_networks.rb:77:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/varac/.vagrant.d/gems/gems/vagrant-proxyconf-1.5.1/lib/vagrant-proxyconf/action/only_once.rb:21:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/varac/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/varac/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/varac/.vagrant.d/gems/gems/vagrant-triggers-0.5.2/lib/vagrant-triggers/action/trigger.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/varac/.vagrant.d/gems/gems/vagrant-triggers-0.5.2/lib/vagrant-triggers/action/trigger.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /home/varac/.vagrant.d/gems/gems/vagrant-triggers-0.5.2/lib/vagrant-triggers/action/trigger.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

--- git/leap_platform ‹develop› » vagrant status     
Current machine states:

node1                     not created (libvirt)

The Libvirt domain is not created. Run `vagrant up` to create it.

--- git/leap_platform ‹develop› » virsh list --all | grep node1

--- git/leap_platform ‹develop› » vagrant --version
Vagrant 1.7.2

--- git/leap_platform ‹develop› » vagrant plugin list
fog (1.34.0)
sahara (0.0.17)
vagrant-libvirt (0.0.30)
vagrant-mutate (1.0.2)
vagrant-proxyconf (1.5.1)
vagrant-share (1.1.4, system)
vagrant-triggers (0.5.2)

```

@pradels: any idea what's causing this ? 
Problem is that i cannot reproduce this, it just happens randomly from time to time...

**Comment by varac** [comment]
damn, had a machine destroyed again today :( same output as above

**Comment by electrofelix** [comment]
I've yet to properly test, but it seems that https://github.com/electrofelix/vagrant-libvirt/tree/support-no-destroy might help it tracking this down.

Once I've confirmed no obvious side effects I'll submit the PR.

**Comment by varac** [comment]
awesome, thx!

**Comment by varac** [comment]
@electrofelix did you tested already ? i just had another VM destroyed and would be very happy for a PR !

**Comment by varac** [comment]
@pronix @electrofelix any update on this ? i'm a bit desperate because i'm loosing a VM every other day at the moment, and bringing it to the state where i can start again takes roughly half an hour of a puppetrun each time :/

@electrofelix if you can explain me how i could use your branch i'm happy to test, but right now i don't know how i would do this.

**Comment by electrofelix** [comment]
@varac I've been trying to get to write some spec tests to ensure the behaviour remains as expected, for the most part it appears working to me.

You should be able to download the patch from https://github.com/electrofelix/vagrant-libvirt/commit/9691efec2e1005b8fdcb0fb158195fb642a932f1.patch and apply it directly to your installed plugin with the following commands:

```
cd ~/Downloads
wget https://github.com/electrofelix/vagrant-libvirt/commit/9691efec2e1005b8fdcb0fb158195fb642a932f1.patch
cd ~/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30
patch -p1 -i ~/Downloads/9691efec2e1005b8fdcb0fb158195fb642a932f1.patch
```

Obviously if you reinstall the plugin or upgrade the fix disappears.

**Comment by electrofelix** [comment]
Gotten some spec tests to exercise some of the code ready, and I think that it also shows that the existing code should not call terminate when it detects that env[:interrupt] has been set and instead should just return and let the middleware warden handle triggering the recover call chain.

https://github.com/pradels/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/wait_till_up.rb#L46

But would like @pradels to comment on the area as it comes from the initial commit and it is a little more difficult to exercise the vagrant warden API to confirm that recover is called as expected.

**Comment by electrofelix** [comment]
Looks like https://github.com/electrofelix/vagrant-libvirt/tree/respect-destroy-on-error fixes this issue and I've done some testing and discovered that still need to call terminate.

That appears to be due to the line
```
    return if env["vagrant.error"].is_a?(Vagrant::Errors::VagrantError)
```
at https://github.com/electrofelix/vagrant-libvirt/blob/respect-destroy-on-error/lib/vagrant-libvirt/action/wait_till_up.rb#L79, which actually looks a little suspect to me, since just about every exception will be a subclass of VagrantError. Perhaps it should be ignored in this case, however for now I've defaulted to leaving it in place until I've a chance to poke the vagrant devs to ask about it.

**Comment by infernix** [comment]
@electrofelix any ideas on this? will mark as bug for now?

**Comment by mkhon** [comment]
The problem is that WaitTillUp is used in both domain creation and domain startup (action_start).
In the latter case (existing domain start) if start fails for some reason or is interrupted by the user WaitTillUp destroys the domain.

See #787 for the proposed fix

**Comment by bigbigbanana** [comment]
@electrofelix 
Hello,when i run vagrant up --provider=libvirt,i got the following error and when i run this command again,it seems to be right,but vagrant reload still have problem,what's wrong with it?
![2017-07-12 10-42-58](https://user-images.githubusercontent.com/24928429/28105764-721e1f2e-6713-11e7-941a-b10a41e01573.png)

**Comment by electrofelix** [comment]
@bigbigbanana that's a different issue, the problem there is that when there is a failure creating the domain, the disk image created is not getting removed as part of the cleanup.

**Comment by electrofelix** [comment]
Believe #787 resolved the problem with some error on starting an existing machine destroying it if it encountered and error. Possibly that means there is still another error to be resolved, but will have to be dealt with in a separate issue (if not already) so that it can be isolated.
