### ISSUE TITLE
Problem with uninstall on Fedora 20

### ISSUE THREAD

**Issue by utahcon** [vagrant-libvirt/vagrant-libvirt#479]
Linux laptop.zulily 3.19.8-100.fc20.x86_64 #1 SMP Tue May 12 17:08:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Vagrant 1.6.5

```
[adbarrett@laptop uwclass]$ vagrant plugin uninstall vagrant-libvirt
Uninstalling the 'vagrant-libvirt' plugin...
/usr/share/gems/gems/vagrant-1.6.5/lib/vagrant/plugin/manager.rb:123:in `uninstall_plugin': undefined method `has_plugin?' for nil:NilClass (NoMethodError)
	from /usr/share/gems/gems/vagrant-1.6.5/plugins/commands/plugin/action/uninstall_plugin.rb:18:in `call'
	from /usr/share/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/gems/gems/vagrant-1.6.5/plugins/commands/plugin/action/plugin_exists_check.rb:20:in `call'
	from /usr/share/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/gems/gems/vagrant-1.6.5/plugins/commands/plugin/command/base.rb:14:in `action'
	from /usr/share/gems/gems/vagrant-1.6.5/plugins/commands/plugin/command/uninstall.rb:21:in `block in execute'
	from /usr/share/gems/gems/vagrant-1.6.5/plugins/commands/plugin/command/uninstall.rb:20:in `each'
	from /usr/share/gems/gems/vagrant-1.6.5/plugins/commands/plugin/command/uninstall.rb:20:in `execute'
	from /usr/share/gems/gems/vagrant-1.6.5/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /usr/share/gems/gems/vagrant-1.6.5/lib/vagrant/cli.rb:42:in `execute'
	from /usr/share/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:301:in `cli'
	from /usr/share/gems/gems/vagrant-1.6.5/bin/vagrant:176:in `<main>'
```

**Comment by electrofelix** [comment]
that looks to be a problem with vagrant itself, rather than the plugin.

**Comment by infernix** [comment]
I'm closing this since the vagrant version is rather old and this indeed does look like a vagrant issue. Feel free to reopen if the issue persists!
