### ISSUE TITLE
Vagrant up fails when using libvirt.uri option.

### ISSUE THREAD

**Issue by italiahardik** [vagrant-libvirt/vagrant-libvirt#512]
Vagrant up fails when using libvirt.uri option.

Vagrantfile config
```
config .vm.define :ctl do |ctl|
      ctl.vm.box = "ubuntu-14.04-amd64"
      ctl.vm.provision :shell do |s|
          s.inline = "sudo bash /vagrant/bootstrap.sh"
      end
      ctl.vm.provider :libvirt do |libvirt|
          ibvirt.uri = "qemu+ssh://sdn@192.168.1.1/system"
      end
  end
```
Error:
```
$ vagrant up ctl
Bringing machine 'ctl' up with 'libvirt' provider...
==> ctl: Creating image (snapshot of base box volume).
==> ctl: Creating domain with the following settings...
==> ctl:  -- Name:              stack_ctl
==> ctl:  -- Domain type:       kvm
==> ctl:  -- Cpus:              1
==> ctl:  -- Memory:            512M
==> ctl:  -- Management MAC:
==> ctl:  -- Loader:
==> ctl:  -- Base box:          ubuntu-14.04-amd64
==> ctl:  -- Storage pool:      default
==> ctl:  -- Image:             /var/lib/libvirt/images/stack_ctl.img (40G)
==> ctl:  -- Volume Cache:      default
==> ctl:  -- Kernel:
==> ctl:  -- Initrd:
==> ctl:  -- Graphics Type:     vnc
==> ctl:  -- Graphics Port:     5900
==> ctl:  -- Graphics IP:       127.0.0.1
==> ctl:  -- Graphics Password: Not defined
==> ctl:  -- Video Type:        cirrus
==> ctl:  -- Video VRAM:        9216
==> ctl:  -- Keymap:            en-us
==> ctl:  -- INPUT:             type=mouse, bus=ps2
==> ctl:  -- Command line :
==> ctl: Creating shared folders metadata...
==> ctl: Starting domain.
==> ctl: Waiting for domain to get an IP address...
==> ctl: Removing domain...
==> ctl: Running cleanup tasks for 'shell' provisioner...
/home/sdn/.vagrant.d/gems/gems/fog-core-1.35.0/lib/fog/core/ssh.rb:47:in `initialize': :key_data, :keys, :password or a loaded ssh-agent is required to initialize SSH (ArgumentError)
        from /home/sdn/.vagrant.d/gems/gems/fog-core-1.35.0/lib/fog/core/ssh.rb:9:in `new'
        from /home/sdn/.vagrant.d/gems/gems/fog-core-1.35.0/lib/fog/core/ssh.rb:9:in `new'
        from /home/sdn/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/models/compute/server.rb:286:in `addresses'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/wait_till_up.rb:39:in `block (3 levels) in call'
        from /home/sdn/.vagrant.d/gems/gems/fog-core-1.35.0/lib/fog/core/model.rb:72:in `instance_eval'
        from /home/sdn/.vagrant.d/gems/gems/fog-core-1.35.0/lib/fog/core/model.rb:72:in `block in wait_for'
        from /home/sdn/.vagrant.d/gems/gems/fog-core-1.35.0/lib/fog/core/wait_for.rb:7:in `block in wait_for'
        from /home/sdn/.vagrant.d/gems/gems/fog-core-1.35.0/lib/fog/core/wait_for.rb:6:in `loop'
        from /home/sdn/.vagrant.d/gems/gems/fog-core-1.35.0/lib/fog/core/wait_for.rb:6:in `wait_for'
        from /home/sdn/.vagrant.d/gems/gems/fog-core-1.35.0/lib/fog/core/model.rb:69:in `wait_for'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/wait_till_up.rb:38:in `block (2 levels) in call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/retryable.rb:17:in `retryable'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/wait_till_up.rb:33:in `block in call'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/util/timer.rb:9:in `time'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/wait_till_up.rb:31:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/start_domain.rb:188:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/set_boot_order.rb:60:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/create_network_interfaces.rb:138:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/create_networks.rb:79:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/share_folders.rb:20:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:18:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:86:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/create_domain.rb:201:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/create_domain_volume.rb:51:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/handle_box_image.rb:109:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/handle_storage_pool.rb:50:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /home/sdn/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

$ vagrant version
Installed Version: 1.7.4
Latest Version: 1.7.4

You're running an up-to-date version of Vagrant!
 
$vagrant plugin list
vagrant-libvirt (0.0.32)
vagrant-mutate (1.0.3)
vagrant-share (1.1.4, system)

Workaround: Instead of using libvir.uri use other options to connect to libvirt like, libvirt.driver,libvirt.host, libvirt.username, libvirt,password and libvirt.connerct_via_ssh

**Comment by 14msitaqadeer** [comment]
could u please explain how to use that workaround...i am new on vagrant

**Comment by italiahardik** [comment]
I used following options instead of libvirt.uri.

libvirt.host = "192.168.1.1"
libvirt.username = "admin"
libvirt.password = "password"

**Comment by 14msitaqadeer** [comment]
thanks :)

**Comment by anukm** [comment]
Is there any way to get libvirt uri to work ?

I am able to connect libvirt uri over virsh using ssh but when I use vagrant it returns the same error.
**/home/username/.vagrant.d/gems/gems/fog-core-1.35.0/lib/fog/core/ssh.rb:47:in `initialize': :key_data, :keys, :password or a loaded ssh-agent is required to initialize SSH (ArgumentError)**

here's my provider settings :

 config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.connect_via_ssh = true
    libvirt.uri = 'qemu+ssh://username@myhost.com/system'
    libvirt.username = "username"
    libvirt.id_ssh_key_file  = "id_dsa"
  end


Thanks

**Comment by infernix** [comment]
The only supported way to use remote libvirt is by using `connect_via_ssh` - otherwise we cannot at this point determine a VMs IP.

With ssh-agent running and ssh keys in place, I had no problem using the following:

```ruby
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
Vagrant.configure(2) do |config|

  config.vm.define :ctl do |ctl|
      ctl.vm.box = "centos/7"
      ctl.vm.provider :libvirt do |libvirt|
	libvirt.driver = "kvm"
	libvirt.host = "192.168.0.1"
	libvirt.connect_via_ssh = true
	libvirt.username = "root"
      end
  end
end
```

**Do not specify libvirt.uri together with the rest!** As stated in the docs, this overrides all the other config options. You do not want that. Also, if you use ssh-agent, you do not need to specify the key file.
