### ISSUE TITLE
Volume for domain is already created. Please run 'vagrant destroy' first.

### ISSUE THREAD

**Issue by cmoulliard** [vagrant-libvirt/vagrant-libvirt#559]
I can't create a new VM machine even if I run the command vagrant destroy. 
How can we avoid such error "Volume for domain is already created' ?

```
VAGRANT_LOG=info  vagrant up --provider=libvirt libvirt
 INFO global: Vagrant version: 1.8.1
 INFO global: Ruby version: 2.2.3
 INFO global: RubyGems version: 2.4.5.1
 INFO global: VAGRANT_LOG="info"
 INFO global: VAGRANT_OLD_ENV_MODULESHOME="/usr/share/Modules"
 INFO global: VAGRANT_OLD_ENV_BASH_FUNC_scl()="() {  local CMD=$1;\n if [ \"$CMD\" = \"load\" -o \"$CMD\" = \"unload\" ]; then\n eval \"module $@\";\n else\n /usr/bin/scl \"$@\";\n fi\n}"
 INFO global: VAGRANT_OLD_ENV_M2="/opt/apache-maven-3.2.3/bin"
 INFO global: VAGRANT_OLD_ENV_QTDIR="/usr/lib64/qt-3.3"
 INFO global: VAGRANT_OLD_ENV_PATH="/home/dabou/.rbenv/shims:/home/dabou/.rbenv/bin:/usr/lib64/qt-3.3/bin:/opt/apache-maven-3.2.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/dabou/openshift-origin-client-tools-v1.1.0.1-bf56e23-linux-64bit:/home/dabou/openshift-origin-server-v1.1.0.1-bf56e23-linux-64bit:/home/dabou/Software:/home/dabou/Software/android-sdk-linux/tools:/home/dabou/Software/android-sdk-linux/platform-tools"
 INFO global: VAGRANT_OLD_ENV_JAVA_HOME="/opt/jdk1.8.0_45/"
 INFO global: VAGRANT_OLD_ENV_HISTCONTROL="ignoredups"
 INFO global: VAGRANT_OLD_ENV_SHLVL="2"
 INFO global: VAGRANT_OLD_ENV_LC_ALL="en_US.UTF-8"
 INFO global: VAGRANT_OLD_ENV_MAIL="/var/spool/mail/dabou"
 INFO global: VAGRANT_OLD_ENV_HOME="/home/dabou"
 INFO global: VAGRANT_OLD_ENV_SSH_CLIENT="192.168.1.80 52888 22"
 INFO global: VAGRANT_OLD_ENV_GUESTFISH_INIT="\\e[1;34m"
 INFO global: VAGRANT_OLD_ENV_USER="dabou"
 INFO global: VAGRANT_OLD_ENV_RBENV_SHELL="bash"
 INFO global: VAGRANT_OLD_ENV_QTLIB="/usr/lib64/qt-3.3/lib"
 INFO global: VAGRANT_OLD_ENV_LESSOPEN="|/usr/bin/lesspipe.sh %s"
 INFO global: VAGRANT_OLD_ENV_GUESTFISH_PS1="\\[\\e[1;32m\\]><fs>\\[\\e[0;31m\\] "
 INFO global: VAGRANT_OLD_ENV_PWD="/home/dabou/Repos/OPEN_virtual/base/vagrant/fuse-dev"
 INFO global: VAGRANT_OLD_ENV_OPENSHIFTCLIENT="/home/dabou/openshift-origin-client-tools-v1.1.0.1-bf56e23-linux-64bit"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/embedded"
 INFO global: VAGRANT_OLD_ENV_SHELL="/bin/bash"
 INFO global: VAGRANT_OLD_ENV_VAGRANT_LOG="info"
 INFO global: VAGRANT_OLD_ENV_GUESTFISH_OUTPUT="\\e[0m"
 INFO global: VAGRANT_OLD_ENV_M2_HOME="/opt/apache-maven-3.2.3"
 INFO global: VAGRANT_OLD_ENV_ANDROID_HOME="/home/dabou/Software/android-sdk-linux"
 INFO global: VAGRANT_OLD_ENV_LANG="en_US.UTF-8"
 INFO global: VAGRANT_OLD_ENV_SSH_CONNECTION="192.168.1.80 52888 192.168.1.85 22"
 INFO global: VAGRANT_OLD_ENV_SELINUX_ROLE_REQUESTED=""
 INFO global: VAGRANT_OLD_ENV_SOFTWARE="/home/dabou/Software"
 INFO global: VAGRANT_OLD_ENV_XDG_RUNTIME_DIR="/run/user/1000"
 INFO global: VAGRANT_OLD_ENV_LC_CTYPE="utf-8"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_OLD_ENV_SSH_TTY="/dev/pts/0"
 INFO global: VAGRANT_OLD_ENV_LOGNAME="dabou"
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant"
 INFO global: VAGRANT_OLD_ENV_XDG_SESSION_ID="7"
 INFO global: VAGRANT_OLD_ENV_QTINC="/usr/lib64/qt-3.3/include"
 INFO global: VAGRANT_OLD_ENV_LS_COLORS="rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;05;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.m4a=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.oga=38;5;45:*.opus=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:"
 INFO global: VAGRANT_OLD_ENV__="/opt/vagrant/bin/vagrant"
 INFO global: VAGRANT_OLD_ENV_LOADEDMODULES=""
 INFO global: VAGRANT_OLD_ENV_QT_GRAPHICSSYSTEM_CHECKED="1"
 INFO global: VAGRANT_OLD_ENV_SELINUX_LEVEL_REQUESTED=""
 INFO global: VAGRANT_OLD_ENV_OPENSHIFT="/home/dabou/openshift-origin-server-v1.1.0.1-bf56e23-linux-64bit"
 INFO global: VAGRANT_OLD_ENV_TERM="xterm-256color"
 INFO global: VAGRANT_OLD_ENV_SSH_ASKPASS="/usr/libexec/openssh/gnome-ssh-askpass"
 INFO global: VAGRANT_OLD_ENV_GUESTFISH_RESTORE="\\e[0m"
 INFO global: VAGRANT_OLD_ENV_SELINUX_USE_CURRENT_RANGE=""
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_OLD_ENV_HOSTNAME="localhost.localdomain"
 INFO global: VAGRANT_OLD_ENV_HISTSIZE="1000"
 INFO global: VAGRANT_OLD_ENV_MODULEPATH="/etc/scl/modulefiles:/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles"
 INFO global: VAGRANT_OLD_ENV_BASH_FUNC_module()="() {  eval `/usr/bin/modulecmd bash $*`\n}"
 INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
 INFO global: Plugins:
 INFO global:   - builder = 3.2.2
 INFO global:   - bundler = 1.10.6
 INFO global:   - excon = 0.45.4
 INFO global:   - formatador = 0.2.5
 INFO global:   - fog-core = 1.35.0
 INFO global:   - multi_json = 1.11.2
 INFO global:   - fog-json = 1.0.2
 INFO global:   - mini_portile = 0.6.0
 INFO global:   - nokogiri = 1.6.3.1
 INFO global:   - fog-xml = 0.1.2
 INFO global:   - json = 1.8.3
 INFO global:   - ruby-libvirt = 0.6.0
 INFO global:   - fog-libvirt = 0.0.3
 INFO global:   - i18n = 0.7.0
 INFO global:   - log4r = 1.1.10
 INFO global:   - micromachine = 1.1.0
 INFO global:   - mime-types = 1.25.1
 INFO global:   - rest-client = 1.6.9
 INFO global:   - vagrant-kvm = 0.1.9
 INFO global:   - vagrant-libvirt = 0.0.32
 INFO global:   - vagrant-share = 1.1.5
 INFO global:   - vagrant-vbguest = 0.11.0
 INFO manager: Registered plugin: Hyper-V provider
 INFO manager: Registered plugin: VirtualBox provider
 INFO manager: Registered plugin: docker-provider
 INFO manager: Registered plugin: plugin command
 INFO manager: Registered plugin: rdp command
 INFO manager: Registered plugin: push command
 INFO manager: Registered plugin: help command
 INFO manager: Registered plugin: provision command
 INFO manager: Registered plugin: resume command
 INFO manager: Registered plugin: ssh-config command
 INFO manager: Registered plugin: status command
 INFO manager: Registered plugin: powershell command
 INFO manager: Registered plugin: halt command
 INFO manager: Registered plugin: list-commands command
 INFO manager: Registered plugin: up command
 INFO manager: Registered plugin: port command
 INFO manager: Registered plugin: init command
 INFO manager: Registered plugin: reload command
 INFO manager: Registered plugin: version command
 INFO manager: Registered plugin: vagrant-login
 INFO manager: Registered plugin: snapshot command
 INFO manager: Registered plugin: cap command
 INFO manager: Registered plugin: destroy command
 INFO manager: Registered plugin: suspend command
 INFO manager: Registered plugin: provider command
 INFO manager: Registered plugin: global-status command
 INFO manager: Registered plugin: ssh command
 INFO manager: Registered plugin: box command
 INFO manager: Registered plugin: package command
 INFO manager: Registered plugin: Windows host
 INFO manager: Registered plugin: Mac OS X host
 INFO manager: Registered plugin: Slackware host
 INFO manager: Registered plugin: Red Hat Enterprise Linux host
 INFO manager: Registered plugin: Arch host
 INFO manager: Registered plugin: FreeBSD host
 INFO manager: Registered plugin: SUSE host
 INFO manager: Registered plugin: Gentoo host
 INFO manager: Registered plugin: Linux host
 INFO manager: Registered plugin: null host
 INFO manager: Registered plugin: BSD host
 INFO manager: Registered plugin: Windows guest.
 INFO manager: Registered plugin: NetBSD guest
 INFO manager: Registered plugin: TinyCore Linux guest.
 INFO manager: Registered plugin: Darwin guest
 INFO manager: Registered plugin: Slackware guest
 INFO manager: Registered plugin: Red Hat Enterprise Linux guest
 INFO manager: Registered plugin: Solaris guest.
 INFO manager: Registered plugin: SmartOS guest.
 INFO manager: Registered plugin: PLD Linux guest
 INFO manager: Registered plugin: OpenBSD guest
 INFO manager: Registered plugin: Mint guest
 INFO manager: Registered plugin: ESXi guest.
 INFO manager: Registered plugin: Arch guest
 INFO manager: Registered plugin: Funtoo guest
 INFO manager: Registered plugin: Debian guest
 INFO manager: Registered plugin: CoreOS guest
 INFO manager: Registered plugin: FreeBSD guest
 INFO manager: Registered plugin: SUSE guest
 INFO manager: Registered plugin: Ubuntu guest
 INFO manager: Registered plugin: VMware Photon guest
 INFO manager: Registered plugin: NixOS guest
 INFO manager: Registered plugin: Fedora guest
 INFO manager: Registered plugin: OmniOS guest.
 INFO manager: Registered plugin: Gentoo guest
 INFO manager: Registered plugin: Linux guest.
 INFO manager: Registered plugin: Solaris 11 guest.
 INFO manager: Registered plugin: Atomic Host guest
 INFO manager: Registered plugin: NFS synced folders
 INFO manager: Registered plugin: RSync synced folders
 INFO manager: Registered plugin: SMB synced folders
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: CFEngine Provisioner
 INFO manager: Registered plugin: ansible
 INFO manager: Registered plugin: file
 INFO manager: Registered plugin: shell
 INFO manager: Registered plugin: salt
 INFO manager: Registered plugin: chef
 INFO manager: Registered plugin: puppet
 INFO manager: Registered plugin: docker
 INFO manager: Registered plugin: winrm communicator
 INFO manager: Registered plugin: ssh communicator
 INFO manager: Registered plugin: atlas
 INFO manager: Registered plugin: ftp
 INFO manager: Registered plugin: local-exec
 INFO manager: Registered plugin: heroku
 INFO manager: Registered plugin: noop
 INFO manager: Registered plugin: kernel
 INFO global: Loading plugins!
 INFO manager: Registered plugin: vagrant-share
 INFO manager: Registered plugin: KVM provider
 INFO manager: Registered plugin: libvirt
 INFO manager: Registered plugin: vagrant-vbguest
 INFO vagrant: `vagrant` invoked: ["up", "--provider=libvirt", "libvirt"]
 INFO environment: Environment initialized (#<Vagrant::Environment:0x00000002fcfb50>)
 INFO environment:   - cwd: /home/dabou/Repos/OPEN_virtual/base/vagrant/fuse-dev
 INFO environment: Home path: /home/dabou/.vagrant.d
 INFO environment: Local data path: /home/dabou/Repos/OPEN_virtual/base/vagrant/fuse-dev/.vagrant
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 3 hooks defined.
 INFO runner: Running action: environment_plugins_loaded #<Vagrant::Action::Builder:0x00000002ef5770>
 INFO environment: Running hook: environment_load
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 3 hooks defined.
 INFO runner: Running action: environment_load #<Vagrant::Action::Builder:0x00000002708f08>
 INFO cli: CLI: [] "up" ["--provider=libvirt", "libvirt"]
 INFO loader: Set :root = ["#<Pathname:/home/dabou/Repos/OPEN_virtual/base/vagrant/fuse-dev/Vagrantfile>"]
 INFO loader: Loading configuration in order: [:home, :root]
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /home/dabou/Repos/OPEN_virtual/base/vagrant/fuse-dev>]
 INFO host: Detected: redhat!
 INFO environment: Getting machine: libvirt (libvirt)
 INFO environment: Uncached load of machine.
 INFO loader: Set "24941920_machine_libvirt" = ["[\"2\", #<Proc:0x00000002e9a5a0@/home/dabou/Repos/OPEN_virtual/base/vagrant/fuse-dev/Vagrantfile:99>]"]
 INFO loader: Loading configuration in order: [:home, :root, "24941920_machine_libvirt"]
 INFO box_collection: Box found: fedora23-libvirt (libvirt)
 INFO loader: Set :"24645400_fedora23-libvirt_libvirt" = ["#<Pathname:/home/dabou/.vagrant.d/boxes/fedora23-libvirt/0/libvirt/Vagrantfile>"]
 INFO loader: Loading configuration in order: [:"24645400_fedora23-libvirt_libvirt", :home, :root, "24941920_machine_libvirt"]
 INFO loader: Set :"24941920_vm_libvirt_fedora23-libvirt_libvirt" = ["[\"2\", #<Proc:0x00000002e8e200>]"]
 INFO loader: Loading configuration in order: [:"24645400_fedora23-libvirt_libvirt", :home, :root, "24941920_machine_libvirt", :"24941920_vm_libvirt_fedora23-libvirt_libvirt"]
 INFO machine: Initializing machine: libvirt
 INFO machine:   - Provider: VagrantPlugins::ProviderLibvirt::Provider
 INFO machine:   - Box: #<Vagrant::Box:0x0000000237aa58>
 INFO machine:   - Data dir: /home/dabou/Repos/OPEN_virtual/base/vagrant/fuse-dev/.vagrant/machines/libvirt/libvirt
 INFO machine: New machine ID: nil
 INFO interface: Machine: metadata ["provider", :libvirt, {:target=>:libvirt}]
 INFO command: With machine: libvirt (#<VagrantPlugins::ProviderLibvirt::Provider:0x00000002db7728 @machine=#<Vagrant::Machine: libvirt (VagrantPlugins::ProviderLibvirt::Provider)>, @cap_logger=#<Log4r::Logger:0x00000002db5bf8 @fullname="vagrant::capability_host::vagrantplugins::providerlibvirt::provider", @outputters=[], @additive=true, @name="provider", @path="vagrant::capability_host::vagrantplugins::providerlibvirt", @parent=#<Log4r::Logger:0x00000001faae50 @fullname="vagrant", @outputters=[#<Log4r::StderrOutputter:0x00000003002c80 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x00000003002c08>, @name="stderr", @level=0, @formatter=#<Log4r::DefaultFormatter:0x00000002f67668 @depth=7>, @out=#<IO:<STDERR>>>], @additive=true, @name="vagrant", @path="", @parent=#<Log4r::RootLogger:0x00000001faab80 @level=0, @outputters=[]>, @level=2, @trace=false>, @level=2, @trace=false>, @cap_host_chain=[[:libvirt, #<#<Class:0x00000002db7480>:0x00000002d99a20>]], @cap_args=[#<Vagrant::Machine: libvirt (VagrantPlugins::ProviderLibvirt::Provider)>], @cap_caps={:hyperv=>#<Vagrant::Registry:0x00000002db6d50 @items={:public_address=>#<Proc:0x00000002da7af8@/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/hyperv/plugin.rb:25>}, @results_cache={}>, :virtualbox=>#<Vagrant::Registry:0x00000002db6be8 @items={:forwarded_ports=>#<Proc:0x00000002d9c658@/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/plugin.rb:27>, :nic_mac_addresses=>#<Proc:0x00000002d9c450@/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/plugin.rb:32>, :public_address=>#<Proc:0x00000001fe55a0@/opt/vagrant/embedded/gems/gems/vagrant-share-1.1.5/lib/vagrant-share.rb:39>, :snapshot_list=>#<Proc:0x00000002d9c3d8@/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/plugin.rb:42>}, @results_cache={}>, :docker=>#<Vagrant::Registry:0x00000002db6918 @items={:public_address=>#<Proc:0x0000000272e050@/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/docker/plugin.rb:54>, :proxy_machine=>#<Proc:0x0000000272dee8@/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/docker/plugin.rb:59>}, @results_cache={}>, :libvirt=>#<Vagrant::Registry:0x00000002db5fb8 @items={:nic_mac_addresses=>#<Proc:0x0000000301cd88@/home/dabou/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/plugin.rb:41>}, @results_cache={}>}>)
 INFO interface: info: Bringing machine 'libvirt' up with 'libvirt' provider...
Bringing machine 'libvirt' up with 'libvirt' provider...
 INFO batch_action: Enabling parallelization by default.
 INFO batch_action: Disabling parallelization because only executing one action
 INFO batch_action: Batch action will parallelize: false
 INFO batch_action: Starting action: #<Vagrant::Machine:0x00000002e4a280> up {:destroy_on_error=>true, :install_provider=>true, :parallel=>true, :provision_ignore_sentinel=>false, :provision_types=>nil, :provider=>"libvirt"}
 INFO machine: Calling action: up on provider Libvirt (new)
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-3ea2ecaa7305624ebf25c2bf96ec277b
 INFO interface: Machine: action ["up", "start", {:target=>:libvirt}]
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 3 hooks defined.
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Builder:0x000000022e5408>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x000000030013d0>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Call:0x00000003001380>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 3 hooks defined.
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Builder:0x00000002fa77e0>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::IsCreated:0x00000002f9ea78>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::IsCreated:0x00000002f9ea78>
 INFO driver: Connecting to Libvirt (qemu:///system?no_verify=1&keyfile=/home/dabou/.ssh/id_rsa) ...
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 3 hooks defined.
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Warden:0x007faab4537be8>
 INFO warden: Calling IN action: #<Proc:0x007faab46793d0@/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:94 (lambda)>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::SetNameOfDomain:0x007faab4537b70>
 INFO set_name_of_domain: Looking for domain fuse-dev_libvirt through list []
 INFO set_name_of_domain: Looking for domain fuse-dev_libvirt
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::HandleStoragePool:0x00000002f16240>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::HandleBox:0x007faab4586a18>
 INFO handle_box: Machine already has box. HandleBox will not run.
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::HandleBoxImage:0x007faab45b0a98>
 INFO interface: info: Created volume larger than box defaults, will require manual resizing of
filesystems to utilize.
 INFO interface: info: ==> libvirt: Created volume larger than box defaults, will require manual resizing of
==> libvirt: filesystems to utilize.
==> libvirt: Created volume larger than box defaults, will require manual resizing of
==> libvirt: filesystems to utilize.
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CreateDomainVolume:0x007faab45e7d40>
 INFO interface: info: Creating image (snapshot of base box volume).
 INFO interface: info: ==> libvirt: Creating image (snapshot of base box volume).
==> libvirt: Creating image (snapshot of base box volume).
ERROR warden: Error occurred: Volume for domain is already created. Please run 'vagrant destroy' first.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Volume for domain is already created. Please run 'vagrant destroy' first.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Volume for domain is already created. Please run 'vagrant destroy' first.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000003001380>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-3ea2ecaa7305624ebf25c2bf96ec277b
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 3 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x007faab43a7f58>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::ProviderLibvirt::Errors::DomainVolumeExists: Volume for domain is already created. Please run 'vagrant destroy' first.>
ERROR vagrant: Volume for domain is already created. Please run 'vagrant destroy' first.
ERROR vagrant: /home/dabou/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/create_domain_volume.rb:30:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/home/dabou/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/handle_box_image.rb:109:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/home/dabou/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/handle_storage_pool.rb:50:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/home/dabou/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: Volume for domain is already created. Please run 'vagrant destroy' first.
Volume for domain is already created. Please run 'vagrant destroy' first.
 INFO interface: Machine: error-exit ["VagrantPlugins::ProviderLibvirt::Errors::DomainVolumeExists", "Volume for domain is already created. Please run 'vagrant destroy' first."]
```

**Comment by cmoulliard** [comment]
Problem solved after deleting the volume using virsh tool

```
virsh # vol-list default
 Name                 Path
------------------------------------------------------------------------------
 fedora23-libvirt_vagrant_box_image_0.img /var/lib/libvirt/images/fedora23-libvirt_vagrant_box_image_0.img
 fuse-dev_libvirt.img /var/lib/libvirt/images/fuse-dev_libvirt.img

virsh # vol-delete fuse-dev_libvirt.img default
```

**Comment by infernix** [comment]
If it reoccurs, please post the output of `VAGRANT_LOG=debug vagrant destroy` so we can see why it's not deleting the stale image (which it should).

**Comment by infernix** [comment]
Closing this due to no further updates/info. Please free to update or reopen this ticket if required. Thanks!
