### ISSUE TITLE
getaddrinfo error during 'vagrant up --provider=libvirt'

### ISSUE THREAD

**Issue by gtaylor** [vagrant-libvirt/vagrant-libvirt#595]
Running on Ubuntu 16.04 with:

* Linux 4.4
* libvirt 1.3.1
* vagrant 1.8.1
* Ruby 2.3.0

Here's my plugin list:

```
$ vagrant plugin list
vagrant-libvirt (0.0.33)
vagrant-share (1.1.5, system)
```

I'm attempting to start a box that I converted from: https://uec-images.ubuntu.com/releases/14.04/release/ubuntu-14.04-server-cloudimg-amd64-disk1.img

I'm not 100% positive this was the correct qemu input, so the problem may be that we're not even getting off the ground.

Here's what I'm seeing when I vagrant up with libvirt specified:
```
$ vagrant up --provider=libvirt
Bringing machine 'default' up with 'libvirt' provider...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
==> default: Removing domain...
/opt/vagrant/embedded/lib/ruby/2.2.0/socket.rb:232:in `getaddrinfo': getaddrinfo: Name or service not known (SocketError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/socket.rb:232:in `foreach'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/socket.rb:328:in `tcp'
	from /home/greg.taylor/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh/transport/session.rb:70:in `initialize'
	from /home/greg.taylor/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh.rb:225:in `new'
	from /home/greg.taylor/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh.rb:225:in `start'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:389:in `block (2 levels) in connect'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `block in catch'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:32:in `catch'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/timeout.rb:103:in `timeout'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:368:in `block in connect'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:367:in `connect'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:125:in `ready?'
	from /home/greg.taylor/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/wait_till_up.rb:66:in `block (2 levels) in call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /home/greg.taylor/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/wait_till_up.rb:58:in `block in call'
	from /home/greg.taylor/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/util/timer.rb:9:in `time'
	from /home/greg.taylor/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/wait_till_up.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/greg.taylor/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/start_domain.rb:294:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/greg.taylor/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/greg.taylor/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/set_boot_order.rb:60:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/greg.taylor/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/create_networks.rb:80:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```
I'm not at all versed in Ruby, so I'm not entirely sure where to begin debugging this. It'd be nice to be able to see what name it's trying to resolve.

Any ideas?

**Comment by infernix** [comment]
I'm not sure if this is a vagrant-libvirt issue. Can you post the output of `VAGRANT_LOG=debug vagrant up --provider=libvirt` as well as your Vagrantfile?

**Comment by gtaylor** [comment]
Ah, this is helpful. Looks like the VM may have never started:
```
==> default: Creating shared folders metadata...
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CreateNetworks:0x007faf908af8a8>
 INFO create_networks: Using vagrant-libvirt at 192.168.121.0/24 as the management network nat is the mode
DEBUG create_networks: In config found network type forwarded_port options {:guest=>15672, :host=>15672, :protocol=>"tcp", :id=>"tcp15672"}
DEBUG create_networks: In config found network type private_network options {:ip=>"192.168.56.111", :protocol=>"tcp", :id=>"0cd322ac-edeb-4fec-885f-4fd06e0448fe"}
DEBUG create_networks: In config found network type forwarded_port options {:guest=>22, :host=>2222, :host_ip=>"127.0.0.1", :id=>"ssh", :auto_correct=>true, :protocol=>"tcp"}
DEBUG create_networks: Searching for network with options {:iface_type=>:private_network, :network_name=>"vagrant-libvirt", :ip=>"192.168.121.0", :netmask=>"255.255.255.0", :dhcp_enabled=>true, :forward_mode=>"nat", :guest_ipv6=>"yes"}
DEBUG create_networks: looking up network with ip == 192.168.121.0
DEBUG create_networks: Checking that network name does not clash with ip
DEBUG create_networks: looking up network named vagrant-libvirt
DEBUG create_networks: generating name for bridge
DEBUG create_networks: looking up bridge named virbr0
DEBUG create_networks: looking up bridge named virbr1
DEBUG create_networks: found available bridge name virbr1
DEBUG create_networks: created network
 INFO create_networks: Saving information about created network vagrant-libvirt, UUID=e54dc164-a4a7-4db3-8715-62305b216be2 to file /home/greg.taylor/code/reddit/.vagrant/machines/default/libvirt/created_networks.
DEBUG create_networks: Searching for network with options {:iface_type=>:private_network, :netmask=>"255.255.255.0", :dhcp_enabled=>true, :forward_mode=>"nat", :ip=>"192.168.56.111", :protocol=>"tcp", :id=>"0cd322ac-edeb-4fec-885f-4fd06e0448fe"}
DEBUG create_networks: looking up network with ip == 192.168.56.0
DEBUG create_networks: generating name for network
DEBUG create_networks: looking up network named reddit0
DEBUG create_networks: generating name for bridge
DEBUG create_networks: looking up bridge named virbr0
DEBUG create_networks: looking up bridge named virbr1
DEBUG create_networks: looking up bridge named virbr2
DEBUG create_networks: found available bridge name virbr2
DEBUG create_networks: created network
 INFO create_networks: Saving information about created network reddit0, UUID=65958342-5f10-4ef8-a62e-5c4e2ee1205c to file /home/greg.taylor/code/reddit/.vagrant/machines/default/libvirt/created_networks.
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CreateNetworkInterfaces:0x007faf906d8778>
 INFO create_network_interfaces: Using vagrant-libvirt at 192.168.121.0/24 as the management network nat is the mode
DEBUG create_network_interfaces: In config found network type forwarded_port options {:guest=>15672, :host=>15672, :protocol=>"tcp", :id=>"tcp15672"}
DEBUG create_network_interfaces: In config found network type private_network options {:ip=>"192.168.56.111", :protocol=>"tcp", :id=>"0cd322ac-edeb-4fec-885f-4fd06e0448fe"}
DEBUG create_network_interfaces: In config found network type forwarded_port options {:guest=>22, :host=>2222, :host_ip=>"127.0.0.1", :id=>"ssh", :auto_correct=>true, :protocol=>"tcp"}
DEBUG create_network_interfaces: Adapter not specified so found slot 0
DEBUG create_network_interfaces: Found network by name
DEBUG create_network_interfaces: Adapter not specified so found slot 1
DEBUG create_network_interfaces: Found network by ip
 INFO create_network_interfaces: Creating network interface eth0 connected to network vagrant-libvirt.
 INFO create_network_interfaces: Creating network interface eth1 connected to network reddit0.
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::SetBootOrder:0x007faf906715c8>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::StartDomain:0x007faf90605030>
 INFO interface: info: Starting domain.
 INFO interface: info: ==> default: Starting domain.
==> default: Starting domain.
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::WaitTillUp:0x007faf9054c918>
DEBUG wait_till_up: Searching for IP for MAC address: 52:54:00:e8:4e:06
 INFO interface: info: Waiting for domain to get an IP address...
 INFO interface: info: ==> default: Waiting for domain to get an IP address...
==> default: Waiting for domain to get an IP address...
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO wait_till_up: Got IP address 192.168.121.103
 INFO wait_till_up: Time for getting IP: 9.13738751411438
 INFO interface: info: Waiting for SSH to become available...
 INFO interface: info: ==> default: Waiting for SSH to become available...
==> default: Waiting for SSH to become available...
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Checking key permissions: /home/greg.taylor/.vagrant.d/insecure_private_key
 INFO ssh: Attempting SSH connection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 192.168.121.103
 INFO ssh:   - Port: 22
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/home/greg.taylor/.vagrant.d/insecure_private_key"]
DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2016-04-28T15:34:56.130018 #4834] DEBUG -- net.ssh.transport.session[3fd7c8540774]: establishing connection to 192.168.121.103:22

DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO retryable: Retryable exception raised: #<Errno::ECONNREFUSED: Connection refused - connect(2) for 192.168.121.103:22>
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 192.168.121.103
 INFO ssh:   - Port: 22
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/home/greg.taylor/.vagrant.d/insecure_private_key"]
DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2016-04-28T15:34:56.133535 #4834] DEBUG -- net.ssh.transport.session[3fd7c850e60c]: establishing connection to 192.168.121.103:22
```

dmesg output:
```
[Thu Apr 28 15:34:44 2016] device virbr1-nic entered promiscuous mode
[Thu Apr 28 15:34:44 2016] virbr1: port 1(virbr1-nic) entered listening state
[Thu Apr 28 15:34:44 2016] virbr1: port 1(virbr1-nic) entered listening state
[Thu Apr 28 15:34:44 2016] virbr1: port 1(virbr1-nic) entered disabled state
[Thu Apr 28 15:34:44 2016] device virbr1-nic left promiscuous mode
[Thu Apr 28 15:34:44 2016] virbr1: port 1(virbr1-nic) entered disabled state
[Thu Apr 28 15:34:44 2016] device virbr2-nic entered promiscuous mode
[Thu Apr 28 15:34:45 2016] virbr2: port 1(virbr2-nic) entered listening state
[Thu Apr 28 15:34:45 2016] virbr2: port 1(virbr2-nic) entered listening state
[Thu Apr 28 15:34:45 2016] virbr2: port 1(virbr2-nic) entered disabled state
[Thu Apr 28 15:34:45 2016] device virbr2-nic left promiscuous mode
[Thu Apr 28 15:34:45 2016] virbr2: port 1(virbr2-nic) entered disabled state
[Thu Apr 28 15:34:45 2016] audit_printk_skb: 45 callbacks suppressed
[Thu Apr 28 15:34:45 2016] audit: type=1400 audit(1461882886.013:27): apparmor="STATUS" operation="profile_load" profile="unconfined" name="libvirt-180dc887-07e0-45e1-a1dc-420774fba071" pid=5248 comm="apparmor_parser"
[Thu Apr 28 15:34:45 2016] audit: type=1400 audit(1461882886.013:28): apparmor="STATUS" operation="profile_load" profile="unconfined" name="libvirt-180dc887-07e0-45e1-a1dc-420774fba071//qemu_bridge_helper" pid=5248 comm="apparmor_parser"
[Thu Apr 28 15:34:45 2016] device vnet0 entered promiscuous mode
[Thu Apr 28 15:34:45 2016] virbr1: port 1(vnet0) entered listening state
[Thu Apr 28 15:34:45 2016] virbr1: port 1(vnet0) entered listening state
[Thu Apr 28 15:34:45 2016] audit: type=1400 audit(1461882886.313:29): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="libvirt-180dc887-07e0-45e1-a1dc-420774fba071" pid=5308 comm="apparmor_parser"
[Thu Apr 28 15:34:45 2016] audit: type=1400 audit(1461882886.329:30): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="libvirt-180dc887-07e0-45e1-a1dc-420774fba071//qemu_bridge_helper" pid=5308 comm="apparmor_parser"
[Thu Apr 28 15:34:45 2016] device vnet1 entered promiscuous mode
[Thu Apr 28 15:34:45 2016] virbr2: port 1(vnet1) entered listening state
[Thu Apr 28 15:34:45 2016] virbr2: port 1(vnet1) entered listening state
[Thu Apr 28 15:34:45 2016] audit: type=1400 audit(1461882886.565:31): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="libvirt-180dc887-07e0-45e1-a1dc-420774fba071" pid=5376 comm="apparmor_parser"
[Thu Apr 28 15:34:45 2016] audit: type=1400 audit(1461882886.589:32): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="libvirt-180dc887-07e0-45e1-a1dc-420774fba071//qemu_bridge_helper" pid=5376 comm="apparmor_parser"
[Thu Apr 28 15:34:46 2016] kvm: zapping shadow pages for mmio generation wraparound
[Thu Apr 28 15:34:46 2016] kvm: zapping shadow pages for mmio generation wraparound
[Thu Apr 28 15:34:47 2016] virbr1: port 1(vnet0) entered learning state
[Thu Apr 28 15:34:47 2016] virbr2: port 1(vnet1) entered learning state
[Thu Apr 28 15:34:49 2016] virbr1: topology change detected, propagating
[Thu Apr 28 15:34:49 2016] virbr1: port 1(vnet0) entered forwarding state
[Thu Apr 28 15:34:49 2016] virbr2: topology change detected, propagating
[Thu Apr 28 15:34:49 2016] virbr2: port 1(vnet1) entered forwarding state


[Thu Apr 28 15:36:30 2016] virbr1: port 1(vnet0) entered disabled state
[Thu Apr 28 15:36:30 2016] device vnet0 left promiscuous mode
[Thu Apr 28 15:36:30 2016] virbr1: port 1(vnet0) entered disabled state
[Thu Apr 28 15:36:30 2016] virbr2: port 1(vnet1) entered disabled state
[Thu Apr 28 15:36:30 2016] device vnet1 left promiscuous mode
[Thu Apr 28 15:36:30 2016] virbr2: port 1(vnet1) entered disabled state
[Thu Apr 28 15:36:31 2016] audit: type=1400 audit(1461882991.795:33): apparmor="STATUS" operation="profile_remove" profile="unconfined" name="libvirt-180dc887-07e0-45e1-a1dc-420774fba071" pid=5872 comm="apparmor_parser"
```

Probably PEBCAK. Could it be an improperly built image, or is this likely config? I'm using this:

https://github.com/reddit/reddit/blob/master/Vagrantfile

with box_url commented out and box changed to a locally built qemu->libvirt converted image.

**Comment by infernix** [comment]
If SSH keeps looping like that, it can't ssh to the guest image. You may have not configured the image; does it bring up eth0 with dhcp? does it allow ssh by default? does the vagrant user exist? is the vagrant key installed? etc. 

If you need a trusty libvirt image, look over at https://atlas.hashicorp.com/boxes/search?provider=libvirt and pick one.

**Comment by gtaylor** [comment]
I'm going to go on ahead and close this since it's probably not a vagrant-libvirt issue. Will re-open if I find anything that suggests otherwise.
