### ISSUE TITLE
Call to virNetworkGetBridgeName failed: internal error: network 'main' does not have a bridge name. (Libvirt::Error)

### ISSUE THREAD

**Issue by john-prowse** [vagrant-libvirt/vagrant-libvirt#599]
### Steps to reproduce
1. Try to start libvirt machine based off a box with initial default config
2. Already have "main" network defined previously as a bridge for existing vm's
### Expected behaviour

Virtual machine successfully started
### Actual behaviour

Recieve error
/root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/util/network_util.rb:116:in `bridge_name': Call to virNetworkGetBridgeName failed: internal error: network 'main' does not have                   a bridge name. (Libvirt::Error)
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/util/network_util.rb:116:in`block in libvirt_networks'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/util/network_util.rb:85:in `each'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/util/network_util.rb:85:in`libvirt_networks'
### System configuration

**OS/Distro version:**:
Arch linux x64 
**Libvirt version:**
 1.3.4
**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 1.8.1

vagrant-libvirt (0.0.33)
vagrant-mutate (1.1.0)

**Output of `VAGRANT_LOG=debug vagrant up --provider=libvirt`**

```
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x000000023b51a8>
/root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/util/network_util.rb:116:in `bridge_name': Call to virNetworkGetBridgeName failed: internal error: network 'main' does not have a bridge name. (Libvirt::Error)
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/util/network_util.rb:116:in `block in libvirt_networks'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/util/network_util.rb:85:in `each'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/util/network_util.rb:85:in `libvirt_networks'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/create_networks.rb:48:in `block (2 levels) in call'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/create_networks.rb:36:in `each'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/create_networks.rb:36:in `block in call'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/create_networks.rb:33:in `synchronize'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.33/lib/vagrant-libvirt/action/create_networks.rb:33:in `call'

virsh net-dumpxml main
<network>
  <name>main</name>
  <uuid>xxxxx-xxx-xxx-xxx-xxxxxxxx</uuid>
  <forward dev='br0' mode='bridge'>
    <interface dev='br0'/>
  </forward>
</network>

```

**A Vagrantfile to reproduce the issue:**

```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro
Distro

**Comment by infernix** [comment]
Please add your Vagrantfile, or if you used `vagrant init` please specify the box image you used.

We use `vagrant-libvirt` as a default network name so I do not know where the network name 'main' comes from; it certainly isn't a default in the code so I suspect that this is in the Vagrantfile.

**Comment by infernix** [comment]
OK, I see the problem now. We parse all libvirt networks by default in `network_util.rb` and if this network definition is found, it fails because it does not have a `libvirt_network.bridge_name` defined.

I think the issue is in the net definition for `main`. If you follow the libvirt docs, this seems to be the way to go currently:

```xml
<network>
	<name>main</name>
	<bridge name="br0"/>
	<forward mode='bridge'/>
</network>
```

Can you re-check with this definition?

**Comment by johnp12345** [comment]
Hi, 

The suggested definition seems to get past the error! 

I suspect the original definition came from the virt-manager gui.

Thanks,

John

**Comment by choppsv1** [comment]
I've hit this error but I cannot give a bridge name as the network is actually for PCI SR-IOV VF passthrough network (i.e., there's no bridge, instead PCI VF devices are allocated to the guests). It's invalid XML to add a bridge name (which is correct as it makes no sense :)

Here's the XML for the network definition.

```
<network connections='8'>
  <name>ixgbe-passthru</name>
  <uuid>1de0576e-6834-4e4f-ad87-2c65f2472750</uuid>
  <forward mode='hostdev' managed='yes'>
    <pf dev='enp4s0f0'/>
    <address type='pci' domain='0x0000' bus='0x04' slot='0x10' function='0x0'/>
    ...
  </forward>
</network>
```

**Comment by awillis** [comment]
I am having the same issue with version 0.0.45 and the latest version of network_util.rb also does not seem to have sanity check for this type of network. It would be preferable to simply skip networks that do not have a bridge defined. Alternatively, if a network name is provided you could check only that one and ignore others.

<network>
  <name>default</name>
  <uuid>8b3b93c1-b1bf-4bbd-bc90-b599e472ad20</uuid>
  <forward mode="hostdev" managed="yes">
    <pf dev="enp12s0f1"/>
    <address type="pci" domain="0x0000" bus="0x0d" slot="0x10" function="0x1"/>
    <address type="pci" domain="0x0000" bus="0x0d" slot="0x10" function="0x5"/>
    <address type="pci" domain="0x0000" bus="0x0d" slot="0x11" function="0x1"/>
    <address type="pci" domain="0x0000" bus="0x0d" slot="0x11" function="0x5"/>
    <address type="pci" domain="0x0000" bus="0x0d" slot="0x12" function="0x1"/>
    <address type="pci" domain="0x0000" bus="0x0d" slot="0x12" function="0x5"/>
    <address type="pci" domain="0x0000" bus="0x0d" slot="0x13" function="0x1"/>
  </forward>
</network>

**Comment by tiagovdaa** [comment]
I am also having the same issue, and 'macvtap' network is to blame:

<network>
  <name>macvtap</name>
  <uuid>ae18450a-5658-464a-8925-f48b4c358805</uuid>
  <forward dev='wlxd0374588d04e' mode='bridge'>
    <interface dev='wlxd0374588d04e'/>
  </forward>
</network>

However this is the only way for my VM's  to get my home network ip. (sometimes NAT is not useful for me).

It works. 

But if I try using vagrant, I got the same error.

How can I work around this?

**Comment by bolausson** [comment]
Looks like this issue is still a problem:

`vagrant-libvirt (0.7.0, global)
`
my vagrant file:
```
#!/usr/bin/env ruby
#
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
Vagrant.configure("2") do |config|
        config.vm.provider "libvirt" do |libvirt|
                libvirt.clock_offset = "localtime"
        end

        config.vm.define "exa0c0" do |node|
                node.vm.box = "client_libvirt"
                node.vm.hostname = "testvm"

                node.ssh.username = "root"
                node.ssh.password = "SomeStrongPassword"

                node.vm.provider "libvirt" do |vbox|
                        vbox.default_prefix = "test"
                        vbox.memory = "1024"
                        vbox.cpus = "2"
                        vbox.video_vram = "128"
                        vbox.keymap = "de-de"
                        vbox.memorybacking :access, :mode => "shared"
                        vbox.nested = true
                end
        end
end
```
and the result of this is:
```
$ vagrant up
Bringing machine 'testvm1' up with 'libvirt' provider...
==> testvm1: Uploading base box image as volume into Libvirt storage...
==> testvm1: Creating image (snapshot of base box volume).
==> testvm1: Creating domain with the following settings...
==> testvm1:  -- Name:              testclustertestvm1
==> testvm1:  -- Description:       Source: /home/user/vagranttest/Vagrantfile
==> testvm1:  -- Domain type:       kvm
==> testvm1:  -- Cpus:              2
==> testvm1:  -- Feature:           acpi
==> testvm1:  -- Feature:           apic
==> testvm1:  -- Feature:           pae
==> testvm1:  -- Clock offset:      localtime
==> testvm1:  -- Memory:            1024M
==> testvm1:  -- Management MAC:    
==> testvm1:  -- Loader:            
==> testvm1:  -- Nvram:             
==> testvm1:  -- Base box:          client_libvirt
==> testvm1:  -- Storage pool:      default
==> testvm1:  -- Image():     /home/user/libvirt_storage/testclustertestvm1.img, 40G
==> testvm1:  -- Disk driver opts:  cache='default'
==> testvm1:  -- Kernel:            
==> testvm1:  -- Initrd:            
==> testvm1:  -- Graphics Type:     vnc
==> testvm1:  -- Graphics Port:     -1
==> testvm1:  -- Graphics IP:       127.0.0.1
==> testvm1:  -- Graphics Password: Not defined
==> testvm1:  -- Video Type:        cirrus
==> testvm1:  -- Video VRAM:        128
==> testvm1:  -- Video 3D accel:    false
==> testvm1:  -- Sound Type:	
==> testvm1:  -- Keymap:            de-de
==> testvm1:  -- TPM Backend:       passthrough
==> testvm1:  -- TPM Path:          
==> testvm1:  -- INPUT:             type=mouse, bus=ps2
==> testvm1: Creating shared folders metadata...
Traceback (most recent call last):
	59: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	58: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/machine.rb:201:in `action'
	57: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/machine.rb:201:in `call'
	56: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/environment.rb:614:in `lock'
	55: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/machine.rb:215:in `block in action'
	54: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/machine.rb:246:in `action_raw'
	53: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `run'
	52: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/util/busy.rb:19:in `busy'
	51: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `block in run'
	50: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builder.rb:149:in `call'
	49: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	48: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	47: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	46: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
	45: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	44: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builtin/call.rb:53:in `call'
	43: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `run'
	42: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/util/busy.rb:19:in `busy'
	41: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `block in run'
	40: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builder.rb:149:in `call'
	39: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	38: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	37: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	36: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
	35: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	34: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/handle_storage_pool.rb:63:in `call'
	33: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	32: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	31: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	30: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/handle_box_image.rb:123:in `call'
	29: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	28: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_domain_volume.rb:94:in `call'
	27: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	26: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_domain.rb:443:in `call'
	25: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	24: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builtin/provision.rb:80:in `call'
	23: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	22: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:14:in `call'
	21: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	20: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	19: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	18: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	17: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	16: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builtin/delayed.rb:19:in `call'
	15: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	14: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	13: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	12: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:21:in `call'
	11: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	10: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/share_folders.rb:22:in `call'
	 9: from /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	 8: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_networks.rb:40:in `call'
	 7: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_networks.rb:40:in `synchronize'
	 6: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_networks.rb:43:in `block in call'
	 5: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_networks.rb:43:in `each'
	 4: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_networks.rb:55:in `block (2 levels) in call'
	 3: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/util/network_util.rb:148:in `libvirt_networks'
	 2: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/util/network_util.rb:148:in `each'
	 1: from /home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/util/network_util.rb:179:in `block in libvirt_networks'
/home/user/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/util/network_util.rb:179:in `bridge_name': Call to virNetworkGetBridgeName failed: internal error: network 'macvtap-net' does not have a bridge name. (Libvirt::Error)
```

and this is the network on the host (with two VMs running)
```
$ ip link 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: dummy0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether XX brd ff:ff:ff:ff:ff:ff
3: enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether XX brd ff:ff:ff:ff:ff:ff
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: ip_vti0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
6: ip6_vti0@NONE: <NOARP> mtu 1428 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd :: permaddr XX::
7: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
8: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd :: permaddr XX::
9: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether XX brd ff:ff:ff:ff:ff:ff
10: macvtap0@enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 500
    link/ether XX brd ff:ff:ff:ff:ff:ff
11: macvtap1@enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 500
    link/ether XX brd ff:ff:ff:ff:ff:ff
12: macvlan0@enp0s31f6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether XX brd ff:ff:ff:ff:ff:ff
```

Any way to make this work?

Cheers,
Bjoern

**Comment by nochristrequired** [comment]
I'm running into this issue with an SR-IOV pool (same as someone else mentioned above).

An unexpected error occurred when executing the action on the
'node05' machine. Please report this as a bug:

> Call to virNetworkGetBridgeName failed: internal error: network 'sriov-pool1' does not have a bridge name.
> 
> /home/nickle/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/util/network_util.rb:179:in `bridge_name'
> /home/nickle/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/util/network_util.rb:179:in `block in libvirt_networks'
> /home/nickle/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/util/network_util.rb:148:in `each'
> /home/nickle/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/util/network_util.rb:148:in `libvirt_networks'
> /home/nickle/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_networks.rb:55:in `block (2 levels) in call'
> /home/nickle/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_networks.rb:43:in `each'
> /home/nickle/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_networks.rb:43:in `block in call'
> /home/nickle/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_networks.rb:40:in `synchronize'
> /home/nickle/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_networks.rb:40:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
> /home/nickle/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/create_domain.rb:443:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
> /home/nickle/.vagrant.d/gems/2.7.5/gems/vagrant-libvirt-0.7.0/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builder.rb:149:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `block in run'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/util/busy.rb:19:in `busy'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `run'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builtin/call.rb:53:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builtin/box_check_outdated.rb:31:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/builder.rb:149:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `block in run'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/util/busy.rb:19:in `busy'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `run'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/machine.rb:246:in `action_raw'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/machine.rb:215:in `block in action'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/environment.rb:614:in `lock'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/machine.rb:201:in `call'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/machine.rb:201:in `action'
> /usr/lib64/ruby/gems/2.7.0/gems/vagrant-2.2.18/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'

**Comment by electrofelix** [comment]
@nochristrequired sorry in the delayed response on this issue. I think what I'll likely need to look into how to solve is a debug log of this attached to the issue, a listing of the networks that libvirt is aware of `virsh net-list --all` and an XML dump of the problematic network `virsh net-dumpxml sriov-pool1`

As the networking is next on the list for tests and fixing I can't say when it will be fixed (I'm also on paternity leave so I have my hands full in other ways for now) as will need to add a fair amount of tests before I start modifying pieces to avoid breaking things.

Essentially as I understand vagrant-libvirt expects certain fields to exist in the XML definition, and it should be possible to manually add these to the network definition at which point the code will work as expected. However the fields should be optional for the definition based on what libvirt supports and unfortunately vagrant-libvirt doesn't handle that case.

**Comment by yannou38** [comment]
Hello,

We just installed vagrant on a build server using libvirt and sadly the problem persist and prevent us from using it, as we have multiples networks that aren't bridges on that server.

I'll share one of the problematic network here for your convenience as pointed out in the last comment of this issue:

```
<network>
  <name>processbus1</name>
  <uuid>c6559b3a-4814-42a6-a6b6-902bf44e8013</uuid>
  <forward mode='hostdev' managed='yes'>
    <address type='pci' domain='0x0000' bus='0x04' slot='0x10' function='0x0'/>
    <address type='pci' domain='0x0000' bus='0x04' slot='0x10' function='0x4'/>
    <address type='pci' domain='0x0000' bus='0x04' slot='0x11' function='0x0'/>
    <address type='pci' domain='0x0000' bus='0x04' slot='0x11' function='0x4'/>
    <address type='pci' domain='0x0000' bus='0x04' slot='0x12' function='0x0'/>
    <address type='pci' domain='0x0000' bus='0x04' slot='0x12' function='0x4'/>
  </forward>
</network>
```

**Comment by electrofelix** [comment]
@yannou38 I think there is probably enough here that I can put together some sanity checks, just hadn't been on my radar, so I'll see what I can do over the next couple of days

**Comment by electrofelix** [comment]
@yannou38 are you comfortable testing out the change in #1628 to see if it is sufficient to fix the bug for your environment?

**Comment by yannou38** [comment]
Sure ! just tell me how and i'll get to it. 
I had installed vagrant from hashicorp then executed the patching script, but i guess i have to somehow edit the source git of the plugin in vagrant to use your fork instead ? then run vagrant plugin install again

**Comment by electrofelix** [comment]
I just recently added a workflow to build gems from pull requests and save them as an artifact. I've yet to add the workflow to publish the to the pr or related issues, however you can grab it from https://github.com/vagrant-libvirt/vagrant-libvirt/actions/runs/3188690598 .

Once you unzip the file there is a gem inside that it should be possible to pass to vagrant to install locally. That might be easier than working with bundle directly as you need to be careful with the vagrant home directory which will have conflicting information as to what plugins are installed. I usually have to set it to a different path compared to using vagrant itself.

```
export VAGRANT_HOME=${HOME}/tmp/.vagrant.d
bundle exec vagrant up
```

So using the built gem might be easier

**Comment by yannou38** [comment]
Thanks for the gem ! yeah it was better to install.

Happy to report that vagrant created the VM successfully !

**Comment by yannou38** [comment]
Update @electrofelix :

I confirm again what i said earlier :
This Vagrantfile will not trigger error messages:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  # Distribution
  config.vm.box = "generic/ubuntu2004" # 20.04 LTS

  # Memory
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 4092
  end

  config.vm.define "master-node" do |master_node|
    master_node.vm.hostname = "master-node"
    #master_node.vm.network :public_network,:dev => "virbr1",:mode => "bridge",:type => "bridge"
  end
end
```

But if you uncomment the network definition then errors pop up again, so i can't say the issue is fixed. it works if the box use the default defined network, but try to search for another and it will error out.

**Comment by electrofelix** [comment]
@yannou38 try adding the following config:
```
libvirt.host_device_exclude_prefixes = ['docker', 'macvtap', 'vnet']
```

The default value excludes virbrX devices under the assumption they were created dynamically by libvirt. I may need to tweak that to skip excluding them as well

**Comment by yannou38** [comment]
Hello @electrofelix , sorry for the late reply.

This setting doesn't help, the offending network is this one (afaik, as it won't list other problematic networks)
```
<network>
  <name>stationbus1</name>
  <uuid>d40f3772-43d4-4fa2-a9ca-b08d92381c02</uuid>
  <forward mode='hostdev' managed='yes'>
    <address type='pci' domain='0x0000' bus='0x04' slot='0x10' function='0x2'/>
    <address type='pci' domain='0x0000' bus='0x04' slot='0x10' function='0x6'/>
    <address type='pci' domain='0x0000' bus='0x04' slot='0x11' function='0x2'/>
    <address type='pci' domain='0x0000' bus='0x04' slot='0x11' function='0x6'/>
    <address type='pci' domain='0x0000' bus='0x04' slot='0x12' function='0x2'/>
    <address type='pci' domain='0x0000' bus='0x04' slot='0x12' function='0x6'/>
  </forward>
</network>
```

It seem strange to me that those networks are properly ignored when no network is specified for the VM, but aren't when one is. Is it the same function called in both case, but with different parameters, or two separate functions ?

**Comment by electrofelix** [comment]
@yannou38 it appears I did something stupid, the bridge name for networks is checked in the host_devices, what I should have done is add a function to list all networks using a filter to skip if the bridge name was missing and use that in both places.

**Comment by yannou38** [comment]
Thanks ! Seem to work perfectly
