### ISSUE TITLE
Vagrant VM create error:  Initialization parameters must be an attributes hash ..

### ISSUE THREAD

**Issue by Newan** [vagrant-libvirt/vagrant-libvirt#688]
### Steps to reproduce
1. vagrant plugin install vagrant-libvirt
2. vagrant plugin install vagrant-mutate
3. vagrant box add trusty64 https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box
4. vagrant mutate trusty64  libvirt
5. crreate new Vagrantfile
like this tutorial: http://www.lucainvernizzi.net/blog/2014/12/03/vagrant-and-libvirt-kvm-qemu-setting-up-boxes-the-easy-way/
6. vagrant up --provider=libvirt

### Expected behaviour
Build process run in build error:
```
Bringing machine 'my_fancy_vm' up with 'libvirt' provider...
/root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/core/collection.rb:87:in `new': Initialization parameters must be an attributes hash, got NilClass nil (ArgumentError)
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/core/collection.rb:77:in `block in load'
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/core/collection.rb:77:in `each'
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/core/collection.rb:77:in `load'
        from /root/.vagrant.d/gems/gems/fog-libvirt-0.3.0/lib/fog/libvirt/models/compute/volumes.rb:11:in `all'
        from /root/.vagrant.d/gems/gems/fog-libvirt-0.3.0/lib/fog/libvirt/models/compute/server.rb:137:in `block in volumes'
        from /root/.vagrant.d/gems/gems/fog-libvirt-0.3.0/lib/fog/libvirt/models/compute/server.rb:137:in `map'
        from /root/.vagrant.d/gems/gems/fog-libvirt-0.3.0/lib/fog/libvirt/models/compute/server.rb:137:in `volumes'
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/formatador.rb:78:in `block in object_attributes'
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/formatador.rb:77:in `map'
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/formatador.rb:77:in `object_attributes'
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/formatador.rb:63:in `attribute_string'
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/formatador.rb:53:in `object_string'
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/formatador.rb:14:in `block in format'
        from /root/.vagrant.d/gems/gems/formatador-0.2.5/lib/formatador.rb:92:in `indent'
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/formatador.rb:41:in `indent'
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/formatador.rb:14:in `format'
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/core/model.rb:24:in `inspect'
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/core/collection.rb:19:in `inspect'
        from /root/.vagrant.d/gems/gems/fog-core-1.43.0/lib/fog/core/collection.rb:19:in `to_s'
        from /root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/set_name_of_domain.rb:18:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/machine.rb:225:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/machine.rb:200:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:567:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/machine.rb:186:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/machine.rb:186:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```
### System configuration
Ubuntu 16.04, headless 

**Libvirt version:**
Installed the plugin 'vagrant-libvirt (0.0.36)'!

**Output of `vagrant version; vagrant plugin list`:**
vagrant-libvirt (0.0.36)
vagrant-mutate (1.2.0)
vagrant-share (1.1.5, system)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
No errors in Log
```

**A Vagrantfile to reproduce the issue:**
```
same as the tutorial
```

**Are you using upstream vagrant package or your distros package?**
Upstream / Distro
Upstream, distro the plugin not installed

Thanks

**Comment by Newan** [comment]
Restart and error ist fixed

**Comment by untoreh** [comment]
*just restart libvirtd

**Comment by pawaanv** [comment]
Thanks untoreh,  restarted saved a lot of time :)
