### ISSUE TITLE
Ignoring ruby-libvirt-0.7.0 because its extensions are not built

### ISSUE THREAD

**Issue by jcf** [vagrant-libvirt/vagrant-libvirt#703]
### Steps to reproduce

1. Install Vagrant 1.9.1
2. Install vagrant-libvirt (using instructions in README)
3. Run `vagrant up`

README instructions:

```
CONFIGURE_ARGS='with-ldflags=-L/opt/vagrant/embedded/lib with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib' GEM_HOME=~/.vagrant.d/gems GEM_PATH=$GEM_HOME:/opt/vagrant/embedded/gems PATH=/opt/vagrant/embedded/bin:$PATH vagrant plugin install vagrant-libvirt
```

### Expected behaviour

The VM should come up.

### Actual behaviour

```
Bringing machine 'default' up with 'libvirt' provider...
Ignoring ruby-libvirt-0.7.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.7.0
WARNING: Nokogiri was built against LibXML version 2.9.4, but has dynamically loaded 2.9.2
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': incompatible library version - /home/jcf/.vagrant.d/gems/2.2.5/gems/ruby-libvirt-0.7.0/lib/_libvirt.so (LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/jcf/.vagrant.d/gems/2.2.5/gems/ruby-libvirt-0.7.0/lib/libvirt.rb:11:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/jcf/.vagrant.d/gems/2.2.5/gems/fog-libvirt-0.3.0/lib/fog/libvirt.rb:4:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/jcf/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/driver.rb:1:in `<top (required)>'
	from /home/jcf/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/provider.rb:29:in `driver'
	from /home/jcf/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/create_networks.rb:26:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:90:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:90:in `finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:20:in `block in initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:20:in `map'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:20:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:170:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:170:in `to_app'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/call.rb:52:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/jcf/.vagrant.d/gems/2.2.5/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/jcf/.vagrant.d/gems/2.2.5/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /home/jcf/.vagrant.d/gems/2.2.5/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:225:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:200:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:567:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

```

### System configuration

**OS/Distro version:**: Linux op 4.8.12-2-ARCH #1 SMP PREEMPT Fri Dec 2 20:17:06 CET 2016 x86_64 GNU/Linux

**Libvirt version:** 0.0.36

**Output of `vagrant version; vagrant plugin list`:**

```
Installed Version: 1.9.1
Latest Version: 1.9.0
 
You're running an up-to-date version of Vagrant!
```

I wonder how the latest version is determined. :smile:

```
vagrant-libvirt (0.0.36)
  - Version Constraint: > 0
vagrant-notify-forwarder (0.5.0)
  - Version Constraint: > 0
vagrant-triggers (0.5.3)
  - Version Constraint: > 0
```

**Are you using upstream vagrant package or your distros package?**

Distro

You might need to follow the steps I mentioned in #702 to get Vagrant 1.9.1 installed.

**Comment by jcf** [comment]
This is a duplicate of #541, which is mentioned in the [Arch wiki](https://wiki.archlinux.org/index.php/Vagrant#vagrant-libvirt).

Sorry about the noise.

**Comment by jcf** [comment]
Reopening this as it's a real issue with the current version of `vagrant-libvirt`. I appreciate that the problem may be upstream, but that doesn't mean that `vagrant-libvirt` isn't broken.

I've tried all the suggested workarounds, I've tried installing different versions of `ruby-libvirt`, and I've even tried older versions of `vagrant-libvirt` via `vagrant plugin install vagrant-libvirt --plugin-version <version>`.

**Comment by jcf** [comment]
Following the instructions to try `gem pristine ruby-libvirt --version 0.7.0`:

``` sh
$ CONFIGURE_ARGS='with-ldflags=-L/opt/vagrant/embedded/lib with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib' GEM_HOME=~/.vagrant.d/gems/2.2.5/ GEM_PATH=$GEM_HOME:/opt/vagrant/embedded/gems PATH=/opt/vagrant/embedded/bin:$PATH gem pristine ruby-libvirt
Restoring gems to pristine condition...
Building native extensions.  This could take a while...
Restored ruby-libvirt-0.7.0
```
