### ISSUE TITLE
can't activate ffi-0.6.4, already activated ffi-1.9.14 (Gem::LoadError)

### ISSUE THREAD

**Issue by devtosystems** [vagrant-libvirt/vagrant-libvirt#709]
Hi guys! Why the libvirt plugin vagrant takes previous version from rubygems?

```bash
$ vagrant plugin install libvirt
Installing the 'libvirt' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate ffi-0.6.4, already activated ffi-1.9.14 (Gem::LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:323:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:248:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:98:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:72:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/bin/vagrant:127:in `<main>'
tosystems@debian:~/Documents/box-images
```

How to resolve this, please?
Thanks! :)

**Comment by pronix** [comment]
```vagrant plugin install vagrant-libvirt```

**Comment by devtosystems** [comment]
I got it now! :D

**Comment by dlaweb** [comment]
```bash
vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Vagrant failed to install the requested plugin because it depends
on a library which is not currently installed on this system. The
following library is required by the 'vagrant-libvirt' plugin:

  libvirt

Please install the library and then run the command again.

➜  ~ vagrant plugin install libvirt                     
Installing the 'libvirt' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies ffi (~> 0.6.3) and ffi (= 1.15.3)
  Activated ffi-1.15.3
  which does not match conflicting dependency (~> 0.6.3)

  Conflicting dependency chains:
    ffi (= 1.15.3), 1.15.3 activated

  versus:
    libvirt (> 0), 0.2.0 activated, depends on
    ffi (~> 0.6.3)
```
