### ISSUE TITLE
ruby errors when trying to set pxe virtual network name

### ISSUE THREAD

**Issue by eoli3n** [vagrant-libvirt/vagrant-libvirt#718]
### Steps to reproduce
1. Vagrant up
2. Cry
3. Search a rope
4. Fail
5. Repeat

### Expected behaviour
Tell us what should happen

### Actual behaviour
```
Bringing machine 'pxeclient' up with 'libvirt' provider...
Ignoring ruby-libvirt-0.7.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.7.0
==> pxeclient: Creating domain with the following settings...
==> pxeclient:  -- Name:              client-dest_pxeclient
==> pxeclient:  -- Domain type:       kvm
==> pxeclient:  -- Cpus:              1
==> pxeclient:  -- Memory:            2048M
==> pxeclient:  -- Management MAC:    
==> pxeclient:  -- Loader:            
==> pxeclient:  -- Storage pool:      default
==> pxeclient:  -- Image:              (G)
==> pxeclient:  -- Volume Cache:      default
==> pxeclient:  -- Kernel:            
==> pxeclient:  -- Initrd:            
==> pxeclient:  -- Graphics Type:     vnc
==> pxeclient:  -- Graphics Port:     5900
==> pxeclient:  -- Graphics IP:       127.0.0.1
==> pxeclient:  -- Graphics Password: Not defined
==> pxeclient:  -- Video Type:        cirrus
==> pxeclient:  -- Video VRAM:        9216
==> pxeclient:  -- Keymap:            en-us
==> pxeclient:  -- TPM Path:          
==> pxeclient:  -- Boot device:        {"network"=>"pxe"}
==> pxeclient:  -- Disks:         vdb(qcow2,10G)
==> pxeclient:  -- Disk(vdb):     /var/lib/libvirt/images/client-dest_pxeclient-vdb.qcow2
==> pxeclient:  -- INPUT:             type=mouse, bus=ps2
==> pxeclient:  -- CHANNEL:             type=spicevmc, mode=
==> pxeclient:  -- CHANNEL:             target_type=virtio, target_name=com.redhat.spice.0
==> pxeclient:  -- Command line : 
/root/.vagrant.d/gems/2.3.3/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/set_boot_order.rb:48:in `block in call': undefined method `add_child' for nil:NilClass (NoMethodError)
	from /root/.vagrant.d/gems/2.3.3/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/set_boot_order.rb:46:in `each'
	from /root/.vagrant.d/gems/2.3.3/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/set_boot_order.rb:46:in `each_with_index'
	from /root/.vagrant.d/gems/2.3.3/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/set_boot_order.rb:46:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:34:in `call'
	from /root/.vagrant.d/gems/2.3.3/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/create_network_interfaces.rb:144:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:34:in `call'
	from /root/.vagrant.d/gems/2.3.3/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/create_networks.rb:80:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:34:in `call'
	from /root/.vagrant.d/gems/2.3.3/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/create_domain.rb:253:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:34:in `call'
	from /root/.vagrant.d/gems/2.3.3/gems/vagrant-libvirt-0.0.36/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/machine.rb:225:in `action_raw'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/machine.rb:200:in `block in action'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/environment.rb:533:in `lock'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/machine.rb:186:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/machine.rb:186:in `action'
	from /usr/share/rubygems-integration/all/gems/vagrant-1.9.0/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

### System configuration
**System version**
Stretch 4.7.0-1-amd64 #1 SMP Debian 4.7.8-1 (2016-10-19) x86_64 GNU/Linux

**Libvirt version:**
libvirt-clients                  2.4.0-3
libvirt-daemon                   2.4.0-3
libvirt-daemon-system            2.4.0-3
libvirt-dev                      2.4.0-3
libvirt0                         2.4.0-3

**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 1.9.0
vagrant-libvirt (0.0.36)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
Too long ->
https://gist.github.com/eoli3n/0183f0445cc58bec54f67cb4f619cbc0

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.define :pxeclient do |pxeclient|
    pxeclient.vm.provider :libvirt do |domain|
      domain.storage :file, :size => '10G', :type => 'qcow2'
      boot_network = {'network' => 'pxe'}
      domain.boot boot_network
    end
  end
end
```
**my .vagrant.d/Vagrantfile**
```
Vagrant.configure("2") do |config|
  
  #vm libvirt configuration
  config.vm.provider :libvirt do |domain|
    domain.cpu_mode = 'host-passthrough'
    domain.memory = 2048
    domain.cpus = 1
    domain.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'
  end
end
```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by eoli3n** [comment]
Upgrading to 1.9.1 with https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb.
No error now.

```
boot_network = {'network' => 'pxe'}
domain.boot boot_network
```

Should this add the interface in virtual network 'pxe' NAT ? Or maybe i misunderstand something.

Server is, vagrantfile network line. I want to be able to pxe boot on this virtual network, my client.

```
config.vm.network "private_network", ip: "192.168.0.254", libvirt__network_name: "pxe"
```

**Comment by eoli3n** [comment]
And was asking for the wrong option, what i wanted is 

```
domain.boot 'network'
domain.mgmt_attach = "false"
domain.management_network_name = "pxe"
domain.management_network_address = "192.168.0.0/24"
domain.management_network_mode = "nat"
```

It works well now.
