### ISSUE TITLE
Unable to install plugin on Ubuntu 16

### ISSUE THREAD

**Issue by chrisspen** [vagrant-libvirt/vagrant-libvirt#724]
### Steps to reproduce
1. Run vagrant plugin install vagrant-libvirt
2. Receive error:

    Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
    /usr/lib/ruby/2.3.0/rubygems/specification.rb:946:in `all=': undefined method `group_by' for nil:NilClass (NoMethodError)
	    from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:275:in `with_isolated_gem'
	    from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:231:in `internal_install'
	    from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:102:in `install'
	    from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	    from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:72:in `install_plugin'
	    from /usr/share/vagrant/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	    from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	    from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	    from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
	    from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	    from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
	    from /usr/share/vagrant/plugins/commands/plugin/command/base.rb:14:in `action'
	    from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	    from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `each'
	    from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `execute'
	    from /usr/share/vagrant/plugins/commands/plugin/command/root.rb:56:in `execute'
	    from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:42:in `execute'
	    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:268:in `cli'
	    from /usr/bin/vagrant:173:in `<main>'

### System configuration
**OS/Distro version:**: Ubuntu 16.04

**Libvirt version:**

    $ dpkg --list|grep -i libvirt
    ii  libvirt-bin                          1.3.1-1ubuntu10.6                        amd64        programs for the libvirt library
    ii  libvirt-dev:amd64                    1.3.1-1ubuntu10.6                        amd64        development files for the libvirt library
    ii  libvirt0:amd64                       1.3.1-1ubuntu10.6                        amd64        library for interfacing with different virtualization systems

**Output of `vagrant version; vagrant plugin list`:**

    Installed Version: 1.8.1

    Vagrant was unable to check for the latest version of Vagrant.
    Please check manually at http://www.vagrantup.com
    No plugins installed.

**Comment by chrisspen** [comment]
It would seem vagrant-libvirt doesn't work with any version of Vagrant less than 1.9*. Purging the 1.8.1 version included in the standard 16.04 repo and installing the deb from Vagrant's website fixed this error.
