### ISSUE TITLE
Package for libvirt

### ISSUE THREAD

**Issue by waldirio** [vagrant-libvirt/vagrant-libvirt#748]
### Vagrant version
Vagrant 1.9.2

### Host operating system
RHEL 7.3

### Actual behavior
Hi, I use only libvirt / kvm on my environment, then after create one new guest via libvirt, configure and prepare to be one new box, I got the message below when trying to create a new one box
[root@dvader BOX]# vagrant package --base base_rhel7
#
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the VBoxManage binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
VBoxManage binary and add it to the PATH environmental variable.
#

So then I was looking for how to force the provider and looking the help
#
--base NAME Name of a VM in VirtualBox to package as a base box (VirtualBox Only)
#

So my request is, just enable the libvirt to be one valid provider to create a new box without virtualbox necessity.

### Expected behavior
Be able to create new box directly via libvirt.

Thank you!
Waldirio

**Comment by infernix** [comment]
`export VAGRANT_DEFAULT_PROVIDER=libvirt`

**Comment by waldirio** [comment]
Hi, good afternoon

I did this one and still the same

export VAGRANT_DEFAULT_PROVIDER=libvirt

or

VAGRANT_DEFAULT_PROVIDER=libvirt
export VAGRANT_DEFAULT_PROVIDER

When I try to create the box, same response.

Waldirio

**Comment by infernix** [comment]
Post the debug log please, as mentioned in the issue template.

**Comment by waldirio** [comment]
Hi infernix,

Attached the file with all steps used to prepare the box and the verbose log during the package.

Thank you for your help.

Ps.: I'm just using the latest vagrant version *downloaded today from the website*.
[vagrant_steps_log.txt](https://github.com/vagrant-libvirt/vagrant-libvirt/files/851239/vagrant_steps_log.txt)

**Comment by waldirio** [comment]
Hi infernix,

Was possible to create the box using the commands below

/root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.37/tools/create_box.sh 
/root/.vagrant.d/gems/gems/vagrant-libvirt-0.0.37/tools/prepare_redhat_for_box.sh

I saw the same code inside the rb code but this is not working for me.

Please, let me know if you need any additional info from my side.

PS: Did you reproduce the same in your side ?

Have a great day.
Waldirio

**Comment by muelli** [comment]
```
➜ tmp>vagrant box list -i | grep win
vagrant-win7-ie10                    (libvirt, 0)
vagrant-win7-ie10                    (libvirt, 1)
➜ tmp>env VAGRANT_LOG=debug VAGRANT_DEFAULT_PROVIDER=libvirt vagrant  --provider=libvirt package --base vagrant-win7-ie10  --output /tmp/windows.box
 INFO global: Vagrant version: 1.8.1
 INFO global: Ruby version: 2.3.1
 INFO global: RubyGems version: 2.5.1
 INFO global: VAGRANT_LOG="debug"
 INFO global: VAGRANT_DEFAULT_PROVIDER="libvirt"
 INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
 INFO global: Plugins:
 INFO global:   - builder = 3.2.3
 INFO global:   - bundler = 1.11.2
 INFO global:   - erubis = 2.7.0
 INFO global:   - excon = 0.57.0
 INFO global:   - ffi = 1.9.18
 INFO global:   - formatador = 0.2.5
 INFO global:   - fog-core = 1.43.0
 INFO global:   - multi_json = 1.12.1
 INFO global:   - fog-json = 1.0.2
 INFO global:   - mini_portile2 = 2.1.0
 INFO global:   - nokogiri = 1.6.8.1
 INFO global:   - fog-xml = 0.1.3
 INFO global:   - json = 2.1.0
 INFO global:   - ruby-libvirt = 0.7.0
 INFO global:   - fog-libvirt = 0.4.0
 INFO global:   - gssapi = 1.2.0
 INFO global:   - gyoku = 1.3.1
 INFO global:   - httpclient = 2.8.3
 INFO global:   - little-plugger = 1.1.4
 INFO global:   - logging = 2.2.2
 INFO global:   - nori = 2.6.0
 INFO global:   - rubyntlm = 0.6.2
 INFO global:   - rubyzip = 1.2.1
 INFO global:   - vagrant-hosts = 2.8.0
 INFO global:   - vagrant-libvirt = 0.0.40
 INFO global:   - vagrant-mutate = 1.2.0
 INFO global:   - vagrant-proxyconf = 1.5.2
 INFO global:   - vai = 0.9.3
 INFO global:   - winrm = 2.0.0
 INFO global:   - winrm-fs = 1.0.1
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/salt/plugin.rb
 INFO manager: Registered plugin: salt
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/chef/plugin.rb
 INFO manager: Registered plugin: chef
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/cfengine/plugin.rb
 INFO manager: Registered plugin: CFEngine Provisioner
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/puppet/plugin.rb
 INFO manager: Registered plugin: puppet
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/file/plugin.rb
 INFO manager: Registered plugin: file
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/ansible/plugin.rb
 INFO manager: Registered plugin: ansible
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/docker/plugin.rb
 INFO manager: Registered plugin: docker
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/provisioners/shell/plugin.rb
 INFO manager: Registered plugin: shell
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/communicators/winrm/plugin.rb
 INFO manager: Registered plugin: winrm communicator
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/communicators/ssh/plugin.rb
 INFO manager: Registered plugin: ssh communicator
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat Enterprise Linux host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/windows/plugin.rb
 INFO manager: Registered plugin: Windows host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/bsd/plugin.rb
 INFO manager: Registered plugin: BSD host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/arch/plugin.rb
 INFO manager: Registered plugin: Arch host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/linux/plugin.rb
 INFO manager: Registered plugin: Linux host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/null/plugin.rb
 INFO manager: Registered plugin: null host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/darwin/plugin.rb
 INFO manager: Registered plugin: Mac OS X host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/suse/plugin.rb
 INFO manager: Registered plugin: SUSE host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/hosts/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo host
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/solaris11/plugin.rb
 INFO manager: Registered plugin: Solaris 11 guest.
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/fedora/plugin.rb
 INFO manager: Registered plugin: Fedora guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/netbsd/plugin.rb
 INFO manager: Registered plugin: NetBSD guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/pld/plugin.rb
 INFO manager: Registered plugin: PLD Linux guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/mint/plugin.rb
 INFO manager: Registered plugin: Mint guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/esxi/plugin.rb
 INFO manager: Registered plugin: ESXi guest.
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/debian/plugin.rb
 INFO manager: Registered plugin: Debian guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat Enterprise Linux guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/ubuntu/plugin.rb
 INFO manager: Registered plugin: Ubuntu guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/windows/plugin.rb
 INFO manager: Registered plugin: Windows guest.
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/photon/plugin.rb
 INFO manager: Registered plugin: VMware Photon guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/nixos/plugin.rb
 INFO manager: Registered plugin: NixOS guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/omnios/plugin.rb
 INFO manager: Registered plugin: OmniOS guest.
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/funtoo/plugin.rb
 INFO manager: Registered plugin: Funtoo guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/arch/plugin.rb
 INFO manager: Registered plugin: Arch guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/linux/plugin.rb
 INFO manager: Registered plugin: Linux guest.
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/smartos/plugin.rb
 INFO manager: Registered plugin: SmartOS guest.
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/atomic/plugin.rb
 INFO manager: Registered plugin: Atomic Host guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/solaris/plugin.rb
 INFO manager: Registered plugin: Solaris guest.
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/tinycore/plugin.rb
 INFO manager: Registered plugin: TinyCore Linux guest.
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/coreos/plugin.rb
 INFO manager: Registered plugin: CoreOS guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/darwin/plugin.rb
 INFO manager: Registered plugin: Darwin guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/openbsd/plugin.rb
 INFO manager: Registered plugin: OpenBSD guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/suse/plugin.rb
 INFO manager: Registered plugin: SUSE guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/guests/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware guest
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/providers/docker/plugin.rb
 INFO manager: Registered plugin: docker-provider
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/providers/hyperv/plugin.rb
 INFO manager: Registered plugin: Hyper-V provider
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/providers/virtualbox/plugin.rb
 INFO manager: Registered plugin: VirtualBox provider
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/resume/plugin.rb
 INFO manager: Registered plugin: resume command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/version/plugin.rb
 INFO manager: Registered plugin: version command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/ssh_config/plugin.rb
 INFO manager: Registered plugin: ssh-config command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/list-commands/plugin.rb
 INFO manager: Registered plugin: list-commands command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/package/plugin.rb
 INFO manager: Registered plugin: package command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/plugin/plugin.rb
 INFO manager: Registered plugin: plugin command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/up/plugin.rb
 INFO manager: Registered plugin: up command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/status/plugin.rb
 INFO manager: Registered plugin: status command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/help/plugin.rb
 INFO manager: Registered plugin: help command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/provision/plugin.rb
 INFO manager: Registered plugin: provision command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/reload/plugin.rb
 INFO manager: Registered plugin: reload command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/box/plugin.rb
 INFO manager: Registered plugin: box command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/login/plugin.rb
 INFO manager: Registered plugin: vagrant-login
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/ssh/plugin.rb
 INFO manager: Registered plugin: ssh command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/global-status/plugin.rb
 INFO manager: Registered plugin: global-status command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/destroy/plugin.rb
 INFO manager: Registered plugin: destroy command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/halt/plugin.rb
 INFO manager: Registered plugin: halt command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/init/plugin.rb
 INFO manager: Registered plugin: init command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/rdp/plugin.rb
 INFO manager: Registered plugin: rdp command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/push/plugin.rb
 INFO manager: Registered plugin: push command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/suspend/plugin.rb
 INFO manager: Registered plugin: suspend command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/snapshot/plugin.rb
 INFO manager: Registered plugin: snapshot command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/port/plugin.rb
 INFO manager: Registered plugin: port command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/powershell/plugin.rb
 INFO manager: Registered plugin: powershell command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/cap/plugin.rb
 INFO manager: Registered plugin: cap command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/commands/provider/plugin.rb
 INFO manager: Registered plugin: provider command
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/synced_folders/rsync/plugin.rb
 INFO manager: Registered plugin: RSync synced folders
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/synced_folders/smb/plugin.rb
 INFO manager: Registered plugin: SMB synced folders
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/synced_folders/nfs/plugin.rb
 INFO manager: Registered plugin: NFS synced folders
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/pushes/atlas/plugin.rb
 INFO manager: Registered plugin: atlas
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/pushes/local-exec/plugin.rb
 INFO manager: Registered plugin: local-exec
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/pushes/noop/plugin.rb
 INFO manager: Registered plugin: noop
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/pushes/ftp/plugin.rb
 INFO manager: Registered plugin: ftp
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/pushes/heroku/plugin.rb
 INFO manager: Registered plugin: heroku
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/kernel_v2/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: /usr/share/vagrant/plugins/kernel_v1/plugin.rb
 INFO manager: Registered plugin: kernel
 INFO global: Loading plugins!
 INFO manager: Registered plugin: vagrant-mutate
 INFO manager: Registered plugin: hosts
 INFO manager: Registered plugin: vai
 INFO proxyconf: Trying to load vagrant-aws
 INFO proxyconf: Failed to load vagrant-aws: #<LoadError: cannot load such file -- vagrant-aws>
 INFO proxyconf: Ignoring the error
 INFO proxyconf: Trying to load vagrant-omnibus
 INFO proxyconf: Failed to load vagrant-omnibus: #<LoadError: cannot load such file -- vagrant-omnibus>
 INFO proxyconf: Ignoring the error
 INFO proxyconf: Trying to load vagrant-vbguest
 INFO proxyconf: Failed to load vagrant-vbguest: #<LoadError: cannot load such file -- vagrant-vbguest>
 INFO proxyconf: Ignoring the error
 INFO manager: Registered plugin: vagrant-proxyconf
 INFO manager: Registered plugin: libvirt
 INFO vagrant: `vagrant` invoked: ["--provider=libvirt", "package", "--base", "vagrant-win7-ie10", "--output", "/tmp/windows.box"]
DEBUG vagrant: Creating Vagrant environment
 INFO environment: Environment initialized (#<Vagrant::Environment:0x00000001bbed28>)
 INFO environment:   - cwd: /tmp
 INFO environment: Home path: /home/muelli/.vagrant.d
 WARN environment: No local data path is set. Local data cannot be stored.
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 3 hooks defined.
 INFO runner: Running action: environment_plugins_loaded #<Vagrant::Action::Builder:0x00000003038d80>
 INFO environment: Running hook: environment_load
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 3 hooks defined.
 INFO runner: Running action: environment_load #<Vagrant::Action::Builder:0x00000002af1c28>
 INFO cli: CLI: ["--provider=libvirt"] "package" ["--base", "vagrant-win7-ie10", "--output", "/tmp/windows.box"]
DEBUG cli: Invoking command class: VagrantPlugins::CommandPackage::Command ["--base", "vagrant-win7-ie10", "--output", "/tmp/windows.box"]
DEBUG command: package options: {:base=>"vagrant-win7-ie10", :output=>"/tmp/windows.box"}
 INFO loader: Loading configuration in order: [:home, :root]
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO machine: Initializing machine: vagrant-win7-ie10
 INFO machine:   - Provider: VagrantPlugins::ProviderVirtualBox::Provider
 INFO machine:   - Box: 
 INFO machine:   - Data dir: 
DEBUG virtualbox: Instantiating the driver for machine ID: "vagrant-win7-ie10"
 INFO base: VBoxManage path: VBoxManage
 INFO environment: Running hook: environment_unload
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /tmp>]
DEBUG host: Trying: redhat
DEBUG host: Trying: arch
DEBUG host: Trying: slackware
DEBUG host: Trying: darwin
DEBUG host: Trying: freebsd
DEBUG host: Trying: suse
DEBUG host: Trying: gentoo
DEBUG host: Trying: windows
DEBUG host: Trying: bsd
DEBUG host: Trying: linux
 INFO host: Detected: linux!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 3 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x000000021c7f58>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VirtualBoxNotDetected: Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.>
ERROR vagrant: Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
ERROR vagrant: /usr/share/vagrant/plugins/providers/virtualbox/driver/meta.rb:51:in `rescue in block in initialize'
/usr/share/vagrant/plugins/providers/virtualbox/driver/meta.rb:45:in `block in initialize'
/usr/share/vagrant/plugins/providers/virtualbox/driver/meta.rb:41:in `synchronize'
/usr/share/vagrant/plugins/providers/virtualbox/driver/meta.rb:41:in `initialize'
/usr/share/vagrant/plugins/providers/virtualbox/provider.rb:56:in `new'
/usr/share/vagrant/plugins/providers/virtualbox/provider.rb:56:in `machine_id_changed'
/usr/share/vagrant/plugins/providers/virtualbox/provider.rb:36:in `initialize'
/usr/lib/ruby/vendor_ruby/vagrant/machine.rb:132:in `new'
/usr/lib/ruby/vendor_ruby/vagrant/machine.rb:132:in `initialize'
/usr/share/vagrant/plugins/commands/package/command.rb:59:in `new'
/usr/share/vagrant/plugins/commands/package/command.rb:59:in `package_base'
/usr/share/vagrant/plugins/commands/package/command.rb:42:in `execute'
/usr/lib/ruby/vendor_ruby/vagrant/cli.rb:42:in `execute'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:268:in `cli'
/usr/bin/vagrant:173:in `<main>'
 INFO interface: error: Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
 INFO interface: Machine: error-exit ["Vagrant::Errors::VirtualBoxNotDetected", "Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.\nVagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires\nthis to be available on the PATH. If VirtualBox is installed, please find the\n`VBoxManage` binary and add it to the PATH environmental variable."]
➜ tmp>
```

**Comment by dms-cat** [comment]
This problem doesn't seem to be specific to libvirt - I'm getting the same error message when using lxd as the provider:

```text
$ vagrant up default --no-provision --provider lxd
Bringing machine 'default' up with 'lxd' provider...
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
```

**Comment by apmattil** [comment]
I uninstalled disksize plugin and vagrant up started to work again.
perhaps there is some dependency at disksize pluging to nonexisting VBox* ?

**Comment by electrofelix** [comment]
@dms-cat it is likely some plugin is trying to do something that requires VirtualBox but isn't ensuring it is only done if it's actions are loaded and instead is trying to do it on load.

@apmattil yeap, see https://github.com/sprotheroe/vagrant-disksize/blob/56b46a9285758ef6d89875755d2a96f0eb801b97/lib/vagrant/disksize/actions.rb#L11-L16

This will result in it attempting to run VBoxManage and throw an exception when it's not found due to the code at https://github.com/hashicorp/vagrant/blob/main/plugins/providers/virtualbox/driver/meta.rb#L34-L54 getting executed during the ResizeDisk class evaluation.

**Comment by electrofelix** [comment]
As this is appears to be caused by other plugins or by issues in Vagrant itself, I don't believe there is much we can do, except try and help debug the cause and log the issues with the appropriate project.

**Comment by pawaanv** [comment]
this isuse is there in linux mint Linux Mint 20.2, uninstlling the vagrant-disksize plugin has fixed the issue thanks @[apmattil].
