### ISSUE TITLE
package failed to output to a directory

### ISSUE THREAD

**Issue by reidrac** [vagrant-libvirt/vagrant-libvirt#765]
### Steps to reproduce
1.  mkdir `boxes`
2. run `vagrant package myvm --output boxes/test.box`

### Expected behaviour
The Vagrant box is saved into the `boxes/` directory.

### Actual behaviour
vagrant-libvirt crashes on rename:
```
tar (child): boxes/test.box: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
/opt/vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:527:in `rename': No such file or directory @ sys_fail2 - (/home/user/vagrant/_tmp_package/boxes/test.box, ../boxes/test.box) (Errno::ENOENT)
        from /opt/vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:527:in `block in mv'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1586:in `fu_each_src_dest0'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:516:in `mv'
        from /home/user/.vagrant.d/gems/2.2.5/gems/vagrant-libvirt-0.0.37/lib/vagrant-libvirt/action/package_domain.rb:47:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/machine.rb:225:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/machine.rb:200:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:567:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/machine.rb:186:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/machine.rb:186:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/package/command.rb:90:in `package_vm'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/package/command.rb:79:in `block in package_target'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/v2/command.rb:229:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/package/command.rb:77:in `package_target'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/package/command.rb:45:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:308:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/bin/vagrant:127:in `<main>'
```

### System configuration
**OS/Distro version:**: OpenSUSE 42.2

**Libvirt version:** ibvirt-2.0.0-13.3.3.x86_64

**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 1.9.3
Latest Version: 1.9.3

vagrant-libvirt (0.0.37)
vagrant-share (1.1.7, system)

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by infernix** [comment]
Yep, this need fixing.

For now just specify `--output test.box` in your current working dir.
