### ISSUE TITLE
Nokogiri upgraded in Vagrant 1.9.4

### ISSUE THREAD

**Issue by jcf** [vagrant-libvirt/vagrant-libvirt#768]
Installation of vagrant-libvirt via `vagrant plugin install vagrant-libvirt` and the longer Arch Linux version fail with the following error:

```
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate nokogiri-1.6.8.1, already activated nokogiri-1.7.1 (Gem::LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/bundler.rb:388:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/bundler.rb:385:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/bundler.rb:385:in `activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/bundler.rb:288:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/bundler.rb:106:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/plugin/manager.rb:72:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/plugin/action/install_gem.rb:29:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/bin/vagrant:127:in `<main>'
```

It looks like Vagrant upgraded its [version of Nokogiri here](https://github.com/mitchellh/vagrant/blob/d790c138ac5c4755facb28fc688b8304209c961a/vagrant.gemspec#L36).

This is the longer recommended installation command for Arch Linux that doesn't make a difference.

```
CONFIGURE_ARGS='with-ldflags=-L/opt/vagrant/embedded/lib with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib' \                                    ⏎
  GEM_HOME=~/.vagrant.d/gems GEM_PATH=$GEM_HOME:/opt/vagrant/embedded/gems PATH=/opt/vagrant/embedded/bin:$PATH \
  vagrant plugin install vagrant-libvirt 
```

**Comment by dolobanko** [comment]
Just spent 6 hours today on this.

**Comment by timhughes** [comment]
Thanks @jcf 

For those that follow there is a workaround https://github.com/vagrant-libvirt/vagrant-libvirt/issues/770#issuecomment-298017815 using this change

**Comment by kzorba** [comment]
Workaround mentioned  at [#828 (comment)](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/828#issuecomment-354654618) worked for me
