### ISSUE TITLE
Starting a cluster with shared storage is racy

### ISSUE THREAD

**Issue by brianjmurrell** [vagrant-libvirt/vagrant-libvirt#825]
### Steps to reproduce
1. Create a Vagrantfile with a cluster of VMs attached to shared storage as such:
```
					libvirt.storage :file,
							:size => '5120M',
							:path => "target#{target}.img",
							:serial => "target#{target}",
							:allow_existing => true,
							:shareable => true,
							:bus => 'scsi',
							:cache => 'none',
							:type => 'qcow2'
```
2. run `vagrant up`

### Expected behaviour
Vagrant[-libvirt] should instantiate the cluster.

### Actual behaviour
Failure to instantiate if the shared volumes but only if they don't exist already:

```
Call to virStorageVolCreateXML failed: storage volume 'target1.img' exists already

/usr/share/gems/gems/fog-libvirt-0.3.0/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume_xml'
/usr/share/gems/gems/fog-libvirt-0.3.0/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume'
/usr/share/gems/gems/fog-libvirt-0.3.0/lib/fog/libvirt/models/compute/volume.rb:40:in `save'
/usr/share/gems/gems/fog-core-1.34.0/lib/fog/core/collection.rb:51:in `create'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/create_domain.rb:137:in `block in call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/create_domain.rb:120:in `each'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/create_domain.rb:120:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/create_domain_volume.rb:51:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/handle_box_image.rb:111:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/handle_storage_pool.rb:50:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.35/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/lib/vagrant/action/builtin/call.rb:53:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/lib/vagrant/machine.rb:225:in `action_raw'
/usr/share/vagrant/lib/vagrant/machine.rb:200:in `block in action'
/usr/share/vagrant/lib/vagrant/environment.rb:561:in `lock'
/usr/share/vagrant/lib/vagrant/machine.rb:186:in `call'
/usr/share/vagrant/lib/vagrant/machine.rb:186:in `action'
/usr/share/vagrant/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

### System configuration
**OS/Distro version:**:
Fedora 26

**Libvirt version:**
2.2.1

**Output of `vagrant version; vagrant plugin list`:**
Installed Version: 1.8.5
Latest Version: 2.0.1

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
Too big (>10K lines) to audit well enough to know I am not leaking sensitive information.  I'm happy to excerpt or analyse as you need.

**A Vagrantfile to reproduce the issue:**
https://github.com/intel-hpdd/intel-manager-for-lustre/blob/manual-upgrade/Vagrantfile

**Are you using upstream vagrant package or your distros package?**
Distro

Seems like there is a race when starting up multiple VMs attached to the same shared storage.  If the storage already exists before running `vagrant up`, startup is fine, so the `:allow_existing => true` attribute is generally working.  My guess would be that there is a race between multiple VMs looking for the existence of the shared volume and then trying to create it when they don't find it.

**Comment by infernix** [comment]
Probably correct but a relatively rare case since using shared storage this way is uncommon. I'm not sure if we can fix that in vagrant-libvirt.

For now I'd work around it with `vagrant up --no-parallel`

**Comment by martin-schwenke** [comment]
I'm hitting this bug too.  I'm just wondering if there has been any progress on understanding and fixing it.

Thanks...
