### ISSUE TITLE
Vagrant up gives me error: Call to virDomainDefineXML failed: internal error: Unknown source mode '' when using "org.qemu.guest_agent.0"

### ISSUE THREAD

**Issue by ruzickap** [vagrant-libvirt/vagrant-libvirt#831]
Hello

I'm not able to run ```vagrant up``` when using the latest Fedroa / libvirt / vagrant with this parameters in Vagrantfile:

```
libvirt.channel :type => 'unix',     :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
```

I'm getting the following error (details are below):

```
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: internal error: Unknown source mode ''
```

### Steps to reproduce
1. ```vagrant init centos/7```
2. Add the following to the Vagrantfile:
```
  config.vm.provider :libvirt do |libvirt|
    libvirt.channel :type => 'unix',     :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
  end
```
3. ```vagrant up```

### Expected behaviour
VM should start like normal when using ```vagrant up``` 

### Actual behaviour
Getting error and Vagrant stops

### System configuration
**OS/Distro version:** 
Fedora 27

**Libvirt version:**
```
$ rpm -qa libvirt-libs
libvirt-libs-3.7.0-2.fc27.x86_64
```

**Output of `vagrant version; vagrant plugin list`:**
```
$ vagrant version; vagrant plugin list
Installed Version: 2.0.1
Latest Version: 2.0.1

You're running an up-to-date version of Vagrant!
vagrant-hostmanager (1.8.7)
vagrant-libvirt (0.0.40)
vagrant-share (1.1.9, system)
vagrant-winrm (0.7.0)
```

**Output of `VAGRANT_LOG=debug vagrant up --provider=libvirt`**
```
VAGRANT_LOG=debug vagrant up --provider=libvirt
...
...
...
==> default:  -- TPM Path:          
 INFO interface: info:  -- INPUT:             type=mouse, bus=ps2
 INFO interface: info: ==> default:  -- INPUT:             type=mouse, bus=ps2
==> default:  -- INPUT:             type=mouse, bus=ps2
 INFO interface: info:  -- CHANNEL:             type=unix, mode=
 INFO interface: info: ==> default:  -- CHANNEL:             type=unix, mode=
==> default:  -- CHANNEL:             type=unix, mode=
 INFO interface: info:  -- CHANNEL:             target_type=virtio, target_name=org.qemu.guest_agent.0
 INFO interface: info: ==> default:  -- CHANNEL:             target_type=virtio, target_name=org.qemu.guest_agent.0
==> default:  -- CHANNEL:             target_type=virtio, target_name=org.qemu.guest_agent.0
ERROR warden: Error occurred: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: internal error: Unknown source mode ''
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: internal error: Unknown source mode ''
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: internal error: Unknown source mode ''
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00000000040b3430>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-a4aa5e184479cf95c2cea3c7abcf9d86
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x000000000312eb40>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::ProviderLibvirt::Errors::FogCreateServerError: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: internal error: Unknown source mode ''>
ERROR vagrant: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: internal error: Unknown source mode ''
ERROR vagrant: /home/pruzicka/.vagrant.d/gems/2.4.2/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/create_domain.rb:302:in `rescue in call'
/home/pruzicka/.vagrant.d/gems/2.4.2/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/create_domain.rb:297:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/home/pruzicka/.vagrant.d/gems/2.4.2/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/create_domain_volume.rb:82:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/home/pruzicka/.vagrant.d/gems/2.4.2/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/handle_box_image.rb:113:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/home/pruzicka/.vagrant.d/gems/2.4.2/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/handle_storage_pool.rb:52:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/home/pruzicka/.vagrant.d/gems/2.4.2/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:227:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:202:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/environment.rb:631:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:188:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:188:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: internal error: Unknown source mode ''
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: internal error: Unknown source mode ''
 INFO interface: Machine: error-exit ["VagrantPlugins::ProviderLibvirt::Errors::FogCreateServerError", "Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: internal error: Unknown source mode ''"]
```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.provider :libvirt do |libvirt|
    libvirt.channel :type => 'unix',     :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
  end
end
```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by ruzickap** [comment]
When I use Fedora 26 which has different libvirt version ```3.2.1``` then everything is working fine...

Looks like the ```vagrant-libvirt``` is not fully compatible with ```libvirt``` version ```3.7.0```.

**Comment by ableischwitz** [comment]
[PR#838](https://github.com/vagrant-libvirt/vagrant-libvirt/pull/838) should provide a fix for this issue. The fix removes the empty "<source mode=''...>" entries.

**Comment by ruzickap** [comment]
The problem was resolved in the latest plugin version...
Closing...
