### ISSUE TITLE
CPU feature 'vmx' can't be overwritten when libvirt.nested = true

### ISSUE THREAD

**Issue by anastasiiavlaskina** [vagrant-libvirt/vagrant-libvirt#866]
### Steps to reproduce
1. libvirt.nested = true 
    libvirt.cpu_feature :name => 'vmx', :policy => 'require'  in Vagrantfile
2. vagrant up

### Expected behaviour
A vm shoud be brought up and support nested virtualization with vmx require parameter.

### Actual behaviour
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: XML error: CPU feature 'vmx' specified more than once

### System configuration
**OS/Distro version:**: Ubuntu 16.04

**Libvirt version:** libvirtd (libvirt) 2.0.0

**Output of `vagrant version; vagrant plugin list`:**
hostmanager (1.2.2)
  - Version Constraint: > 0
vagrant-hostmanager (1.8.7)
  - Version Constraint: > 0
vagrant-libvirt (0.0.40)
  - Version Constraint: > 0
vagrant-share (1.1.9, system)
  - Version Constraint: > 0

**Output of `VAGRANT_LOG=debug vagrant up --provider=libvirt`**
```
ERROR vagrant: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: XML error: CPU feature 'vmx' specified more than once
ERROR vagrant: /home/vlaskina/.vagrant.d/gems/2.4.2/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/create_domain.rb:302:in `rescue in call'
/home/vlaskina/.vagrant.d/gems/2.4.2/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/create_domain.rb:297:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/home/vlaskina/.vagrant.d/gems/2.4.2/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/create_domain_volume.rb:82:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/home/vlaskina/.vagrant.d/gems/2.4.2/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/handle_box_image.rb:113:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/home/vlaskina/.vagrant.d/gems/2.4.2/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/handle_storage_pool.rb:52:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/home/vlaskina/.vagrant.d/gems/2.4.2/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:227:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:202:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/environment.rb:631:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:188:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/machine.rb:188:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: XML error: CPU feature 'vmx' specified more than once

```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = 'kvm'
    libvirt.connect_via_ssh = false
    libvirt.username = 'root'
    libvirt.keymap = 'de'
    libvirt.cpus = 1
    libvirt.memory = 1024
    libvirt.nested = true
    libvirt.cpu_feature :name => 'vmx', :policy => 'require'
  end

```

**Are you using upstream vagrant package or your distros package?**
Upstream

**Comment by pronix** [comment]
confirmed. should i expect PR ? ;)

**Comment by anastasiiavlaskina** [comment]
WIP :)

**Comment by pronix** [comment]
https://github.com/vagrant-libvirt/vagrant-libvirt/pull/871
