### ISSUE TITLE
qemu_use_session and storage_pool_path no longer work

### ISSUE THREAD

**Issue by ladar** [vagrant-libvirt/vagrant-libvirt#902]
### Bug Description
Whenever I create a Vagrantfile with the settings qemu_use_session or storage_pool_path, vagrant up will terminate immediately with an error. Both settings are defined in the following file `vagrant-libvirt/lib/vagrant-libvirt/util/storage_util.rb` and without access to those attributes, it's impossible to create a user session box. With `uri = "qemu:///session"` defined, the `create_volume_xml` function will fail, with an error indicating it can't chown the base image. It seems that those settings are what override the `storage_pool_uid` and `storage_pool_gid` values. Because those overrides don't occur, I believe vagrant is trying to set the uid/gid to 0, aka root, and thus failing. 

### Actual behaviour

Including the above mentioned parameters in the Vagrantfile results in:
```
Libvirt Provider:
* The following settings shouldn't exist: qemu_use_session, storage_pool_path
```
Without those settings, a user session up operation results in (note, gem paths shortened for to avoid line wrapping/overflow and improve readability):
```
fog-libvirt-0.5.0/lib/fog/libvirt/requests/compute /create_volume.rb:6:in `create_volume_xml': 
  Call to virStorageVolCreateXML failed: cannot chown /home/ladar/.local/share/libvirt/images/
  lavabit-VAGRANTSLASH-magma_vagrant_box_image_1.8.12.img to (0, 0): Operation not 
  permitted (Libvirt::Error)
    from fog-libvirt-0.5.0/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume'
    from fog-libvirt-0.5.0/lib/fog/libvirt/models/compute/volume.rb:40:in `save'
    from fog-core-1.43.0/lib/fog/core/collection.rb:51:in `create'
    from vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/handle_box_image.rb:79:in `block in call'
    from vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/handle_box_image.rb:60:in `synchronize'
    from vagrant-libvirt-0.0.43/lib/vagrant-libvirt/action/handle_box_image.rb:60:in `call'
<snipped>
```
Finally, any attempt to override the uid/gid manually, also results in an error:
```
Libvirt Provider:
* The following settings shouldn't exist: storage_pool_gid, storage_pool_uid
```
### System configuration

Host: CentOS 7.5. 
Vagrant: 2.1.1
Libvirt Plugin: 0.0.43

### Vagrantfile
```
Vagrant.configure(2) do |config|
  config.vm.box = "lavabit/magma"
  config.vm.provider :libvirt do |v, override|
    v.uri = "qemu:///session"
    v.storage_pool_uid = 1000
    v.storage_pool_gid = 1000
    v.qemu_use_session = true
    v.storage_pool_path = "//home/user/Data/vagrant/magma-libvirt"
    v.driver = "qemu"
    v.graphics_type = "sdl"
    v.video_vram = 256
    v.memory = 1024
    v.cpus = 1
  end
end
```
### Graphics Type

I'm only attempting this because I want to create a Vagrantfile that will launch a graphical console. Something akin to the `gui = true` used by the other providers. As a result it's worth noting that despite what the docs say, `graphics_type = "gtk"` does not work. It results in `virDomainDefineXML` failing, with an unknown graphics device type. If I manually create a user session box, using the "sdl" option, I do get a graphical console. Unfortunately when using this option on a system hosted box, QEMU will fail because it lacks access to the display.

Note, that on my system, the `-display gtk` option is available, but using it results in an error indicating that GTK support is unavailable. This happens with `qemu-kvm` and `qemu-system-x86_64` binaries. However, while the `qemu-kvm` binary lacks SDL support, the `qemu-system-x86_64` does support SDL.

**Comment by ladar** [comment]
@ electrofelix I'm using the command:

```
vagrant plugin install vagrant-libvirt
```

Which indicates it is downloading, compiling and then installing the plugin locally? Is the commit you refenference on a different branch? I found the relevant documentation in the default README, so I assumed it was included with the build I received? I'd be happy to test a little more later this week... but need to know how I get the correct version installed?

**Comment by ladar** [comment]
@electrofelix I'm using the command:

```
vagrant plugin install vagrant-libvirt
```

Which indicates it is downloading, compiling and then installing the plugin locally? Is the commit you refenference on a different branch? I found the relevant documentation in the default README, so I assumed it was included with the build I received? I'd be happy to test a little more later this week... but need to know how I get the correct version installed?

**Comment by electrofelix** [comment]
@ladar The compiling refers to the ruby-libvirt gem which contains 'C' code that needs to be built in order for that gem to talk to libvirt.

If you use a locally built package from a clone of this repo would look something like the following:
```
$ git clone https://github.com/vagrant-libvirt/vagrant-libvirt
$ cd vagrant-libvirt
# assuming you have vagrant installed locally
$ GEM_HOME=/opt/vagrant/embedded/gems/ PATH=/opt/vagrant/embedded/bin:${PATH} rake build
vagrant-libvirt 0.0.43 built to pkg/vagrant-libvirt-0.0.43.gem.
vagrant-libvirt 0.0.43 built to pkg/vagrant-libvirt-0.0.43.gem.
$ vagrant plugin install pkg/vagrant-libvirt-0.0.43.gem
```

Otherwise you're just testing with the last version published to rubygems.

**Comment by Steap** [comment]
Hello!

I recently ran into the same issue.

```ruby
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpus = 1
    libvirt.driver = "kvm"
    libvirt.connect_via_ssh = false
    libvirt.uri = "qemu:///session"
    libvirt.storage_pool_name = "default"
  end

  config.vm.define "freebsd" do |freebsd|
    freebsd.vm.box = "generic/freebsd12"
  end

  config.vm.define "openbsd" do |openbsd|
    openbsd.vm.box = "generic/openbsd6"
  end
end
```

```console
$ vagrant up openbsd
...
/usr/lib/ruby/vendor_ruby/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume_xml': Call to virStorageVolCreateXML failed: cannot chown /home/cyril/.local/share/libvirt/images/generic-VAGRANTSLASH-openbsd6_vagrant_box_image_2.0.6.img to (0, 0): Operation not permitted (Libvirt::Error)
```
It works as expected when using qemu:///system.

I tried this on Debian Sid, with Vagrant 2.2.6 (Debian version, not upstream) and vagrant-libvirt (both from this git repository and using the Debian package).

**Comment by electrofelix** [comment]
Forgot to close this after the release containing this code had gone out.

@Steap sorry for the delay, that seems like a different issue and I'd have to suspect that you weren't getting the version of the plugin called that you thought you were, because the uid/gid code was well landed at that point and would not have used `(0, 0)` for the uid/gid.

```
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

Bringing machine 'openbsd' up with 'libvirt' provider...
==> openbsd: Checking if box 'generic/openbsd6' version '4.1.0' is up to date...
==> openbsd: Creating image (snapshot of base box volume).
==> openbsd: Creating domain with the following settings...
==> openbsd:  -- Name:              vagrant-libvirt_openbsd
==> openbsd:  -- Description:       Source: /home/electrofelix/git/github.com/vagrant-libvirt/vagrant-libvirt/Vagrantfile
==> openbsd:  -- Domain type:       kvm
==> openbsd:  -- Cpus:              1
==> openbsd:  -- Feature:           acpi
==> openbsd:  -- Feature:           apic
==> openbsd:  -- Feature:           pae
==> openbsd:  -- Clock offset:      utc
==> openbsd:  -- Memory:            1024M
==> openbsd:  -- Management MAC:    
==> openbsd:  -- Loader:            
==> openbsd:  -- Nvram:             
==> openbsd:  -- Base box:          generic/openbsd6
==> openbsd:  -- Storage pool:      default
==> openbsd:  -- Image(sda):        /home/electrofelix/.local/share/libvirt/images/vagrant-libvirt_openbsd.img, scsi, 128G
==> openbsd:  -- Disk driver opts:  cache='default'
==> openbsd:  -- Kernel:            
==> openbsd:  -- Initrd:            
==> openbsd:  -- Graphics Type:     vnc
==> openbsd:  -- Graphics Port:     -1
==> openbsd:  -- Graphics IP:       127.0.0.1
==> openbsd:  -- Graphics Password: Not defined
==> openbsd:  -- Video Type:        cirrus
==> openbsd:  -- Video VRAM:        256
==> openbsd:  -- Video 3D accel:    false
==> openbsd:  -- Sound Type:	
==> openbsd:  -- Keymap:            en-us
==> openbsd:  -- TPM Backend:       passthrough
==> openbsd:  -- TPM Path:          
==> openbsd:  -- INPUT:             type=mouse, bus=ps2
==> openbsd: Creating shared folders metadata...
==> openbsd: Starting domain.
==> openbsd: Waiting for domain to get an IP address...
==> openbsd: Waiting for machine to boot. This may take a few minutes...
    openbsd: SSH address: 192.168.122.115:22
    openbsd: SSH username: vagrant
    openbsd: SSH auth method: private key
    openbsd: Warning: Connection refused. Retrying...
    openbsd: 
    openbsd: Vagrant insecure key detected. Vagrant will automatically replace
    openbsd: this with a newly generated keypair for better security.
    openbsd: 
    openbsd: Inserting generated public key within guest...
    openbsd: Removing insecure key from the guest if it's present...
    openbsd: Key inserted! Disconnecting and reconnecting using new SSH key...
==> openbsd: Machine booted and ready!
```

**Comment by rafutek** [comment]
Hello,

I am trying to connect to an hypervisor with this config :
```
config.vm.provider "libvirt" do |v|
    v.qemu_use_session = true
    v.uri = "qemu+ssh://#{libvirt_user}@#{libvirt_host}/session"
    v.management_network_device = bridge_name
    ...
end
```

But I end up with this error message : 

> Call to virStorageVolCreateXML failed: cannot chown /home/me/.local/share/libvirt/images/generic-VAGRANTSLASH-rocky8_vagrant_box_image_4.2.14_box.img to (1001, 1001): Operation not permitted

Creating the machine (with the same URI) directly on the host works, so it might be an issue with user permissions. Indeed, 1001 is my local user, not the user on the hypervisor machine. The uid and gid used should be the one of the user connected through ssh right ? [It seems to not be the case](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/0.11.2/lib/vagrant-libvirt/util/storage_util.rb). 


However, I tried with a local user with the same uid and gid, and it gave this error :

> Error while connecting to Libvirt: Error making a connection to libvirt URI qemu:///system:
Call to virConnectOpen failed: authentication unavailable: no polkit agent available to authenticate action 'org.libvirt.unix.manage'

Using vagrant-libvirt 0.11.2

Thank you

**Comment by electrofelix** [comment]
@rafutek I think best to record this as a new issue as there is an issue with resolving the correct paths and uid/gid for remote libvirt when using qemu session.

https://github.com/vagrant-libvirt/vagrant-libvirt/blob/9e7d0f3ec8c7b9c673672b801ec58e5926c08dfb/lib/vagrant-libvirt/util/storage_util.rb#L18-L22 needs to be adjusted to expand based on the remote user connection. Probably better if it queried libvirt for the path from the pool xml similar to what the following two commands would return:
```
virsh -c qemu:///system pool-dumpxml default
```
or
```
virsh -c qemu:///session pool-dumpxml default
```

Now you can override the path to explicitly set it, by ensuring the storage_pool_path is set https://github.com/vagrant-libvirt/vagrant-libvirt/blob/9e7d0f3ec8c7b9c673672b801ec58e5926c08dfb/lib/vagrant-libvirt/util/storage_util.rb#L16 by setting the config option `storage_pool_path` which it appears is undocumented as well.

Resolving the uid/gid detected at https://github.com/vagrant-libvirt/vagrant-libvirt/blob/9e7d0f3ec8c7b9c673672b801ec58e5926c08dfb/lib/vagrant-libvirt/util/storage_util.rb#L7-L13 might take a little more work as there doesn't appear to be a way to query that from libvirt. So I expect it'll need to use ssh directly and cache the result along with providing a mechanism to override the detected value if there is some issue connecting as the user using ssh directly.
