### ISSUE TITLE
impossible to create private_network static IP with only an IPv6

### ISSUE THREAD

**Issue by lelutin** [vagrant-libvirt/vagrant-libvirt#914]
Hi,

vagrant-libvirt offers IPv6 support for private addresses, as shown in the README. However, I find that it's impossible to setup a network interface of type `:private_network` with only an IPv6 address.

I've tried to give an IPv6 address to `:ip` as shown in the [vagrant private_network examples](https://www.vagrantup.com/docs/networking/private_network.html#ipv6), but this shows a ruby stack trace that says the ipaddress is invalid.

dropping `:ip` and using only the `:libvirt__ipv6*` parameters errors out in another way since not having the `:ip` parameter means requesting dhcp.

is the provider not accepting an IPv6 address in the `:ip` parameter for `config.vm.network` because of a constraint in how libvirt operates? or do you think that it would be possible to make some changes to setup an IPv6-only private_network address?

**Comment by mykaul** [comment]
I've had a similar problem with mixed IPv4 and IPv6 - I suspect it has to do with:
1. What libvirt does and what Vagrant does. I suspect static IP allocation is done with IPv4 via Vagrant - unsure what does it with IPv6?
2. It seems to recreate the network, so the last 'creation' wins.

Here's a snippet of my code:
```
    (1..node_count).reverse_each do |num|
      config.vm.define "node-#{num}" do |node|
        vm_ip = "192.168.250.#{num+10}"
        vm_ip6 = "fddd::#{num+10}"

        node.vm.box = "centos/7"
        node.vm.network :private_network,
            :ip => vm_ip,
            :libvirt__driver_queues => "#{cpus}",
            :libvirt__guest_ipv6 => "yes",
            :libvirt__ipv6_address => vm_ip6,
            :libvirt__ipv6_prefix => "64"
```

The resulting network, in libvirt:
```
<network connections='3' ipv6='yes'>
  <name>vg0</name>
  <uuid>d6ee89af-4df3-46ee-b265-0ee8b3e596db</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr2' stp='on' delay='0'/>
  <mac address='52:54:00:62:ef:2d'/>
  <ip address='192.168.250.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.250.1' end='192.168.250.254'/>
    </dhcp>
  </ip>
  <ip family='ipv6' address='fddd::13' prefix='64'>
  </ip>
</network>
```

I would expect:
1. All addresses to appear in the XML, not just 'fddd::13'.
2. There's a missing connection between the interface and the IP. This could be done using the 'id' field or something.
3. It's unclear to me what Vagrant does here.

**Comment by electrofelix** [comment]
@lelutin I don't make much use of ipv6 myself yet, but if you could provide the full stack trace then might be able to track it down.

I'm guessing the code is growing through https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/create_networks.rb#L75 and then https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/create_networks.rb#L132 which in turn calls into a vagrant library. At which point it likely gets an error because the code is probably not handling changing the netmask which is defaulted to `255.255.255.0` in https://github.com/vagrant-libvirt/vagrant-libvirt/blob/39f9a9d0b455a358917290417bb447396c245034/lib/vagrant-libvirt/util/network_util.rb#L94-L99

I suspect that probably need to do something like https://github.com/hashicorp/vagrant/blob/b886ec0b323163920202baec6424b64ccfcc56bc/plugins/providers/virtualbox/action/network.rb#L487-L490 in order to handle it correctly, but really need the stack trace in order to look at it closer.


@mykaul your issue is different in that you are using both IPv4 and IPv6, please don't hijack other peoples issues unless it is actually the same. Please file a separate issue taking into account my next comment.

I'm not sure why you would expect all addresses to appear in the network XML definition, it should just contain the network details rather than specific IPs for each machine unless you are assigning specific IPs via DHCP. Check out https://libvirt.org/formatnetwork.html#examplesNAT while the domain (machine) XML contains the address for static assigned see https://libvirt.org/formatdomain.html#ipconfig. AFAICR vagrant-libvirt need only allocate it's management network and once accessible vagrant will enter the VM brought up via that network to assign static IPs directly so in general you'll only see static IPs if using them for the management config. Looking at the network XML generated there is likely a bug in how the network address for IPv6 is being determined, but I'd rather work that as a separate issue.

**Comment by lelutin** [comment]
@electrofelix oops! wow indeed: I'm re-reading my original report and I don't know why I left this out.

with the following Vagrantfile (the base box used is a self-built vanilla debian stretch):

~~~
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define :stretch do |st|
    st.vm.box = "debian-9-amd64"
    config.vm.network "private_network", ip: "fde4:8dba:82e1::c4"
  end
end
~~~

I get this output with the stack trace towards the end:

~~~
$ vagrant up stretch
Bringing machine 'stretch' up with 'libvirt' provider...
==> stretch: Creating image (snapshot of base box volume).
==> stretch: Creating domain with the following settings...
==> stretch:  -- Name:              mgmt_stretch
==> stretch:  -- Domain type:       kvm
==> stretch:  -- Cpus:              1
==> stretch:  -- Feature:           acpi
==> stretch:  -- Feature:           apic
==> stretch:  -- Feature:           pae
==> stretch:  -- Memory:            512M
==> stretch:  -- Management MAC:    
==> stretch:  -- Loader:            
==> stretch:  -- Nvram:             
==> stretch:  -- Base box:          debian-9-amd64
==> stretch:  -- Storage pool:      default
==> stretch:  -- Image:             /var/lib/libvirt/images/mgmt_stretch.img (10G)
==> stretch:  -- Volume Cache:      default
==> stretch:  -- Kernel:            
==> stretch:  -- Initrd:            
==> stretch:  -- Graphics Type:     vnc
==> stretch:  -- Graphics Port:     -1
==> stretch:  -- Graphics IP:       127.0.0.1
==> stretch:  -- Graphics Password: Not defined
==> stretch:  -- Video Type:        cirrus
==> stretch:  -- Video VRAM:        9216
==> stretch:  -- Sound Type:	
==> stretch:  -- Keymap:            en-us
==> stretch:  -- TPM Path:          
==> stretch:  -- INPUT:             type=mouse, bus=ps2
==> stretch: Creating shared folders metadata...
Traceback (most recent call last):
	62: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	61: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/machine.rb:194:in `action'
	60: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/machine.rb:194:in `call'
	59: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/environment.rb:614:in `lock'
	58: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/machine.rb:208:in `block in action'
	57: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/machine.rb:239:in `action_raw'
	56: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `run'
	55: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/util/busy.rb:19:in `busy'
	54: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `block in run'
	53: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/builder.rb:116:in `call'
	52: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	51: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	50: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	49: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/builtin/box_check_outdated.rb:36:in `call'
	48: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	47: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/builtin/call.rb:53:in `call'
	46: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `run'
	45: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/util/busy.rb:19:in `busy'
	44: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `block in run'
	43: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/builder.rb:116:in `call'
	42: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	41: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	40: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	39: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	38: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	37: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_storage_pool.rb:57:in `call'
	36: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	35: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	34: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	33: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_box_image.rb:146:in `call'
	32: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	31: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_domain_volume.rb:83:in `call'
	30: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	29: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_domain.rb:333:in `call'
	28: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	27: from /usr/lib/ruby/vendor_ruby/vagrant-cachier/action/configure_bucket_root.rb:20:in `call'
	26: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	25: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/builtin/provision.rb:80:in `call'
	24: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	23: from /usr/lib/ruby/vendor_ruby/vagrant-cachier/action/install_buckets.rb:14:in `call'
	22: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	21: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
	20: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	19: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	18: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	17: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	16: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	15: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	14: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	13: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:18:in `call'
	12: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	11: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/share_folders.rb:20:in `call'
	10: from /usr/share/rubygems-integration/all/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
	 9: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:38:in `call'
	 8: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:38:in `synchronize'
	 7: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:41:in `block in call'
	 6: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:41:in `each'
	 5: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:75:in `block (2 levels) in call'
	 4: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:136:in `handle_ip_option'
	 3: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:275:in `get_host_ip_addr'
	 2: from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:275:in `new'
	 1: from /usr/lib/ruby/2.5.0/ipaddr.rb:586:in `initialize'
/usr/lib/ruby/2.5.0/ipaddr.rb:649:in `in6_addr': invalid address (IPAddr::InvalidAddressError)
~~~

If I change the Vagrantfile to the following (just adding a netmask parameter):

~~~
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define :stretch do |st|
    st.vm.box = "debian-9-amd64"
    config.vm.network "private_network", ip: "fde4:8dba:82e1::c4", netmask: "96"
  end
end
~~~

I get no stack trace but an error about no "family" specified for non IPv4 address:

~~~
 vagrant up stretch
Bringing machine 'stretch' up with 'libvirt' provider...
==> stretch: Creating image (snapshot of base box volume).
==> stretch: Creating domain with the following settings...
==> stretch:  -- Name:              mgmt_stretch
==> stretch:  -- Domain type:       kvm
==> stretch:  -- Cpus:              1
==> stretch:  -- Feature:           acpi
==> stretch:  -- Feature:           apic
==> stretch:  -- Feature:           pae
==> stretch:  -- Memory:            512M
==> stretch:  -- Management MAC:    
==> stretch:  -- Loader:            
==> stretch:  -- Nvram:             
==> stretch:  -- Base box:          debian-9-amd64
==> stretch:  -- Storage pool:      default
==> stretch:  -- Image:             /var/lib/libvirt/images/mgmt_stretch.img (10G)
==> stretch:  -- Volume Cache:      default
==> stretch:  -- Kernel:            
==> stretch:  -- Initrd:            
==> stretch:  -- Graphics Type:     vnc
==> stretch:  -- Graphics Port:     -1
==> stretch:  -- Graphics IP:       127.0.0.1
==> stretch:  -- Graphics Password: Not defined
==> stretch:  -- Video Type:        cirrus
==> stretch:  -- Video VRAM:        9216
==> stretch:  -- Sound Type:	
==> stretch:  -- Keymap:            en-us
==> stretch:  -- TPM Path:          
==> stretch:  -- INPUT:             type=mouse, bus=ps2
==> stretch: Creating shared folders metadata...
Error occurred while creating new network: Call to virNetworkDefineXML failed: unsupported configuration: no family specified for non-IPv4 address 'fde4:8dba:82e1::1' in network 'mgmt0'.
~~~

**Comment by electrofelix** [comment]
@lelutin thanks, that looks to be sufficient to dig into this, I'll probably will need to add some unit tests to make sure the various network configurations produce valid results as I suspect this is a case that most were only using ipv4 behaviour so the code for ipv6 support wasn't fully tested.

Yeah, the first one makes sense in that we're simply not switching to an IPv6 netmask, probably some simple checking and switching default netmask will solve that. But obviously once past that running into probably more missing configuration. Probably not too difficult to fix, just a case of template needs to set additional parameters when using ipv6, hopefully will get to it over the next week.

**Comment by martin-schwenke** [comment]
This issue is affecting me and it doesn't seem to be getting much love, so I'll weigh in with an opinion on the correct way of fixing it...

The first thing to do is read [the Vagrant private network documentation](https://www.vagrantup.com/docs/networking/private_network.html)!

vagrant-libvirt should obey [the principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) and behave according to that documentation.  It should not be necessary to use any of the 20 custom vagrant-libvirt private network options, including IPv6-specific options, to get an IPv6 address on an interface.  If a single IP address is given and that IP address happens to be an IPv6 address then it should just work...

Following from that, if vagrant-libvirt provides extensions to put multiple IP addresses on private interfaces then it should simply allow extra addresses (IPv6 or IPv6) to be specified.  However, I'm not very convinced that there is value in putting multiple addresses on private interfaces.  If that feature was wanted by a lot of Vagrant users then it would be documented as an upstream Vagrant feature.  Putting IPv4 and IPv6 addresses on separate private networks should work just fine.

i don't mean to "rock the boat" but I think the solution here is to make things simpler instead of making them more complicated...

**Comment by jchook** [comment]
Any update on this issue? 

Hopefully a minimal fix is possible to input the correct IPv6 prefix into `NetworkIp#network_address`?

**Comment by electrofelix** [comment]
Unfortunately quite a few things to be worked on and not enough time. Main thing still missing is unit tests around the networking behaviour. There are some integration tests that might be able to be extended to cover this, but again combination of time and lack of familiarity around the networking parts of the code have meant I've ended up improving testability of other areas first ahead of it.
