### ISSUE TITLE
Feature request: support libvirt.usb_controller 'None' model

### ISSUE THREAD

**Issue by mykaul** [vagrant-libvirt/vagrant-libvirt#944]
### Steps to reproduce
1. Try to use 'None' as a USB controller (a legit libvirt setting).
2. This fails with vagrant-libvirt.

### Expected behaviour
Should run a VM without a USB controller. It's not needed in many cases.

### Actual behaviour
There's a default USB controller.

### System configuration
**OS/Distro version:**:
Fedora 29
**Libvirt version:**
libvirt-daemon-4.7.0-1.fc29.x86_64

**Output of `vagrant version; vagrant plugin list`:**
[ykaul@ykaul cockpit-gluster]$ vagrant version
==> vagrant: A new version of Vagrant is available: 2.2.1!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

Installed Version: 2.1.2
Latest Version: 2.2.1
 
To upgrade to the latest version, visit the downloads page and
download and install the latest version of Vagrant from the URL
below:

  https://www.vagrantup.com/downloads.html

If you're curious what changed in the latest release, view the
CHANGELOG below:

  https://github.com/hashicorp/vagrant/blob/v2.2.1/CHANGELOG.md
Creating 1 clusters.
Creating 3 nodes.
Creating 2 disks(20G) each.
Using 120 GB!.
[ykaul@ykaul cockpit-gluster]$ vagrant plugin list
Creating 1 clusters.
Creating 3 nodes.
Creating 2 disks(20G) each.
Using 120 GB!.
vagrant-libvirt (0.0.40, system)

**Output of `VAGRANT_LOG=debug vagrant ... --provider=libvirt`**
```
Insert debug output inside quotes here (replace ... with whatever command you use to trigger the issue)
```

**A Vagrantfile to reproduce the issue:**
```
Insert Vagrantfile inside quotes here (remove sensitive data if needed)
```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by davidscaife** [comment]
It looks like you're using 0.0.40? Support for configuring the USB controller was added in #861 which was merged/released in 0.0.44. The fact that a USB controller is added by default flows from libvirt's own default behaviour - it needs to explicitly be told to not add a controller.

I guess you should be able to run `vagrant plugin update vagrant-libvirt` to pull down the latest version, then once it's updated you'll be able to set `libvirt.usb_controller :model => "none"`.

**Comment by mykaul** [comment]
```
[ykaul@ykaul ~]$ sudo vagrant plugin update 
[sudo] password for ykaul: 
==> vagrant: A new version of Vagrant is available: 2.2.1!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

Updating installed plugins...
/usr/share/gems/gems/psych-3.0.2/lib/psych.rb:232: warning: already initialized constant Psych::LIBYAML_VERSION
/usr/share/ruby/psych.rb:232: warning: previous definition of LIBYAML_VERSION was here
/usr/share/gems/gems/psych-3.0.2/lib/psych.rb:234: warning: already initialized constant Psych::FALLBACK
/usr/share/ruby/psych.rb:234: warning: previous definition of FALLBACK was here
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-libvirt (> 0)'
[ykaul@ykaul ~]$ sudo vagrant plugin list
vagrant-libvirt (0.0.40, system)
```

**Comment by davidscaife** [comment]
I see that F29's vagrant-libvirt package is a bit stale. But you ought to be able to run the above update command as an unprivileged user, without sudo, to pull down the latest plugin version (but it will only be available for that user).

I'm not sure how a user-local update command interacts with system-installed plugins, so if the update command still fails, try `vagrant plugin install vagrant-libvirt` (again, without sudo) instead.

**Comment by mykaul** [comment]
@davidscaife - thanks, but I've tried first without sudo, and it failed in exactly the same manner.
I've also noticed the RPM is a bit outdated - unsure how to push it forward (and if the CentOS RPM works on F29? Who knows?)

The plugin install failed:
```
[ykaul@ykaul ~]$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
/usr/share/gems/gems/psych-3.0.2/lib/psych.rb:232: warning: already initialized constant Psych::LIBYAML_VERSION
/usr/share/ruby/psych.rb:232: warning: previous definition of LIBYAML_VERSION was here
/usr/share/gems/gems/psych-3.0.2/lib/psych.rb:234: warning: already initialized constant Psych::FALLBACK
/usr/share/ruby/psych.rb:234: warning: previous definition of FALLBACK was here
Traceback (most recent call last):
	16: from /usr/share/vagrant/gems/bin/vagrant:23:in `<main>'
	15: from /usr/share/vagrant/gems/bin/vagrant:23:in `load'
	14: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/bin/vagrant:161:in `<top (required)>'
	13: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/environment.rb:275:in `cli'
	12: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/cli.rb:54:in `execute'
	11: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/plugins/commands/plugin/command/root.rb:66:in `execute'
	10: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/plugins/commands/plugin/command/install.rb:31:in `execute'
	 9: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/plugins/commands/plugin/command/install.rb:31:in `each'
	 8: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	 7: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/plugins/commands/plugin/command/base.rb:14:in `action'
	 6: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `run'
	 5: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/util/busy.rb:19:in `busy'
	 4: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:66:in `block in run'
	 3: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/builder.rb:116:in `call'
	 2: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/action/warden.rb:34:in `call'
	 1: from /usr/share/vagrant/gems/gems/vagrant-2.1.2/plugins/commands/plugin/action/install_gem.rb:29:in `call'
/usr/share/vagrant/gems/gems/vagrant-2.1.2/lib/vagrant/plugin/manager.rb:79:in `install_plugin': undefined method `name' for nil:NilClass (NoMethodError)
```

**Comment by mykaul** [comment]
Removed the vagrant-libvirt RPM, and now it almost succeeded:
```
[ykaul@ykaul ~]$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
/usr/share/gems/gems/psych-3.0.2/lib/psych.rb:232: warning: already initialized constant Psych::LIBYAML_VERSION
/usr/share/ruby/psych.rb:232: warning: previous definition of LIBYAML_VERSION was here
/usr/share/gems/gems/psych-3.0.2/lib/psych.rb:234: warning: already initialized constant Psych::FALLBACK
/usr/share/ruby/psych.rb:234: warning: previous definition of FALLBACK was here
Fetching: builder-3.2.3.gem (100%)
Fetching: excon-0.62.0.gem (100%)
Fetching: formatador-0.2.5.gem (100%)
Fetching: fog-core-1.43.0.gem (100%)
Fetching: multi_json-1.13.1.gem (100%)
Fetching: fog-json-1.2.0.gem (100%)
Fetching: mini_portile2-2.3.0.gem (100%)
Fetching: nokogiri-1.8.5.gem (100%)
Building native extensions. This could take a while...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

ERROR: Failed to build gem native extension.

    current directory: /home/ykaul/.vagrant.d/gems/2.5.3/gems/nokogiri-1.8.5/ext/nokogiri
/usr/bin/ruby -r ./siteconf20181121-14337-1lkg6dv.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /home/ykaul/.vagrant.d/gems/2.5.3/gems/nokogiri-1.8.5 for inspection.
Results logged to /home/ykaul/.vagrant.d/gems/2.5.3/extensions/x86_64-linux/2.5.0/nokogiri-1.8.5/gem_make.out
```

**Comment by davidscaife** [comment]
Possibly need to install the ruby-devel package?

**Comment by mykaul** [comment]
Almost (perhaps another -devel is missing?):
```
Building native extensions. This could take a while...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

ERROR: Failed to build gem native extension.

    current directory: /home/ykaul/.vagrant.d/gems/2.5.3/gems/ruby-libvirt-0.7.1/ext/libvirt
/usr/bin/ruby -r ./siteconf20181121-17567-wgnhm5.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
	--with-libvirt-include
	--without-libvirt-include
	--with-libvirt-lib
	--without-libvirt-lib
	--with-libvirt-config
	--without-libvirt-config
	--with-pkg-config
	--without-pkg-config
extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/ykaul/.vagrant.d/gems/2.5.3/extensions/x86_64-linux/2.5.0/ruby-libvirt-0.7.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/ykaul/.vagrant.d/gems/2.5.3/gems/ruby-libvirt-0.7.1 for inspection.
Results logged to /home/ykaul/.vagrant.d/gems/2.5.3/extensions/x86_64-linux/2.5.0/ruby-libvirt-0.7.1/gem_make.out

```

And /home/ykaul/.vagrant.d/gems/2.5.3/extensions/x86_64-linux/2.5.0/ruby-libvirt-0.7.1/mkmf.log has:
```
"pkg-config --exists libvirt"
package configuration for libvirt is not found
```

I've install rubygem-ruby-libvirt RPM, and that solved it!
```
[ykaul@ykaul ~]$ sudo dnf install rubygem-ruby-libvirt
Last metadata expiration check: 1:50:14 ago on Wed 21 Nov 2018 12:27:58 PM IST.
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                                     Arch                                          Version                                             Repository                                     Size
===================================================================================================================================================================================================================
Installing:
 rubygem-ruby-libvirt                                        x86_64                                        0.7.1-3.fc29                                        fedora                                         91 k

Transaction Summary
===================================================================================================================================================================================================================
Install  1 Package

Total download size: 91 k
Installed size: 275 k
Is this ok [y/N]: y
Downloading Packages:
rubygem-ruby-libvirt-0.7.1-3.fc29.x86_64.rpm                                                                                                                                        48 kB/s |  91 kB     00:01    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                               23 kB/s |  91 kB     00:03     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                           1/1 
Installed: rubygem-ruby-libvirt-0.7.1-3.fc29.x86_64
  Installing       : rubygem-ruby-libvirt-0.7.1-3.fc29.x86_64                                                                                                                                                  1/1 
Installed: rubygem-ruby-libvirt-0.7.1-3.fc29.x86_64
  Running scriptlet: rubygem-ruby-libvirt-0.7.1-3.fc29.x86_64                                                                                                                                                  1/1 
  Verifying        : rubygem-ruby-libvirt-0.7.1-3.fc29.x86_64                                                                                                                                                  1/1 

Installed:
  rubygem-ruby-libvirt-0.7.1-3.fc29.x86_64                                                                                                                                                                         

Complete!
[ykaul@ykaul ~]$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
/usr/share/gems/gems/psych-3.0.2/lib/psych.rb:232: warning: already initialized constant Psych::LIBYAML_VERSION
/usr/share/ruby/psych.rb:232: warning: previous definition of LIBYAML_VERSION was here
/usr/share/gems/gems/psych-3.0.2/lib/psych.rb:234: warning: already initialized constant Psych::FALLBACK
/usr/share/ruby/psych.rb:234: warning: previous definition of FALLBACK was here
Building native extensions. This could take a while...
Fetching: fog-libvirt-0.5.0.gem (100%)
Fetching: vagrant-libvirt-0.0.45.gem (100%)
Installed the plugin 'vagrant-libvirt (0.0.45)'!
```

Now I'll need to see how to get rid of the serial device and replace it with virtio-serial ;-)

Thanks!
