### ISSUE TITLE
Not possible to create network without IP address defined?

### ISSUE THREAD

**Issue by attila123** [vagrant-libvirt/vagrant-libvirt#967]
### Steps to reproduce
1. With virsh I can create a network without dhcp, without any ip address range / limitation (in my scenario the IP range/netmark changes in this network (during an installation procedure)), and with specifying a bridge interface name (I will use it for another, virt-inst installed VM (where I do not want to use NAT (AFAIK, a NAT-ed NIC (the 1st one) is mandatory for vagrant)). To do that I create an XML file e.g. (see https://libvirt.org/formatnetwork.html):
```
<network>
  <name>my-internal-net</name>
  <bridge name="virbr100" />
</network>
```
then to create it: `sudo virsh net-create --file my-internal-net.xml`.

To verify it has been created correctly:
```
$ sudo virsh net-dumpxml my-internal-net
<network>
  <name>my-internal-net</name>
  <uuid>e44844f1-25cd-4c9a-88cc-4769208f46ce</uuid>
  <bridge name='virbr100' stp='on' delay='0'/>
  <mac address='52:54:00:7d:d7:17'/>
</network>
```
2. I tried to create such a network in Vagrantfile:
```
  config.vm.network :private_network,
    :libvirt__network_name => 'my-internal-net',
    :libvirt__dhcp_enabled => false,
    :libvirt__forward_mode => 'none'
```
However, at 'vagrant up' I get the following error:

"Error occurred while creating new network: Call to virNetworkDefineXML failed: XML error: Missing required address attribute in network 'my-internal-net'."

However if I specify some ip, e.g. `:ip => "192.168.177.1",` then the dumped XML is very similar to what I want to achieve:

```
$ sudo virsh net-dumpxml my-internal-net
<network ipv6='yes'>
  <name>my-internal-net</name>
  <uuid>a2419c46-dbdc-4460-9a54-2fed401da755</uuid>
  <bridge name='virbr2' stp='on' delay='0'/>
  <mac address='52:54:00:91:b5:6c'/>
  <ip address='192.168.177.1' netmask='255.255.255.0'>
  </ip>
</network>
```
but I do not want the IP address to be set.

### Expected behaviour
I should be able to specify no IP address. Optionally I should be able to specify a concrete bridge name (although in my case I can easily parse it from the `virsh net-dumpxml` output).

### Actual behaviour
This does not seems to be possible, see error message above.

### System configuration
**OS/Distro version:**
current Manjaro Linux / does not matter

**Libvirt version:**
community/libvirt 4.9.0-2

**Output of `vagrant version; vagrant plugin list`:**
```
$ vagrant version
Installed Version: 2.2.3
Latest Version: 2.2.3
 
You're running an up-to-date version of Vagrant!
$ vagrant plugin list
vagrant-docker-compose (1.3.0, global)
  - Version Constraint: > 0
vagrant-ignition (0.0.3, global)
  - Version Constraint: > 0
vagrant-libvirt (0.0.45, global)
vagrant-openstack-provider (0.13.0, global)
  - Version Constraint: > 0
vagrant-proxyconf (2.0.0, global)
  - Version Constraint: > 0
vagrant-vbguest (0.17.1, global)
```
**Output of `VAGRANT_LOG=debug vagrant up --no-provision --provider=libvirt` (relevant parts)**
```
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CreateNetworks:0x000055bbb930b180>
 INFO create_networks: Using vagrant-libvirt at 192.168.121.0/24 as the management network nat is the mode
DEBUG create_networks: In config found network type private_network options {:libvirt__network_name=>"my-internal-net", :libvirt__dhcp_enabled=>false, :libvirt__forward_mode=>"none", :protocol=>"tcp", :id=>"f518c08e-5657-4c2f-86ff-8dba6e846c97"}

...

DEBUG create_networks: Searching for network with options {:iface_type=>:private_network, :netmask=>"255.255.255.0", :dhcp_enabled=>false, :forward_mode=>"none", :libvirt__network_name=>"my-internal-net", :libvirt__dhcp_enabled=>false, :libvirt__forward_mode=>"none", :protocol=>"tcp", :id=>"f518c08e-5657-4c2f-86ff-8dba6e846c97", :network_name=>"my-internal-net"}
DEBUG create_networks: looking up network named my-internal-net
DEBUG create_networks: generating name for bridge
DEBUG create_networks: looking up bridge named virbr0
DEBUG create_networks: looking up bridge named virbr1
DEBUG create_networks: looking up bridge named virbr2
DEBUG create_networks: found available bridge name virbr2
ERROR warden: Error occurred: Error occurred while creating new network: Call to virNetworkDefineXML failed: XML error: Missing required address attribute in network 'my-internal-net'.

...

ERROR warden: Error occurred: Error occurred while creating new network: Call to virNetworkDefineXML failed: XML error: Missing required address attribute in network 'my-internal-net'.

...

ERROR warden: Error occurred: Error occurred while creating new network: Call to virNetworkDefineXML failed: XML error: Missing required address attribute in network 'my-internal-net'.

...

 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x000055bbb94c4288>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::ProviderLibvirt::Errors::CreateNetworkError: Error occurred while creating new network: Call to virNetworkDefineXML failed: XML error: Missing required address attribute in network 'my-internal-net'.>
ERROR vagrant: Error occurred while creating new network: Call to virNetworkDefineXML failed: XML error: Missing required address attribute in network 'my-internal-net'.

...

 INFO interface: error: Error occurred while creating new network: Call to virNetworkDefineXML failed: XML error: Missing required address attribute in network 'my-internal-net'.
Error occurred while creating new network: Call to virNetworkDefineXML failed: XML error: Missing required address attribute in network 'my-internal-net'.
 INFO interface: Machine: error-exit ["VagrantPlugins::ProviderLibvirt::Errors::CreateNetworkError", "Error occurred while creating new network: Call to virNetworkDefineXML failed: XML error: Missing required address attribute in network 'my-internal-net'."]
```

**A Vagrantfile to reproduce the issue:**
```
Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"

  config.vm.box_check_update = false

  config.vm.hostname = "vagrant-libvirt-issue-report"

  # https://github.com/vagrant-libvirt/vagrant-libvirt#networks
  config.vm.network :private_network,
    :libvirt__network_name => 'my-internal-net',
    :libvirt__dhcp_enabled => false,
    #:ip => "192.168.177.1",
    :libvirt__forward_mode => 'none'

  # https://github.com/vagrant-libvirt/vagrant-libvirt#domain-specific-options
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 512
    libvirt.cpus = 2
    # libvirt.cputopology :sockets => '2', :cores => '2', :threads => '1'
    # Older virt-manager GUI / qemu may not work correctly with the 'spice' type, in this case 'vnc' is often recommended.
    libvirt.graphics_type = 'vnc'
  end

end
```

**Are you using upstream vagrant package or your distros package?**
Distro

**Comment by electrofelix** [comment]
This looks like you want to create something like https://libvirt.org/formatnetwork.html#examplesNoGateway you can do this by setting `:libvirt__forward_mode` to `very_isolated` as opposed to `none`.

**Comment by attila123** [comment]
@electrofelix thx for the idea. However:
with the following Vagrantfile (using `very_isolated`):
```
Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"

  config.vm.box_check_update = false

  config.vm.hostname = "vagrant-libvirt-issue-report"

  # https://github.com/vagrant-libvirt/vagrant-libvirt#networks
  config.vm.network :private_network,
    :libvirt__network_name => 'my-internal-net',
    :libvirt__dhcp_enabled => false,
    #:ip => "192.168.177.1",
    :libvirt__forward_mode => 'very_isolated'

  # https://github.com/vagrant-libvirt/vagrant-libvirt#domain-specific-options
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 512
    libvirt.cpus = 2
    # libvirt.cputopology :sockets => '2', :cores => '2', :threads => '1'
    # Older virt-manager GUI / qemu may not work correctly with the 'spice' type, in this case 'vnc' is often recommended.
    libvirt.graphics_type = 'vnc'
  end

end
```
`vagrant up` still complains about the missing required attribute:
```
$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              vagrant-libvirt-bugreport2_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              2
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Memory:            512M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Nvram:             
==> default:  -- Base box:          generic/ubuntu1804
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/vagrant-libvirt-bugreport2_default.img (32G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     -1
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        256
==> default:  -- Sound Type:	
==> default:  -- Keymap:            en-us
==> default:  -- TPM Path:          
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default: Creating shared folders metadata...
Error occurred while creating new network: Call to virNetworkDefineXML failed: XML error: Missing required address attribute in network 'my-internal-net'.
```
Also, if I remove (comment out) the libvirt__dhcp_enabled, then vagrant-libvirt crashes (instead of giving a meaningful error message):

```
Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"

  config.vm.box_check_update = false

  config.vm.hostname = "vagrant-libvirt-issue-report"

  # https://github.com/vagrant-libvirt/vagrant-libvirt#networks
  config.vm.network :private_network,
    :libvirt__network_name => 'my-internal-net',
    #:libvirt__dhcp_enabled => false,
    #:ip => "192.168.177.1",
    :libvirt__forward_mode => 'very_isolated'

  # https://github.com/vagrant-libvirt/vagrant-libvirt#domain-specific-options
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 512
    libvirt.cpus = 2
    # libvirt.cputopology :sockets => '2', :cores => '2', :threads => '1'
    # Older virt-manager GUI / qemu may not work correctly with the 'spice' type, in this case 'vnc' is often recommended.
    libvirt.graphics_type = 'vnc'
  end

end
```
```
$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              vagrant-libvirt-bugreport2_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              2
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Memory:            512M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Nvram:             
==> default:  -- Base box:          generic/ubuntu1804
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/vagrant-libvirt-bugreport2_default.img (32G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     -1
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        256
==> default:  -- Sound Type:	
==> default:  -- Keymap:            en-us
==> default:  -- TPM Path:          
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default: Creating shared folders metadata...
Traceback (most recent call last):
	59: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	58: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/machine.rb:194:in `action'
	57: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/machine.rb:194:in `call'
	56: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/environment.rb:614:in `lock'
	55: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/machine.rb:208:in `block in action'
	54: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/machine.rb:239:in `action_raw'
	53: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/runner.rb:66:in `run'
	52: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/util/busy.rb:19:in `busy'
	51: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/runner.rb:66:in `block in run'
	50: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/builder.rb:116:in `call'
	49: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	48: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	47: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	46: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/builtin/box_check_outdated.rb:23:in `call'
	45: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	44: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/builtin/call.rb:53:in `call'
	43: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/runner.rb:66:in `run'
	42: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/util/busy.rb:19:in `busy'
	41: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/runner.rb:66:in `block in run'
	40: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/builder.rb:116:in `call'
	39: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	38: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	37: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	36: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	35: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	34: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_storage_pool.rb:57:in `call'
	33: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	32: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	31: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	30: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_box_image.rb:146:in `call'
	29: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	28: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_domain_volume.rb:83:in `call'
	27: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	26: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_domain.rb:333:in `call'
	25: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	24: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/builtin/provision.rb:80:in `call'
	23: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	22: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-proxyconf-2.0.0/lib/vagrant-proxyconf/action/only_once.rb:21:in `call'
	21: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	20: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/prepare_nfs_valid_ids.rb:12:in `call'
	19: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	18: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
	17: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	16: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
	15: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	14: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
	13: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	12: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-proxyconf-2.0.0/lib/vagrant-proxyconf/action/only_once.rb:21:in `call'
	11: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	10: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/prepare_nfs_settings.rb:18:in `call'
	 9: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	 8: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/share_folders.rb:20:in `call'
	 7: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.3/lib/vagrant/action/warden.rb:34:in `call'
	 6: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:38:in `call'
	 5: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:38:in `synchronize'
	 4: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:41:in `block in call'
	 3: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:41:in `each'
	 2: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:79:in `block (2 levels) in call'
	 1: from /home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:245:in `handle_network_name_option'
/home/avangel/.vagrant.d/gems/2.6.0/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_networks.rb:315:in `create_private_network': undefined method `to_range' for nil:NilClass (NoMethodError)
```

**Comment by attila123** [comment]
@electrofelix Thanks again for the tip, `veryisolated` works indeed (I tested with my use case). So closing this issue.

Here is the final working sample Vagrantfile:
```
Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"

  config.vm.box_check_update = false

  config.vm.hostname = "vagrant-libvirt-issue-report"

  # https://github.com/vagrant-libvirt/vagrant-libvirt#networks
  config.vm.network :private_network,
    :libvirt__network_name => 'my-internal-net',
    :libvirt__dhcp_enabled => false,
    :libvirt__forward_mode => 'veryisolated'

  # https://github.com/vagrant-libvirt/vagrant-libvirt#domain-specific-options
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 512
    libvirt.cpus = 2
    # libvirt.cputopology :sockets => '2', :cores => '2', :threads => '1'
    # Older virt-manager GUI / qemu may not work correctly with the 'spice' type, in this case 'vnc' is often recommended.
    libvirt.graphics_type = 'vnc'
  end

end
```
After `vagrant up` everything is fine:
```
$ sudo virsh net-list --all
 Name              State      Autostart   Persistent  
------------------------------------------------------
 default           inactive   no          yes         
 my-internal-net   active     no          yes         
 vagrant-libvirt   active     no          yes         

$ sudo virsh net-dumpxml my-internal-net
<network connections='1' ipv6='yes'>
  <name>my-internal-net</name>
  <uuid>c245ae82-ac6c-4fee-bc1f-0f07efd352fa</uuid>
  <bridge name='virbr2' stp='on' delay='0'/>
  <mac address='52:54:00:91:2d:8b'/>
</network>
```
So if one wants to use the bridge name for virt-install-ing another VM, it can be parsed e.g. by `sudo virsh net-dumpxml my-internal-net | grep 'bridge name' | cut -d "'" -f2`.

**Comment by electrofelix** [comment]
@attila123 apologies, I read the README and then my brain assumed there would be a separator.

Would you have a few minutes to add your example to the README under the private network options as an example? Means we can recognize you with a contribution for working out the exact options as we seem to be missing any for people to follow.

**Comment by attila123** [comment]
@electrofelix No problems, it really helped. Yes, I will try do the example this week.
